/**
 * GSTR-1 demo documents — realistic outward supply mix for report preview.
 */

import { COMPANY_BILLING } from "@/lib/procurement/config";
import type { Gstr1Document, Gstr1LineItem } from "./gstr1-report-types";

const BRANCH_GSTIN: Record<string, string> = {
  "Head Office": COMPANY_BILLING.gstNumber,
  "Mumbai Branch": "27AABCD1234E2Z6",
  "Nagpur Branch": "27AABCD1234E3Z7",
};

function companyGstinForBranch(branch: string): string {
  return BRANCH_GSTIN[branch] ?? COMPANY_BILLING.gstNumber;
}

function line(
  id: string,
  product: string,
  hsn: string,
  qty: number,
  uqc: string,
  rate: number,
  discount: number,
  gstRate: number,
  interstate: boolean,
  taxability: Gstr1LineItem["taxabilityType"] = "taxable",
): Gstr1LineItem {
  const gross = qty * rate;
  const taxable = gross - discount;
  let igst = 0;
  let cgst = 0;
  let sgst = 0;
  if (taxability === "taxable") {
    const tax = Math.round(taxable * gstRate) / 100;
    if (interstate) igst = tax;
    else {
      cgst = Math.round(tax * 50) / 100;
      sgst = tax - cgst;
    }
  }
  const taxAmount = igst + cgst + sgst;
  return {
    id,
    product,
    hsn,
    quantity: qty,
    uqc,
    rate,
    grossAmount: gross,
    discount,
    taxableAmount: taxable,
    gstRate,
    igst,
    cgst,
    sgst,
    taxAmount,
    totalAmount: taxable + taxAmount,
    taxabilityType: taxability,
  };
}

function negateDoc(doc: Gstr1Document): Gstr1Document {
  return {
    ...doc,
    taxableAmount: -Math.abs(doc.taxableAmount),
    igst: -Math.abs(doc.igst),
    cgst: -Math.abs(doc.cgst),
    sgst: -Math.abs(doc.sgst),
    taxAmount: -Math.abs(doc.taxAmount),
    invoiceAmount: -Math.abs(doc.invoiceAmount),
    lines: doc.lines.map((l) => ({
      ...l,
      taxableAmount: -Math.abs(l.taxableAmount),
      igst: -Math.abs(l.igst),
      cgst: -Math.abs(l.cgst),
      sgst: -Math.abs(l.sgst),
      taxAmount: -Math.abs(l.taxAmount),
      totalAmount: -Math.abs(l.totalAmount),
    })),
  };
}

function buildDoc(
  base: Omit<
    Gstr1Document,
    | "companyGstin"
    | "taxableAmount"
    | "igst"
    | "cgst"
    | "sgst"
    | "taxAmount"
    | "invoiceAmount"
    | "gstRate"
  >,
): Gstr1Document {
  const lines = base.lines;
  const taxableAmount = lines.reduce((s, l) => s + l.taxableAmount, 0);
  const igst = lines.reduce((s, l) => s + l.igst, 0);
  const cgst = lines.reduce((s, l) => s + l.cgst, 0);
  const sgst = lines.reduce((s, l) => s + l.sgst, 0);
  const taxAmount = igst + cgst + sgst;
  const invoiceAmount = lines.reduce((s, l) => s + l.totalAmount, 0);
  const gstRate = lines.length === 1 ? lines[0].gstRate : 0;
  return {
    ...base,
    companyGstin: companyGstinForBranch(base.branch),
    taxableAmount,
    igst,
    cgst,
    sgst,
    taxAmount,
    invoiceAmount,
    gstRate,
  };
}

export const GSTR1_DEMO_DOCUMENTS: Gstr1Document[] = [
  buildDoc({
    id: "demo-si-b2b-001",
    docType: "sales_invoice",
    sourceId: 9001,
    sectionId: "b2b",
    documentNo: "SI-2025-0412",
    documentDate: "2025-04-18",
    customer: "Krishna Agro Distributors",
    gstin: "27AABCU9603R1ZM",
    registrationType: "registered",
    placeOfSupply: "Maharashtra",
    branch: "Head Office",
    invoiceType: "Regular",
    isInterstate: false,
    status: "posted",
    lines: [line("l1", "Urea 46% N", "31021000", 120, "BAG", 580, 0, 5, false)],
  }),
  buildDoc({
    id: "demo-si-b2b-002",
    docType: "sales_invoice",
    sourceId: 9002,
    sectionId: "b2b",
    documentNo: "SI-2025-0428",
    documentDate: "2025-05-06",
    customer: "Pune Farmers Cooperative",
    gstin: "27AAACF1234G1Z5",
    registrationType: "registered",
    placeOfSupply: "Maharashtra",
    branch: "Head Office",
    invoiceType: "Regular",
    isInterstate: false,
    status: "posted",
    lines: [
      line("l1", "DAP Fertilizer", "31053000", 80, "BAG", 1420, 2000, 5, false),
      line("l2", "Micronutrient Mix", "31059090", 40, "BAG", 890, 0, 12, false),
    ],
  }),
  buildDoc({
    id: "demo-si-b2b-003",
    docType: "sales_invoice",
    sourceId: 9003,
    sectionId: "b2b",
    documentNo: "SI-2025-0515",
    documentDate: "2025-05-22",
    customer: "Nashik Crop Care Pvt Ltd",
    gstin: "27AABCN5678H1Z2",
    registrationType: "registered",
    placeOfSupply: "Maharashtra",
    branch: "Mumbai Branch",
    invoiceType: "Regular",
    isInterstate: false,
    status: "posted",
    lines: [line("l1", "Hybrid Maize Seeds", "12099100", 200, "KG", 420, 0, 5, false)],
  }),
  buildDoc({
    id: "demo-si-b2b-004",
    docType: "sales_invoice",
    sourceId: 9004,
    sectionId: "b2b",
    documentNo: "SI-2025-0602",
    documentDate: "2025-06-02",
    customer: "Gujarat Agri Traders",
    gstin: "24AABCG1234F1Z8",
    registrationType: "registered",
    placeOfSupply: "Gujarat",
    branch: "Head Office",
    invoiceType: "Regular",
    isInterstate: true,
    status: "posted",
    lines: [line("l1", "Potash MOP", "31042000", 150, "BAG", 760, 0, 5, true)],
  }),
  buildDoc({
    id: "demo-si-b2b-005",
    docType: "sales_invoice",
    sourceId: 9005,
    sectionId: "b2b",
    documentNo: "SI-2025-0610",
    documentDate: "2025-06-10",
    customer: "Karnataka Seeds Ltd",
    gstin: "29AABCK9012K1Z3",
    registrationType: "registered",
    placeOfSupply: "Karnataka",
    branch: "Head Office",
    invoiceType: "Regular",
    isInterstate: true,
    status: "needs-review",
    lines: [line("l1", "Bio Pesticide", "38089199", 60, "LTR", 1850, 0, 18, true)],
  }),
  buildDoc({
    id: "demo-si-b2cl-001",
    docType: "sales_invoice",
    sourceId: 9010,
    sectionId: "b2c-large",
    documentNo: "SI-2025-0520",
    documentDate: "2025-05-20",
    customer: "Walk-in Customer — Ahmed",
    gstin: "",
    registrationType: "unregistered",
    placeOfSupply: "Maharashtra",
    branch: "Head Office",
    invoiceType: "Regular",
    isInterstate: false,
    status: "posted",
    lines: [line("l1", "Tractor Sprayer Kit", "84248100", 5, "NOS", 58000, 5000, 18, false)],
  }),
  buildDoc({
    id: "demo-si-b2cs-001",
    docType: "sales_invoice",
    sourceId: 9011,
    sectionId: "b2c-small",
    documentNo: "SI-2025-0410",
    documentDate: "2025-04-10",
    customer: "Retail — Village Store A",
    gstin: "",
    registrationType: "unregistered",
    placeOfSupply: "Maharashtra",
    branch: "Head Office",
    invoiceType: "Regular",
    isInterstate: false,
    status: "posted",
    lines: [line("l1", "Vegetable Seeds Pack", "12099100", 30, "PKT", 180, 0, 5, false)],
  }),
  buildDoc({
    id: "demo-si-b2cs-002",
    docType: "sales_invoice",
    sourceId: 9012,
    sectionId: "b2c-small",
    documentNo: "SI-2025-0505",
    documentDate: "2025-05-05",
    customer: "Retail — Farm Mart",
    gstin: "",
    registrationType: "unregistered",
    placeOfSupply: "Maharashtra",
    branch: "Mumbai Branch",
    invoiceType: "Regular",
    isInterstate: false,
    status: "posted",
    lines: [line("l1", "Garden Hose Pipe", "39173290", 12, "NOS", 950, 100, 18, false)],
  }),
  buildDoc({
    id: "demo-si-b2cs-003",
    docType: "sales_invoice",
    sourceId: 9013,
    sectionId: "b2c-small",
    documentNo: "SI-2025-0525",
    documentDate: "2025-05-25",
    customer: "Retail — Green Valley",
    gstin: "",
    registrationType: "unregistered",
    placeOfSupply: "Maharashtra",
    branch: "Head Office",
    invoiceType: "Regular",
    isInterstate: false,
    status: "posted",
    lines: [line("l1", "Organic Compost", "31010099", 50, "BAG", 320, 0, 5, false)],
  }),
  buildDoc({
    id: "demo-si-b2cs-004",
    docType: "sales_invoice",
    sourceId: 9014,
    sectionId: "b2c-small",
    documentNo: "SI-2025-0608",
    documentDate: "2025-06-08",
    customer: "Retail — Kisan Kendra",
    gstin: "",
    registrationType: "unregistered",
    placeOfSupply: "Maharashtra",
    branch: "Nagpur Branch",
    invoiceType: "Regular",
    isInterstate: false,
    status: "posted",
    lines: [line("l1", "Hand Sprayer 16L", "84248100", 8, "NOS", 2200, 0, 18, false)],
  }),
  buildDoc({
    id: "demo-si-exp-001",
    docType: "sales_invoice",
    sourceId: 9020,
    sectionId: "export-sez",
    documentNo: "SI-2025-EX-001",
    documentDate: "2025-05-14",
    customer: "East Africa Agri Imports",
    gstin: "",
    registrationType: "unregistered",
    placeOfSupply: "Outside India",
    branch: "Head Office",
    invoiceType: "Export with Payment",
    isInterstate: true,
    status: "posted",
    lines: [line("l1", "Neem Oil Formulation", "15159099", 200, "LTR", 680, 0, 0, true)],
  }),
  buildDoc({
    id: "demo-si-exp-002",
    docType: "sales_invoice",
    sourceId: 9021,
    sectionId: "export-sez",
    documentNo: "SI-2025-EX-002",
    documentDate: "2025-05-28",
    customer: "Global Farm Solutions FZE",
    gstin: "",
    registrationType: "unregistered",
    placeOfSupply: "Outside India",
    branch: "Head Office",
    invoiceType: "Export under LUT",
    isInterstate: true,
    status: "posted",
    lines: [line("l1", "Bio Fertilizer Consignment", "31010099", 500, "KG", 120, 0, 0, true)],
  }),
  buildDoc({
    id: "demo-si-sez-001",
    docType: "sales_invoice",
    sourceId: 9022,
    sectionId: "export-sez",
    documentNo: "SI-2025-SEZ-001",
    documentDate: "2025-06-05",
    customer: "Pune SEZ Agro Unit",
    gstin: "27AABCS1234E1Z9",
    registrationType: "registered",
    placeOfSupply: "Maharashtra",
    branch: "Head Office",
    invoiceType: "SEZ with Payment",
    isInterstate: false,
    status: "posted",
    lines: [line("l1", "Precision Seeder", "84321000", 2, "NOS", 125000, 0, 18, false)],
  }),
  buildDoc({
    id: "demo-si-sez-002",
    docType: "sales_invoice",
    sourceId: 9023,
    sectionId: "export-sez",
    documentNo: "SI-2025-SEZ-002",
    documentDate: "2025-06-12",
    customer: "Aurangabad SEZ Processing",
    gstin: "27AABCA5678B1Z4",
    registrationType: "registered",
    placeOfSupply: "Maharashtra",
    branch: "Head Office",
    invoiceType: "SEZ without Payment",
    isInterstate: false,
    status: "posted",
    lines: [line("l1", "Irrigation Controller", "90328990", 4, "NOS", 42000, 0, 18, false)],
  }),
  negateDoc(
    buildDoc({
      id: "demo-cn-reg-001",
      docType: "credit_note",
      sourceId: 9101,
      sectionId: "cn-dn-registered",
      documentNo: "CN-2025-0018",
      documentDate: "2025-05-30",
      customer: "Krishna Agro Distributors",
      gstin: "27AABCU9603R1ZM",
      registrationType: "registered",
      placeOfSupply: "Maharashtra",
      branch: "Head Office",
      invoiceType: "Credit Note",
      isInterstate: false,
      status: "posted",
      lines: [line("l1", "Urea 46% N — Sales Return", "31021000", 10, "BAG", 580, 0, 5, false)],
    }),
  ),
  negateDoc(
    buildDoc({
      id: "demo-cn-unreg-001",
      docType: "credit_note",
      sourceId: 9102,
      sectionId: "cn-dn-unregistered",
      documentNo: "CN-2025-0022",
      documentDate: "2025-06-15",
      customer: "Retail — Farm Mart",
      gstin: "",
      registrationType: "unregistered",
      placeOfSupply: "Maharashtra",
      branch: "Mumbai Branch",
      invoiceType: "Credit Note",
      isInterstate: false,
      status: "posted",
      lines: [line("l1", "Garden Hose — Return", "39173290", 2, "NOS", 950, 0, 18, false)],
    }),
  ),
  buildDoc({
    id: "demo-dn-reg-001",
    docType: "debit_note",
    sourceId: 9201,
    sectionId: "cn-dn-registered",
    documentNo: "DN-2025-0006",
    documentDate: "2025-06-18",
    customer: "Pune Farmers Cooperative",
    gstin: "27AAACF1234G1Z5",
    registrationType: "registered",
    placeOfSupply: "Maharashtra",
    branch: "Head Office",
    invoiceType: "Debit Note",
    isInterstate: false,
    status: "posted",
    lines: [line("l1", "Rate Difference — DAP", "31053000", 5, "BAG", 1420, 0, 5, false)],
  }),
  buildDoc({
    id: "demo-si-nil-001",
    docType: "sales_invoice",
    sourceId: 9030,
    sectionId: "nil-exempt-non-gst",
    documentNo: "SI-2025-NIL-001",
    documentDate: "2025-05-08",
    customer: "Organic Growers Association",
    gstin: "27AABCO7890N1Z1",
    registrationType: "registered",
    placeOfSupply: "Maharashtra",
    branch: "Head Office",
    invoiceType: "Regular",
    isInterstate: false,
    status: "posted",
    lines: [line("l1", "Fresh Vegetables", "07099990", 100, "KG", 45, 0, 0, false, "nil-rated")],
  }),
  buildDoc({
    id: "demo-si-exempt-001",
    docType: "sales_invoice",
    sourceId: 9031,
    sectionId: "nil-exempt-non-gst",
    documentNo: "SI-2025-EXM-001",
    documentDate: "2025-05-16",
    customer: "Rural Health NGO",
    gstin: "",
    registrationType: "unregistered",
    placeOfSupply: "Maharashtra",
    branch: "Head Office",
    invoiceType: "Regular",
    isInterstate: false,
    status: "posted",
    lines: [line("l1", "Educational Farm Kit", "90230090", 20, "NOS", 250, 0, 0, false, "exempt")],
  }),
  buildDoc({
    id: "demo-si-nongst-001",
    docType: "sales_invoice",
    sourceId: 9032,
    sectionId: "nil-exempt-non-gst",
    documentNo: "SI-2025-NG-001",
    documentDate: "2025-06-01",
    customer: "Walk-in — Petty Cash",
    gstin: "",
    registrationType: "unregistered",
    placeOfSupply: "Maharashtra",
    branch: "Head Office",
    invoiceType: "Regular",
    isInterstate: false,
    status: "posted",
    lines: [line("l1", "Petty Packing Material", "39232990", 15, "NOS", 80, 0, 0, false, "non-gst")],
  }),
];
