import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import { formatMoney, formatMoneyNumber } from "@/lib/accounts/money-format";
import type { InventoryRegisterTotals } from "./inventory-register-data";
import {
  formatInventoryRegisterDate,
  formatQty,
  INVENTORY_TRANSACTION_TYPE_LABELS,
  type InventoryRegisterRow,
} from "./inventory-register-data";

const COMPANY_NAME = "Dharitri Sutra Agri Solutions Pvt Ltd";
const REPORT_NAME = "Inventory Register";

export interface InventoryRegisterExportMeta {
  dateFrom: string;
  dateTo: string;
  financialYear: string;
  warehouse: string;
  product: string;
  category: string;
  batchNo: string;
  transactionType: string;
  search: string;
}

function generatedOnLabel(): string {
  return new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function metaRows(meta: InventoryRegisterExportMeta) {
  return [
    ["Company Name", COMPANY_NAME],
    ["Report Name", REPORT_NAME],
    ["Date Range", `${meta.dateFrom} to ${meta.dateTo}`],
    ["Financial Year", meta.financialYear],
    ["Warehouse", meta.warehouse],
    ["Product", meta.product],
    ["Category", meta.category],
    ["Batch No.", meta.batchNo],
    ["Transaction Type", meta.transactionType],
    ["Search", meta.search || "—"],
    ["Generated By", ACCOUNTS_CURRENT_USER],
    ["Generated On", generatedOnLabel()],
  ];
}

function exportDataRows(rows: InventoryRegisterRow[]) {
  return rows.map((row) => ({
    Date: formatInventoryRegisterDate(row.date),
    "Transaction Type": INVENTORY_TRANSACTION_TYPE_LABELS[row.transactionType],
    "Document No.": row.documentNo,
    Product: row.productName,
    SKU: row.sku,
    "Batch No.": row.batchNo,
    Warehouse: row.warehouse,
    "In Qty": row.inQty || "",
    "Out Qty": row.outQty || "",
    "Balance Qty": row.balanceQty,
    UOM: row.uom,
    "Cost Price": row.costPrice,
    "Stock Value": row.stockValue,
  }));
}

export async function exportInventoryRegisterToExcel(
  rows: InventoryRegisterRow[],
  meta: InventoryRegisterExportMeta,
  totals: InventoryRegisterTotals,
): Promise<void> {
  const XLSX = await import("xlsx");

  const dataRows = exportDataRows(rows).map((r) => ({
    Date: r.Date,
    "Transaction Type": r["Transaction Type"],
    "Document No.": r["Document No."],
    Product: r.Product,
    SKU: r.SKU,
    "Batch No.": r["Batch No."],
    Warehouse: r.Warehouse,
    "In Qty": r["In Qty"],
    "Out Qty": r["Out Qty"],
    "Balance Qty": r["Balance Qty"],
    UOM: r.UOM,
    "Cost Price (₹)": r["Cost Price"],
    "Stock Value (₹)": r["Stock Value"],
  }));

  const sheet = XLSX.utils.json_to_sheet(dataRows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, sheet, "Inventory Register");

  const info = XLSX.utils.aoa_to_sheet(metaRows(meta));
  XLSX.utils.book_append_sheet(wb, info, "Report Info");

  const summary = XLSX.utils.aoa_to_sheet([
    ["Total In Quantity", totals.totalInQty],
    ["Total Out Quantity", totals.totalOutQty],
  ]);
  XLSX.utils.book_append_sheet(wb, summary, "Totals");

  const date = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `Inventory_Register_${date}.xlsx`);
}

export function exportInventoryRegisterToPdf(
  rows: InventoryRegisterRow[],
  meta: InventoryRegisterExportMeta,
  totals: InventoryRegisterTotals,
): void {
  const tableRows = rows
    .map(
      (row) => `<tr>
        <td>${formatInventoryRegisterDate(row.date)}</td>
        <td>${INVENTORY_TRANSACTION_TYPE_LABELS[row.transactionType]}</td>
        <td class="mono">${row.documentNo}</td>
        <td>${row.productName}</td>
        <td class="mono">${row.sku}</td>
        <td class="mono">${row.batchNo}</td>
        <td>${row.warehouse}</td>
        <td class="num">${formatQty(row.inQty)}</td>
        <td class="num">${formatQty(row.outQty)}</td>
        <td class="num">${formatQty(row.balanceQty)}</td>
        <td>${row.uom}</td>
        <td class="num">${formatMoney(row.costPrice)}</td>
        <td class="num">${formatMoney(row.stockValue)}</td>
      </tr>`,
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${REPORT_NAME}</title>
  <style>
    @media print { @page { margin: 10mm; size: landscape; } }
    body { font-family: system-ui, sans-serif; font-size: 9px; padding: 16px; color: #111; }
    .header { display: flex; align-items: flex-start; gap: 12px; margin-bottom: 12px; }
    .logo { width: 36px; height: 36px; border-radius: 8px; background: linear-gradient(135deg, #F47920, #D96A10); color: #fff; font-weight: 800; font-size: 13px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
    h1 { font-size: 14px; margin: 0 0 2px; color: #1A3A96; }
    .company { font-size: 10px; font-weight: 600; margin: 0 0 4px; }
    .meta { color: #555; font-size: 8px; line-height: 1.5; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th, td { border: 1px solid #ddd; padding: 4px 5px; text-align: left; }
    th { background: #fff; font-size: 8px; text-transform: uppercase; font-weight: 700; }
    .num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
    .mono { font-family: ui-monospace, monospace; font-size: 8px; }
    tfoot td { font-weight: 700; background: #f8fafc; border-top: 2px solid #ccc; }
    .footer-meta { margin-top: 12px; font-size: 8px; color: #666; }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">DS</div>
    <div>
      <p class="company">${COMPANY_NAME}</p>
      <h1>${REPORT_NAME}</h1>
      <p class="meta">
        Date Range: ${meta.dateFrom} to ${meta.dateTo}<br />
        Financial Year: ${meta.financialYear}<br />
        Warehouse: ${meta.warehouse} · Product: ${meta.product} · Category: ${meta.category}<br />
        Batch: ${meta.batchNo} · Transaction Type: ${meta.transactionType}<br />
        Generated By: ${ACCOUNTS_CURRENT_USER} · Generated On: ${generatedOnLabel()}
      </p>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Transaction Type</th>
        <th>Document No.</th>
        <th>Product</th>
        <th>SKU</th>
        <th>Batch No.</th>
        <th>Warehouse</th>
        <th class="num">In Qty</th>
        <th class="num">Out Qty</th>
        <th class="num">Balance Qty</th>
        <th>UOM</th>
        <th class="num">Cost Price</th>
        <th class="num">Stock Value</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
    <tfoot>
      <tr>
        <td colspan="7">Totals</td>
        <td class="num">${formatQty(totals.totalInQty)}</td>
        <td class="num">${formatQty(totals.totalOutQty)}</td>
        <td colspan="4"></td>
      </tr>
    </tfoot>
  </table>
  <p class="footer-meta">
    Total In Quantity: ${formatQty(totals.totalInQty)} ·
    Total Out Quantity: ${formatQty(totals.totalOutQty)} ·
    ${totals.count} movement(s)
  </p>
  <script>window.onload = () => window.print();</script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
}
