import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import { formatMoney } from "@/lib/accounts/money-format";
import type { StockLedgerDisplayRow, StockLedgerSummary } from "./stock-ledger-data";
import { formatQty } from "./stock-ledger-data";

const COMPANY_NAME = "Dharitri Sutra Agri Solutions Pvt Ltd";
const REPORT_NAME = "Stock Ledger";

export interface StockLedgerExportMeta {
  dateFrom: string;
  dateTo: string;
  financialYear: string;
  warehouse: string;
  batchNo: string;
  search: string;
}

function generatedOnLabel(): string {
  return new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function metaRows(summary: StockLedgerSummary, meta: StockLedgerExportMeta) {
  return [
    ["Company Name", COMPANY_NAME],
    ["Report Name", REPORT_NAME],
    ["Product Name", summary.productName],
    ["SKU", summary.sku],
    ["Category", summary.category],
    ["Date Range", `${meta.dateFrom} to ${meta.dateTo}`],
    ["Financial Year", meta.financialYear],
    ["Warehouse", meta.warehouse],
    ["Batch No.", meta.batchNo],
    ["Search", meta.search || "—"],
    ["Opening Quantity", `${summary.openingQty} ${summary.unit}`],
    ["Total In Quantity", `${summary.totalInQty} ${summary.unit}`],
    ["Total Out Quantity", `${summary.totalOutQty} ${summary.unit}`],
    ["Closing Quantity", `${summary.closingQty} ${summary.unit}`],
    ["Generated By", ACCOUNTS_CURRENT_USER],
    ["Generated On", generatedOnLabel()],
  ];
}

function exportDataRows(rows: StockLedgerDisplayRow[]) {
  return rows.map((row) => ({
    Date: row.date,
    "Document No.": row.documentNo,
    "Transaction Type": row.transactionTypeLabel,
    Warehouse: row.warehouse,
    "Batch No.": row.batchNo,
    "In Qty": row.inQty || "",
    "Out Qty": row.outQty || "",
    "Balance Qty": row.balanceQty,
    Unit: row.unit,
    "Cost Price (₹)": row.costPrice || "",
  }));
}

export async function exportStockLedgerToExcel(
  rows: StockLedgerDisplayRow[],
  summary: StockLedgerSummary,
  meta: StockLedgerExportMeta,
): Promise<void> {
  const XLSX = await import("xlsx");

  const sheet = XLSX.utils.json_to_sheet(exportDataRows(rows));
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, sheet, "Stock Ledger");

  const info = XLSX.utils.aoa_to_sheet(metaRows(summary, meta));
  XLSX.utils.book_append_sheet(wb, info, "Report Info");

  const totals = XLSX.utils.aoa_to_sheet([
    ["Opening Quantity", summary.openingQty],
    ["Total In Quantity", summary.totalInQty],
    ["Total Out Quantity", summary.totalOutQty],
    ["Closing Quantity", summary.closingQty],
    ["Unit", summary.unit],
  ]);
  XLSX.utils.book_append_sheet(wb, totals, "Totals");

  const date = new Date().toISOString().slice(0, 10);
  const sku = summary.sku.replace(/[^a-zA-Z0-9]/g, "_");
  XLSX.writeFile(wb, `Stock_Ledger_${sku}_${date}.xlsx`);
}

export function exportStockLedgerToPdf(
  rows: StockLedgerDisplayRow[],
  summary: StockLedgerSummary,
  meta: StockLedgerExportMeta,
): void {
  const tableRows = rows
    .map(
      (row) => `<tr class="${row.kind === "closing" ? "closing-row" : row.kind === "opening" ? "opening-row" : ""}">
        <td>${row.date}</td>
        <td class="mono">${row.documentNo}</td>
        <td>${row.transactionTypeLabel}</td>
        <td>${row.warehouse}</td>
        <td class="mono">${row.batchNo}</td>
        <td class="num">${formatQty(row.inQty)}</td>
        <td class="num">${formatQty(row.outQty)}</td>
        <td class="num">${formatQty(row.balanceQty)}</td>
        <td>${row.unit}</td>
        <td class="num">${row.costPrice ? formatMoney(row.costPrice) : "—"}</td>
      </tr>`,
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${REPORT_NAME}</title>
  <style>
    @media print { @page { margin: 10mm; size: landscape; } }
    body { font-family: system-ui, sans-serif; font-size: 9px; padding: 16px; color: #111; }
    .header { display: flex; align-items: flex-start; gap: 12px; margin-bottom: 12px; }
    .logo { width: 36px; height: 36px; border-radius: 8px; background: linear-gradient(135deg, #F47920, #D96A10); color: #fff; font-weight: 800; font-size: 13px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
    h1 { font-size: 14px; margin: 0 0 2px; color: #1A3A96; }
    .company { font-size: 10px; font-weight: 600; margin: 0 0 4px; }
    .meta { color: #555; font-size: 8px; line-height: 1.5; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th, td { border: 1px solid #ddd; padding: 4px 5px; text-align: left; }
    th { background: #fff; font-size: 8px; text-transform: uppercase; font-weight: 700; }
    .num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
    .mono { font-family: ui-monospace, monospace; font-size: 8px; }
    .opening-row { background: #f8fafc; font-weight: 600; }
    .closing-row { background: #FFF3E8; font-weight: 700; border-top: 2px solid #F47920; }
    tfoot td { font-weight: 700; background: #f8fafc; border-top: 2px solid #ccc; }
    .footer-meta { margin-top: 12px; font-size: 8px; color: #666; }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">DS</div>
    <div>
      <p class="company">${COMPANY_NAME}</p>
      <h1>${REPORT_NAME}</h1>
      <p class="meta">
        Product: ${summary.productName} (${summary.sku}) · Category: ${summary.category}<br />
        Date Range: ${meta.dateFrom} to ${meta.dateTo}<br />
        Financial Year: ${meta.financialYear} · Warehouse: ${meta.warehouse} · Batch: ${meta.batchNo}<br />
        Opening Qty: ${formatQty(summary.openingQty, true)} ${summary.unit} ·
        Closing Qty: ${formatQty(summary.closingQty, true)} ${summary.unit}<br />
        Generated By: ${ACCOUNTS_CURRENT_USER} · Generated On: ${generatedOnLabel()}
      </p>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Document No.</th>
        <th>Transaction Type</th>
        <th>Warehouse</th>
        <th>Batch No.</th>
        <th class="num">In Qty</th>
        <th class="num">Out Qty</th>
        <th class="num">Balance Qty</th>
        <th>Unit</th>
        <th class="num">Cost Price</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
    <tfoot>
      <tr>
        <td colspan="5">Totals</td>
        <td class="num">${formatQty(summary.totalInQty, true)}</td>
        <td class="num">${formatQty(summary.totalOutQty, true)}</td>
        <td class="num">${formatQty(summary.closingQty, true)} ${summary.unit}</td>
        <td colspan="2"></td>
      </tr>
    </tfoot>
  </table>
  <p class="footer-meta">
    Total In Quantity: ${formatQty(summary.totalInQty, true)} ${summary.unit} ·
    Total Out Quantity: ${formatQty(summary.totalOutQty, true)} ${summary.unit} ·
    Closing Quantity: ${formatQty(summary.closingQty, true)} ${summary.unit}
  </p>
  <script>window.onload = () => window.print();</script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
}
