import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import { formatMoney } from "@/lib/accounts/money-format";
import type { StockLedgerRow, StockLedgerSummary } from "./stock-ledger-data";
import {
  formatQty,
  formatStockLedgerDate,
  STOCK_LEDGER_TRANSACTION_TYPE_LABELS,
} from "./stock-ledger-data";

const COMPANY_NAME = "Dharitri Sutra Agri Solutions Pvt Ltd";
const REPORT_NAME = "Stock Ledger";

export interface StockLedgerExportMeta {
  dateFrom: string;
  dateTo: string;
  financialYear: string;
  warehouse: string;
  product: string;
  batchNo: string;
  transactionType: string;
  documentNo: string;
  search: string;
}

function generatedOnLabel(): string {
  return new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function metaRows(summary: StockLedgerSummary, meta: StockLedgerExportMeta) {
  return [
    ["Company Name", COMPANY_NAME],
    ["Report Name", REPORT_NAME],
    ["Date Range", `${meta.dateFrom} to ${meta.dateTo}`],
    ["Financial Year", meta.financialYear],
    ["Product", meta.product],
    ["Warehouse", meta.warehouse],
    ["Batch No.", meta.batchNo],
    ["Transaction Type", meta.transactionType],
    ["Document No.", meta.documentNo],
    ["Search", meta.search || "—"],
    ["Total Products", summary.totalProducts],
    ["Total Inward Qty", summary.totalInwardQty],
    ["Total Outward Qty", summary.totalOutwardQty],
    ["Net Movement", summary.netMovement],
    ["Current Closing Stock", summary.closingStock],
    ["Current Stock Value", summary.stockValue],
    ["Generated By", ACCOUNTS_CURRENT_USER],
    ["Generated On", generatedOnLabel()],
  ];
}

function exportDataRows(rows: StockLedgerRow[]) {
  return rows.map((row) => ({
    Date: formatStockLedgerDate(row.date),
    "Document No.": row.documentNo,
    "Transaction Type": STOCK_LEDGER_TRANSACTION_TYPE_LABELS[row.transactionType],
    "Product Code": row.productCode,
    "Product Name": row.productName,
    Warehouse: row.warehouse,
    "Batch No.": row.batchNo,
    "Mfg Date": row.mfgDate ? formatStockLedgerDate(row.mfgDate) : "",
    "Expiry Date": row.expiryDate ? formatStockLedgerDate(row.expiryDate) : "",
    "Opening Qty": row.openingQty || "",
    "In Qty": row.inQty || "",
    "Out Qty": row.outQty || "",
    "Closing Qty": row.closingQty,
    Unit: row.unit,
    Rate: row.rate || "",
    Value: row.value || "",
    "Reference Module": row.referenceModule,
    "Created By": row.createdBy,
    Remarks: row.remarks,
  }));
}

function csvEscape(value: unknown): string {
  const str = String(value ?? "");
  if (str.includes(",") || str.includes('"') || str.includes("\n")) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

export async function exportStockLedgerToExcel(
  rows: StockLedgerRow[],
  summary: StockLedgerSummary,
  meta: StockLedgerExportMeta,
): Promise<void> {
  const XLSX = await import("xlsx");

  const sheet = XLSX.utils.json_to_sheet(exportDataRows(rows));
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, sheet, "Stock Ledger");

  const info = XLSX.utils.aoa_to_sheet(metaRows(summary, meta));
  XLSX.utils.book_append_sheet(wb, info, "Report Info");

  const date = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `Stock_Ledger_${date}.xlsx`);
}

export function exportStockLedgerToCsv(
  rows: StockLedgerRow[],
  summary: StockLedgerSummary,
  meta: StockLedgerExportMeta,
): void {
  const data = exportDataRows(rows);
  const headers = Object.keys(data[0] ?? {});
  const lines = [
    headers.join(","),
    ...data.map((row) => headers.map((h) => csvEscape(row[h as keyof typeof row])).join(",")),
  ];

  const blob = new Blob([lines.join("\n")], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `Stock_Ledger_${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportStockLedgerToPdf(
  rows: StockLedgerRow[],
  summary: StockLedgerSummary,
  meta: StockLedgerExportMeta,
): void {
  const tableRows = rows
    .map(
      (row) => `<tr>
        <td>${formatStockLedgerDate(row.date)}</td>
        <td class="mono">${row.documentNo}</td>
        <td>${STOCK_LEDGER_TRANSACTION_TYPE_LABELS[row.transactionType]}</td>
        <td class="mono">${row.productCode}</td>
        <td>${row.productName}</td>
        <td>${row.warehouse}</td>
        <td class="mono">${row.batchNo}</td>
        <td class="num">${formatQty(row.openingQty, true)}</td>
        <td class="num">${formatQty(row.inQty)}</td>
        <td class="num">${formatQty(row.outQty)}</td>
        <td class="num">${formatQty(row.closingQty, true)}</td>
        <td>${row.unit}</td>
        <td class="num">${row.rate ? formatMoney(row.rate) : "—"}</td>
        <td class="num">${row.value ? formatMoney(row.value) : "—"}</td>
      </tr>`,
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${REPORT_NAME}</title>
  <style>
    @media print { @page { margin: 8mm; size: landscape; } }
    body { font-family: system-ui, sans-serif; font-size: 8px; padding: 12px; color: #111; }
    .header { display: flex; align-items: flex-start; gap: 12px; margin-bottom: 10px; }
    .logo { width: 32px; height: 32px; border-radius: 8px; background: linear-gradient(135deg, #F47920, #D96A10); color: #fff; font-weight: 800; font-size: 12px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
    h1 { font-size: 13px; margin: 0 0 2px; color: #1A3A96; }
    .company { font-size: 9px; font-weight: 600; margin: 0 0 4px; }
    .meta { color: #555; font-size: 7px; line-height: 1.5; }
    table { width: 100%; border-collapse: collapse; margin-top: 6px; }
    th, td { border: 1px solid #ddd; padding: 3px 4px; text-align: left; }
    th { background: #f8fafc; font-size: 7px; text-transform: uppercase; font-weight: 700; }
    .num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
    .mono { font-family: ui-monospace, monospace; font-size: 7px; }
    tfoot td { font-weight: 700; background: #f8fafc; border-top: 2px solid #ccc; }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">DS</div>
    <div>
      <p class="company">${COMPANY_NAME}</p>
      <h1>${REPORT_NAME}</h1>
      <p class="meta">
        Date Range: ${meta.dateFrom} to ${meta.dateTo}<br />
        Product: ${meta.product} · Warehouse: ${meta.warehouse} · Batch: ${meta.batchNo}<br />
        Total Products: ${summary.totalProducts} · Inward: ${formatQty(summary.totalInwardQty, true)} · Outward: ${formatQty(summary.totalOutwardQty, true)} · Closing: ${formatQty(summary.closingStock, true)} · Value: ${formatMoney(summary.stockValue)}<br />
        Generated By: ${ACCOUNTS_CURRENT_USER} · Generated On: ${generatedOnLabel()}
      </p>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Document No.</th>
        <th>Type</th>
        <th>Code</th>
        <th>Product</th>
        <th>Warehouse</th>
        <th>Batch</th>
        <th class="num">Opening</th>
        <th class="num">In</th>
        <th class="num">Out</th>
        <th class="num">Closing</th>
        <th>Unit</th>
        <th class="num">Rate</th>
        <th class="num">Value</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
    <tfoot>
      <tr>
        <td colspan="7">Totals</td>
        <td class="num">${formatQty(summary.totalInwardQty, true)}</td>
        <td class="num">${formatQty(summary.totalOutwardQty, true)}</td>
        <td class="num">${formatQty(summary.closingStock, true)}</td>
        <td colspan="3"></td>
      </tr>
    </tfoot>
  </table>
  <script>window.onload = () => window.print();</script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
}
