/**
 * GSTR-3B Phase 1 demo documents — ensures meaningful report data
 * (local / interstate / export / SEZ sales + local / interstate purchases).
 */

import { COMPANY_BILLING } from "@/lib/procurement/config";
import type { Gstr3bDocument } from "./gstr3b-report-types";

const HO = "Head Office";
const GSTIN = COMPANY_BILLING.gstNumber;

function amt(
  taxable: number,
  rate: number,
  interstate: boolean,
): { taxableValue: number; cgst: number; sgst: number; igst: number; taxAmount: number } {
  const tax = Math.round(taxable * rate) / 100;
  if (interstate) {
    return { taxableValue: taxable, cgst: 0, sgst: 0, igst: tax, taxAmount: tax };
  }
  const cgst = Math.round(tax * 50) / 100;
  const sgst = Math.round((tax - cgst) * 100) / 100;
  return { taxableValue: taxable, cgst, sgst, igst: 0, taxAmount: cgst + sgst };
}

export const GSTR3B_DEMO_DOCUMENTS: Gstr3bDocument[] = [
  // Local B2B sales
  {
    id: "demo-si-local-1",
    docType: "sales_invoice",
    sourceId: 9301,
    documentNo: "SI-3B-0001",
    documentDate: "2026-06-05",
    partyName: "Green Valley Agro Ltd",
    gstin: "27AABCG1111A1Z1",
    placeOfSupply: "Maharashtra",
    state: "Maharashtra",
    branch: HO,
    companyGstin: GSTIN,
    ...amt(250_000, 18, false),
    taxability: "taxable",
    supplyKind: "domestic_b2b",
    isInterstate: false,
    sign: 1,
    isDemo: true,
  },
  {
    id: "demo-si-local-2",
    docType: "sales_invoice",
    sourceId: 9302,
    documentNo: "SI-3B-0002",
    documentDate: "2026-06-12",
    partyName: "Pune Farm Supplies",
    gstin: "27AABCP2222B1Z2",
    placeOfSupply: "Maharashtra",
    state: "Maharashtra",
    branch: HO,
    companyGstin: GSTIN,
    ...amt(180_000, 12, false),
    taxability: "taxable",
    supplyKind: "domestic_b2b",
    isInterstate: false,
    sign: 1,
    isDemo: true,
  },
  // B2C local
  {
    id: "demo-si-b2c-1",
    docType: "sales_invoice",
    sourceId: 9303,
    documentNo: "SI-3B-0003",
    documentDate: "2026-06-08",
    partyName: "Walk-in Customer — Nagpur",
    gstin: "",
    placeOfSupply: "Maharashtra",
    state: "Maharashtra",
    branch: "Nagpur Branch",
    companyGstin: "27AABCD1234E3Z7",
    ...amt(45_000, 18, false),
    taxability: "taxable",
    supplyKind: "domestic_b2c",
    isInterstate: false,
    sign: 1,
    isDemo: true,
  },
  // Interstate B2B
  {
    id: "demo-si-inter-1",
    docType: "sales_invoice",
    sourceId: 9304,
    documentNo: "SI-3B-0004",
    documentDate: "2026-06-10",
    partyName: "Gujarat Crop Care Pvt Ltd",
    gstin: "24AABCG3333C1Z3",
    placeOfSupply: "Gujarat",
    state: "Gujarat",
    branch: HO,
    companyGstin: GSTIN,
    ...amt(320_000, 18, true),
    taxability: "taxable",
    supplyKind: "interstate",
    isInterstate: true,
    sign: 1,
    isDemo: true,
  },
  {
    id: "demo-si-inter-2",
    docType: "sales_invoice",
    sourceId: 9305,
    documentNo: "SI-3B-0005",
    documentDate: "2026-06-18",
    partyName: "Karnataka Seeds House",
    gstin: "29AABCK4444D1Z4",
    placeOfSupply: "Karnataka",
    state: "Karnataka",
    branch: HO,
    companyGstin: GSTIN,
    ...amt(210_000, 12, true),
    taxability: "taxable",
    supplyKind: "interstate",
    isInterstate: true,
    sign: 1,
    isDemo: true,
  },
  {
    id: "demo-si-inter-3",
    docType: "sales_invoice",
    sourceId: 9306,
    documentNo: "SI-3B-0006",
    documentDate: "2026-06-22",
    partyName: "Rajasthan Agri Traders",
    gstin: "08AABCR5555E1Z5",
    placeOfSupply: "Rajasthan",
    state: "Rajasthan",
    branch: "Mumbai Branch",
    companyGstin: "27AABCD1234E2Z6",
    ...amt(95_000, 18, true),
    taxability: "taxable",
    supplyKind: "interstate",
    isInterstate: true,
    sign: 1,
    isDemo: true,
  },
  // Export
  {
    id: "demo-si-export-1",
    docType: "sales_invoice",
    sourceId: 9307,
    documentNo: "SI-3B-0007",
    documentDate: "2026-06-15",
    partyName: "Agro Export LLC — Dubai",
    gstin: "URP",
    placeOfSupply: "Other Country",
    state: "Other Country",
    branch: HO,
    companyGstin: GSTIN,
    taxableValue: 400_000,
    cgst: 0,
    sgst: 0,
    igst: 0,
    taxAmount: 0,
    taxability: "taxable",
    supplyKind: "export",
    isInterstate: true,
    sign: 1,
    isDemo: true,
  },
  // SEZ
  {
    id: "demo-si-sez-1",
    docType: "sales_invoice",
    sourceId: 9308,
    documentNo: "SI-3B-0008",
    documentDate: "2026-06-20",
    partyName: "SEZ Agro Processing Unit",
    gstin: "27AABCZ6666F1Z6",
    placeOfSupply: "Maharashtra (SEZ)",
    state: "Maharashtra",
    branch: HO,
    companyGstin: GSTIN,
    taxableValue: 150_000,
    cgst: 0,
    sgst: 0,
    igst: 27_000,
    taxAmount: 27_000,
    taxability: "taxable",
    supplyKind: "sez",
    isInterstate: true,
    sign: 1,
    isDemo: true,
  },
  // Nil / Exempt / Non-GST
  {
    id: "demo-si-nil-1",
    docType: "sales_invoice",
    sourceId: 9309,
    documentNo: "SI-3B-0009",
    documentDate: "2026-06-07",
    partyName: "Cooperative Society — Nil Rated",
    gstin: "27AABCN7777G1Z7",
    placeOfSupply: "Maharashtra",
    state: "Maharashtra",
    branch: HO,
    companyGstin: GSTIN,
    taxableValue: 60_000,
    cgst: 0,
    sgst: 0,
    igst: 0,
    taxAmount: 0,
    taxability: "nil_rated",
    supplyKind: "domestic_b2b",
    isInterstate: false,
    sign: 1,
    isDemo: true,
  },
  {
    id: "demo-si-exempt-1",
    docType: "sales_invoice",
    sourceId: 9310,
    documentNo: "SI-3B-0010",
    documentDate: "2026-06-09",
    partyName: "Farmer Producer Org — Exempt",
    gstin: "",
    placeOfSupply: "Maharashtra",
    state: "Maharashtra",
    branch: HO,
    companyGstin: GSTIN,
    taxableValue: 35_000,
    cgst: 0,
    sgst: 0,
    igst: 0,
    taxAmount: 0,
    taxability: "exempt",
    supplyKind: "domestic_b2c",
    isInterstate: false,
    sign: 1,
    isDemo: true,
  },
  {
    id: "demo-si-nongst-1",
    docType: "sales_invoice",
    sourceId: 9311,
    documentNo: "SI-3B-0011",
    documentDate: "2026-06-11",
    partyName: "Non-GST Packing Service",
    gstin: "",
    placeOfSupply: "Maharashtra",
    state: "Maharashtra",
    branch: HO,
    companyGstin: GSTIN,
    taxableValue: 22_000,
    cgst: 0,
    sgst: 0,
    igst: 0,
    taxAmount: 0,
    taxability: "non_gst",
    supplyKind: "domestic_b2c",
    isInterstate: false,
    sign: 1,
    isDemo: true,
  },
  // Credit note — reduces outward
  {
    id: "demo-cn-1",
    docType: "credit_note",
    sourceId: 9401,
    documentNo: "CN-3B-0001",
    documentDate: "2026-06-25",
    partyName: "Green Valley Agro Ltd",
    gstin: "27AABCG1111A1Z1",
    placeOfSupply: "Maharashtra",
    state: "Maharashtra",
    branch: HO,
    companyGstin: GSTIN,
    taxableValue: -25_000,
    cgst: -2_250,
    sgst: -2_250,
    igst: 0,
    taxAmount: -4_500,
    taxability: "taxable",
    supplyKind: "domestic_b2b",
    isInterstate: false,
    sign: -1,
    isDemo: true,
  },
  // Local purchase
  {
    id: "demo-pi-local-1",
    docType: "purchase_invoice",
    sourceId: 9501,
    documentNo: "PI-3B-0001",
    documentDate: "2026-06-04",
    partyName: "Maharashtra Fertilizer Traders",
    gstin: "27AABCM8888H1Z8",
    placeOfSupply: "Maharashtra",
    state: "Maharashtra",
    branch: HO,
    companyGstin: GSTIN,
    ...amt(200_000, 18, false),
    taxability: "taxable",
    supplyKind: "purchase_local",
    isInterstate: false,
    sign: 1,
    isDemo: true,
  },
  {
    id: "demo-pi-local-2",
    docType: "purchase_invoice",
    sourceId: 9502,
    documentNo: "PI-3B-0002",
    documentDate: "2026-06-14",
    partyName: "Pune Packaging Co",
    gstin: "27AABCP9999I1Z9",
    placeOfSupply: "Maharashtra",
    state: "Maharashtra",
    branch: HO,
    companyGstin: GSTIN,
    ...amt(80_000, 12, false),
    taxability: "taxable",
    supplyKind: "purchase_local",
    isInterstate: false,
    sign: 1,
    isDemo: true,
  },
  // Interstate purchase
  {
    id: "demo-pi-inter-1",
    docType: "purchase_invoice",
    sourceId: 9503,
    documentNo: "PI-3B-0003",
    documentDate: "2026-06-16",
    partyName: "Delhi Agri Inputs Pvt Ltd",
    gstin: "07AABCD1010J1Z0",
    placeOfSupply: "Delhi",
    state: "Delhi",
    branch: HO,
    companyGstin: GSTIN,
    ...amt(175_000, 18, true),
    taxability: "taxable",
    supplyKind: "purchase_interstate",
    isInterstate: true,
    sign: 1,
    isDemo: true,
  },
  {
    id: "demo-pi-inter-2",
    docType: "purchase_invoice",
    sourceId: 9504,
    documentNo: "PI-3B-0004",
    documentDate: "2026-06-21",
    partyName: "Tamil Nadu Seeds Corp",
    gstin: "33AABCT2020K1Z1",
    placeOfSupply: "Tamil Nadu",
    state: "Tamil Nadu",
    branch: HO,
    companyGstin: GSTIN,
    ...amt(110_000, 12, true),
    taxability: "taxable",
    supplyKind: "purchase_interstate",
    isInterstate: true,
    sign: 1,
    isDemo: true,
  },
  // Debit note — increases input GST (purchase adjustment)
  {
    id: "demo-dn-1",
    docType: "debit_note",
    sourceId: 9601,
    documentNo: "DN-3B-0001",
    documentDate: "2026-06-26",
    partyName: "Maharashtra Fertilizer Traders",
    gstin: "27AABCM8888H1Z8",
    placeOfSupply: "Maharashtra",
    state: "Maharashtra",
    branch: HO,
    companyGstin: GSTIN,
    taxableValue: 15_000,
    cgst: 1_350,
    sgst: 1_350,
    igst: 0,
    taxAmount: 2_700,
    taxability: "taxable",
    supplyKind: "purchase_local",
    isInterstate: false,
    sign: 1,
    isDemo: true,
  },
];
