import { GrnPendingStockRecord } from "../types";

export const SEED_GRN_PENDING_STOCK: GrnPendingStockRecord[] = [
  {
    id: "gp-1",
    grnNo: "GRN-2026-044",
    product: "Urea 50kg",
    warehouse: "Central Warehouse",
    batchNumber: "B-UR-88W",
    receivedQuantity: 1000,
    grnDate: "2026-06-01",
    vendor: "Chambal Fertilizers Ltd",
    status: "Pending QC",
    assignedInspector: "Anil K.",
    inspectionDueDate: "2026-06-04",
  },
  {
    id: "gp-2",
    grnNo: "GRN-2026-042",
    product: "NPK 10:26:26",
    warehouse: "Central Warehouse",
    batchNumber: "B-NPK-77X",
    receivedQuantity: 500,
    grnDate: "2026-05-31",
    vendor: "Rashtriya Chemicals & Fert",
    status: "QC In Progress",
    assignedInspector: "Anil K.",
    inspectionDueDate: "2026-06-03",
  },
  {
    id: "gp-3",
    grnNo: "GRN-2026-045",
    product: "Hybrid Maize Seed",
    warehouse: "North Zone Hub",
    batchNumber: "B-MZ-22Y",
    receivedQuantity: 300,
    grnDate: "2026-06-02",
    vendor: "Pioneer Seeds Ltd",
    status: "Awaiting Inspection",
    assignedInspector: "Sanjay D.",
    inspectionDueDate: "2026-06-05",
  },
  {
    id: "gp-4",
    grnNo: "GRN-2026-040",
    product: "DAP 50kg",
    warehouse: "South Zone Depot",
    batchNumber: "B-DAP-11Z",
    receivedQuantity: 800,
    grnDate: "2026-05-29",
    vendor: "IFFCO Cooperative",
    status: "QC In Progress",
    assignedInspector: "Rita M.",
    inspectionDueDate: "2026-06-01",
  },
  {
    id: "gp-5",
    grnNo: "GRN-2026-043",
    product: "Zinc Sulphate 21%",
    warehouse: "West Zone Hub",
    batchNumber: "B-ZN-99M",
    receivedQuantity: 400,
    grnDate: "2026-06-01",
    vendor: "Aries Agro Industries",
    status: "Pending QC",
    assignedInspector: "Sanjay D.",
    inspectionDueDate: "2026-06-04",
  },
];
