import { QcPassedStockRecord } from "../types";

export const SEED_QC_PASSED_STOCK: QcPassedStockRecord[] = [
  {
    id: "st-1",
    product: "Urea 50kg",
    warehouse: "Central Warehouse",
    batchNumber: "B-UR-99A",
    availableQuantity: 500,
    reservedQuantity: 0,
    manufacturingDate: "2025-11-01",
    expiryDate: "2027-11-01",
    status: "Available",
    threshold: 100,
  },
  {
    id: "st-2",
    product: "NPK 10:26:26",
    warehouse: "Central Warehouse",
    batchNumber: "B-NPK-12B",
    availableQuantity: 300,
    reservedQuantity: 50,
    manufacturingDate: "2025-12-05",
    expiryDate: "2027-12-05",
    status: "Reserved",
    threshold: 100,
  },
  {
    id: "st-3",
    product: "Hybrid Maize Seed",
    warehouse: "North Zone Hub",
    batchNumber: "B-MZ-01X",
    availableQuantity: 200,
    reservedQuantity: 0,
    manufacturingDate: "2025-10-10",
    expiryDate: "2026-10-10",
    status: "Available",
    threshold: 100,
  },
  {
    id: "st-4",
    product: "DAP 50kg",
    warehouse: "Central Warehouse",
    batchNumber: "B-DAP-33C",
    availableQuantity: 45,
    reservedQuantity: 0,
    manufacturingDate: "2025-12-01",
    expiryDate: "2027-12-01",
    status: "Low Stock",
    threshold: 100,
  },
  {
    id: "st-5",
    product: "Zinc Sulphate 21%",
    warehouse: "Central Warehouse",
    batchNumber: "B-ZN-77Y",
    availableQuantity: 140,
    reservedQuantity: 40,
    manufacturingDate: "2025-11-15",
    expiryDate: "2027-11-15",
    status: "Reserved",
    threshold: 50,
  },
  {
    id: "st-6",
    product: "Urea 50kg",
    warehouse: "North Zone Hub",
    batchNumber: "B-UR-44X",
    availableQuantity: 80,
    reservedQuantity: 0,
    manufacturingDate: "2025-09-01",
    expiryDate: "2026-06-25",
    status: "Near Expiry",
    threshold: 100,
  },
  {
    id: "st-7",
    product: "Hybrid Maize Seed",
    warehouse: "South Zone Depot",
    batchNumber: "B-MZ-99F",
    availableQuantity: 0,
    reservedQuantity: 0,
    manufacturingDate: "2024-04-01",
    expiryDate: "2026-04-01",
    status: "Expired",
    threshold: 50,
  },
  {
    id: "st-8",
    product: "NPK 10:26:26",
    warehouse: "West Zone Hub",
    batchNumber: "B-NPK-88M",
    availableQuantity: 0,
    reservedQuantity: 0,
    manufacturingDate: "2025-01-10",
    expiryDate: "2027-01-10",
    status: "Out Of Stock",
    threshold: 100,
  },
  {
    id: "st-9",
    product: "DAP 50kg",
    warehouse: "South Zone Depot",
    batchNumber: "B-DAP-11K",
    availableQuantity: 600,
    reservedQuantity: 100,
    manufacturingDate: "2025-08-20",
    expiryDate: "2027-08-20",
    status: "Reserved",
    threshold: 100,
  },
  {
    id: "st-10",
    product: "Zinc Sulphate 21%",
    warehouse: "West Zone Hub",
    batchNumber: "B-ZN-22L",
    availableQuantity: 20,
    reservedQuantity: 0,
    manufacturingDate: "2025-10-01",
    expiryDate: "2027-10-01",
    status: "Low Stock",
    threshold: 50,
  },
  {
    id: "st-11",
    product: "Urea 50kg",
    warehouse: "South Zone Depot",
    batchNumber: "B-UR-22B",
    availableQuantity: 1000,
    reservedQuantity: 0,
    manufacturingDate: "2025-10-15",
    expiryDate: "2027-10-15",
    status: "Available",
    threshold: 100,
  },
  {
    id: "st-12",
    product: "NPK 10:26:26",
    warehouse: "North Zone Hub",
    batchNumber: "B-NPK-55P",
    availableQuantity: 12,
    reservedQuantity: 5,
    manufacturingDate: "2025-07-20",
    expiryDate: "2026-06-18",
    status: "Near Expiry",
    threshold: 100,
  },
  {
    id: "st-13",
    product: "Hybrid Maize Seed",
    warehouse: "West Zone Hub",
    batchNumber: "B-MZ-12T",
    availableQuantity: 400,
    reservedQuantity: 0,
    manufacturingDate: "2025-11-05",
    expiryDate: "2026-11-05",
    status: "Available",
    threshold: 100,
  },
  {
    id: "st-14",
    product: "DAP 50kg",
    warehouse: "West Zone Hub",
    batchNumber: "B-DAP-77S",
    availableQuantity: 0,
    reservedQuantity: 0,
    manufacturingDate: "2025-05-01",
    expiryDate: "2026-05-01",
    status: "Expired",
    threshold: 100,
  },
  {
    id: "st-15",
    product: "Zinc Sulphate 21%",
    warehouse: "North Zone Hub",
    batchNumber: "B-ZN-99Z",
    availableQuantity: 300,
    reservedQuantity: 0,
    manufacturingDate: "2025-11-30",
    expiryDate: "2027-11-30",
    status: "Available",
    threshold: 50,
  },
  {
    id: "st-16",
    product: "Urea 50kg",
    warehouse: "West Zone Hub",
    batchNumber: "B-UR-88D",
    availableQuantity: 350,
    reservedQuantity: 80,
    manufacturingDate: "2025-09-10",
    expiryDate: "2027-09-10",
    status: "Reserved",
    threshold: 100,
  },
  {
    id: "st-17",
    product: "NPK 10:26:26",
    warehouse: "South Zone Depot",
    batchNumber: "B-NPK-33V",
    availableQuantity: 25,
    reservedQuantity: 0,
    manufacturingDate: "2025-11-01",
    expiryDate: "2026-06-30",
    status: "Near Expiry",
    threshold: 100,
  },
  {
    id: "st-18",
    product: "Hybrid Maize Seed",
    warehouse: "Central Warehouse",
    batchNumber: "B-MZ-44Q",
    availableQuantity: 0,
    reservedQuantity: 0,
    manufacturingDate: "2025-02-14",
    expiryDate: "2027-02-14",
    status: "Out Of Stock",
    threshold: 100,
  },
  {
    id: "st-19",
    product: "DAP 50kg",
    warehouse: "North Zone Hub",
    batchNumber: "B-DAP-09G",
    availableQuantity: 700,
    reservedQuantity: 150,
    manufacturingDate: "2025-09-15",
    expiryDate: "2027-09-15",
    status: "Reserved",
    threshold: 100,
  },
  {
    id: "st-20",
    product: "Zinc Sulphate 21%",
    warehouse: "South Zone Depot",
    batchNumber: "B-ZN-05K",
    availableQuantity: 15,
    reservedQuantity: 0,
    manufacturingDate: "2025-10-10",
    expiryDate: "2027-10-10",
    status: "Low Stock",
    threshold: 50,
  },
  {
    id: "st-21",
    product: "Urea 50kg",
    warehouse: "Central Warehouse",
    batchNumber: "B-UR-10X",
    availableQuantity: 0,
    reservedQuantity: 0,
    manufacturingDate: "2024-05-15",
    expiryDate: "2026-05-15",
    status: "Expired",
    threshold: 100,
  },
  {
    id: "st-22",
    product: "NPK 10:26:26",
    warehouse: "West Zone Hub",
    batchNumber: "B-NPK-90P",
    availableQuantity: 400,
    reservedQuantity: 0,
    manufacturingDate: "2025-12-01",
    expiryDate: "2027-12-01",
    status: "Available",
    threshold: 100,
  },
  {
    id: "st-23",
    product: "Hybrid Maize Seed",
    warehouse: "Central Warehouse",
    batchNumber: "B-MZ-88E",
    availableQuantity: 120,
    reservedQuantity: 30,
    manufacturingDate: "2025-10-10",
    expiryDate: "2027-10-10",
    status: "Reserved",
    threshold: 50,
  },
  {
    id: "st-24",
    product: "DAP 50kg",
    warehouse: "North Zone Hub",
    batchNumber: "B-DAP-60W",
    availableQuantity: 90,
    reservedQuantity: 10,
    manufacturingDate: "2025-08-01",
    expiryDate: "2027-08-01",
    status: "Low Stock",
    threshold: 100,
  },
  {
    id: "st-25",
    product: "Zinc Sulphate 21%",
    warehouse: "Central Warehouse",
    batchNumber: "B-ZN-44H",
    availableQuantity: 8,
    reservedQuantity: 0,
    manufacturingDate: "2025-12-05",
    expiryDate: "2026-06-15",
    status: "Near Expiry",
    threshold: 50,
  },
  {
    id: "st-26",
    product: "Bio Fertilizer A",
    warehouse: "Central Warehouse",
    batchNumber: "B001",
    availableQuantity: 50,
    reservedQuantity: 0,
    manufacturingDate: "2026-01-15",
    expiryDate: "2026-07-21",
    status: "Near Expiry",
    threshold: 20,
  },
  {
    id: "st-27",
    product: "Bio Fertilizer A",
    warehouse: "Central Warehouse",
    batchNumber: "B002",
    availableQuantity: 100,
    reservedQuantity: 0,
    manufacturingDate: "2025-12-01",
    expiryDate: "2026-12-23",
    status: "Available",
    threshold: 20,
  },
  {
    id: "st-28",
    product: "Urea 50kg",
    warehouse: "Central Warehouse",
    batchNumber: "B-UR-55C",
    availableQuantity: 220,
    reservedQuantity: 0,
    manufacturingDate: "2026-01-10",
    expiryDate: "2026-07-28",
    status: "Near Expiry",
    threshold: 100,
  },
];
