import { RejectedStockRecord } from "../types";

export const SEED_REJECTED_STOCK: RejectedStockRecord[] = [
  {
    id: "rj-1",
    product: "Urea 50kg",
    warehouse: "Central Warehouse",
    batchNumber: "B-UR-77R",
    rejectedQuantity: 80,
    rejectionReason: "Moisture Content Out of Range",
    qcNumber: "QC-2026-005",
    inspectionDate: "2026-05-15",
    inspector: "Anil K.",
    remarks: "Packaging was slightly damaged; bags absorbed water and content crystallized.",
    status: "Rejected",
  },
  {
    id: "rj-2",
    product: "NPK 10:26:26",
    warehouse: "Central Warehouse",
    batchNumber: "B-NPK-66N",
    rejectedQuantity: 120,
    rejectionReason: "Active Ingredient Concentration Under Limit",
    qcNumber: "QC-2026-008",
    inspectionDate: "2026-05-18",
    inspector: "Anil K.",
    remarks: "Undergoing secondary testing from vendor samples.",
    status: "Under Review",
  },
  {
    id: "rj-3",
    product: "Hybrid Maize Seed",
    warehouse: "North Zone Hub",
    batchNumber: "B-MZ-33K",
    rejectedQuantity: 50,
    rejectionReason: "Germination Rate Below Standard",
    qcNumber: "QC-2026-002",
    inspectionDate: "2026-05-02",
    inspector: "Sanjay D.",
    remarks: "Disposed locally at North Zone Hub with authorized witness present.",
    status: "Disposed",
  },
  {
    id: "rj-4",
    product: "DAP 50kg",
    warehouse: "South Zone Depot",
    batchNumber: "B-DAP-55V",
    rejectedQuantity: 200,
    rejectionReason: "Contamination Detected",
    qcNumber: "QC-2026-012",
    inspectionDate: "2026-05-28",
    inspector: "Rita M.",
    remarks: "Returned to Vendor (M/s GreenFert Corp) under challan RV-2605.",
    status: "Returned To Vendor",
  },
  {
    id: "rj-5",
    product: "Zinc Sulphate 21%",
    warehouse: "West Zone Hub",
    batchNumber: "B-ZN-44W",
    rejectedQuantity: 30,
    rejectionReason: "Incorrent Granulometry / Dust Content High",
    qcNumber: "QC-2026-015",
    inspectionDate: "2026-06-01",
    inspector: "Sanjay D.",
    remarks: "Evaluating option to filter and repackage.",
    status: "Under Review",
  },
];
