import { SalesReturnStockRecord } from "../types";

export const SEED_SALES_RETURN_STOCK: SalesReturnStockRecord[] = [
  {
    id: "sr-st-1",
    product: "Urea 50kg",
    warehouse: "Central Warehouse",
    batchNumber: "B-UR-99A",
    availableQuantity: 25,
    salesReturnNo: "SRET-2026-001",
    customer: "ABC Traders",
    returnDate: "2026-05-10",
    expiryDate: "2027-11-01",
    status: "Available",
  },
  {
    id: "sr-st-2",
    product: "NPK 10:26:26",
    warehouse: "Central Warehouse",
    batchNumber: "B-NPK-12B",
    availableQuantity: 12,
    salesReturnNo: "SRET-2026-002",
    customer: "Green Valley Agro",
    returnDate: "2026-05-14",
    expiryDate: "2027-12-05",
    status: "QC Pending",
  },
  {
    id: "sr-st-3",
    product: "Hybrid Maize Seed",
    warehouse: "North Zone Hub",
    batchNumber: "B-MZ-01X",
    availableQuantity: 10,
    salesReturnNo: "SRET-2026-003",
    customer: "Kisan Fertilizers",
    returnDate: "2026-05-18",
    expiryDate: "2026-10-10",
    status: "Near Expiry",
  },
  {
    id: "sr-st-4",
    product: "DAP 50kg",
    warehouse: "South Zone Depot",
    batchNumber: "B-DAP-44D",
    availableQuantity: 8,
    salesReturnNo: "SRET-2026-004",
    customer: "Punjab Agro Distributors",
    returnDate: "2026-05-22",
    expiryDate: "2027-06-15",
    status: "Available",
  },
  {
    id: "sr-st-5",
    product: "Zinc Sulphate 21%",
    warehouse: "West Zone Hub",
    batchNumber: "B-ZS-88W",
    availableQuantity: 5,
    salesReturnNo: "SRET-2026-005",
    customer: "Maharashtra Crop Care",
    returnDate: "2026-06-01",
    expiryDate: "2026-04-30",
    status: "Expired",
  },
];
