import { SampleReturnStockRecord } from "../types";

export const SEED_SAMPLE_RETURN_STOCK: SampleReturnStockRecord[] = [
  {
    id: "smp-st-1",
    product: "Hybrid Maize Seed",
    warehouse: "Central Warehouse",
    batchNumber: "B-MZ-01X",
    availableQuantity: 4,
    sampleReturnNo: "SR-2024-001",
    customer: "Green Valley Agro",
    returnDate: "2024-01-22",
    expiryDate: "2026-10-10",
    status: "Available",
  },
  {
    id: "smp-st-2",
    product: "Urea 50kg",
    warehouse: "Central Warehouse",
    batchNumber: "B-UR-99A",
    availableQuantity: 6,
    sampleReturnNo: "SR-2024-002",
    customer: "Demo Farmer Co-op",
    returnDate: "2024-02-05",
    expiryDate: "2027-11-01",
    status: "QC Pending",
  },
  {
    id: "smp-st-3",
    product: "NPK 10:26:26",
    warehouse: "North Zone Hub",
    batchNumber: "B-NPK-12B",
    availableQuantity: 3,
    sampleReturnNo: "SR-2024-003",
    customer: "Field Demo Unit — North",
    returnDate: "2024-02-12",
    expiryDate: "2027-12-05",
    status: "Available",
  },
  {
    id: "smp-st-4",
    product: "DAP 50kg",
    warehouse: "South Zone Depot",
    batchNumber: "B-DAP-44D",
    availableQuantity: 2,
    sampleReturnNo: "SR-2024-004",
    customer: "Agri Innovation Lab",
    returnDate: "2024-02-18",
    expiryDate: "2026-03-15",
    status: "Near Expiry",
  },
];
