/**
 * Step 4 match demo — pending statement rows aligned with banking demo vouchers.
 */

import type { BankReconActivityEvent } from "@/app/(app)/accounts/bank-reconciliation/bank-reconciliation-v2-data";
import type { BankReconTransactionRecord } from "@/lib/accounts/bank-recon-register";
import { enrichRecordWithManualDefaults } from "@/lib/accounts/bank-recon-manual-demo-seed";

function act(
  id: string,
  label: string,
  detail: string,
  actor: string,
  timestamp: string,
  tone: BankReconActivityEvent["tone"] = "blue",
): BankReconActivityEvent {
  return { id, label, detail, actor, timestamp, tone };
}

/** Statement rows for auto-match testing — appended on v2-step4 migration */
export const MATCH_DEMO_TRANSACTIONS: BankReconTransactionRecord[] = [
  enrichRecordWithManualDefaults({
    id: "match-demo-001",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-01",
    valueDate: "2026-07-01",
    bookDate: null,
    reference: "NEFT-001",
    utrNumber: "NEFT-001",
    chequeNo: null,
    narration: "NEFT CR — ABC Agro Distributor — Sales collection",
    partyLedger: "ABC Agro Distributor",
    deposit: 185000,
    withdrawal: 0,
    source: "Statement Upload",
    matchStatus: "Pending",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "NEFT",
    importedFileName: "hdfc-match-demo.csv",
    importBatchId: "batch-match-demo",
    activity: [act("m1", "Statement Imported", "Exact UTR match candidate RV-0001", "System", "01 Jul 2026")],
  }),
  enrichRecordWithManualDefaults({
    id: "match-demo-002",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-02",
    valueDate: "2026-07-02",
    bookDate: null,
    reference: "PAY-001",
    utrNumber: null,
    chequeNo: null,
    narration: "RTGS DR — AgroChem Traders — Supplier payment",
    partyLedger: "AgroChem Traders",
    deposit: 0,
    withdrawal: 245000,
    source: "Statement Upload",
    matchStatus: "Pending",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "RTGS",
    importedFileName: "hdfc-match-demo.csv",
    importBatchId: "batch-match-demo",
    activity: [act("m2", "Statement Imported", "Exact reference match candidate PV-0001", "System", "02 Jul 2026")],
  }),
  enrichRecordWithManualDefaults({
    id: "match-demo-003",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-10",
    valueDate: "2026-07-10",
    bookDate: null,
    reference: "458921",
    utrNumber: null,
    chequeNo: "458921",
    narration: "CHQ DEP — Punjab Agro Distributors",
    partyLedger: "Punjab Agro Distributors",
    deposit: 200000,
    withdrawal: 0,
    source: "Statement Upload",
    matchStatus: "Pending",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "Cheque",
    importedFileName: "hdfc-match-demo.csv",
    importBatchId: "batch-match-demo",
    activity: [act("m3", "Statement Imported", "Cheque match with 2-day book date diff", "System", "10 Jul 2026")],
  }),
  enrichRecordWithManualDefaults({
    id: "match-demo-004",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-03",
    valueDate: "2026-07-03",
    bookDate: null,
    reference: "UTR001",
    utrNumber: "UTR001",
    chequeNo: null,
    narration: "NEFT CR — Customer A",
    partyLedger: "—",
    deposit: 25000,
    withdrawal: 0,
    source: "Statement Upload",
    matchStatus: "Pending",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "NEFT",
    importedFileName: "hdfc-match-demo.csv",
    importBatchId: "batch-match-demo",
    activity: [act("m4", "Statement Imported", "Same amount different ref scenario A", "System", "03 Jul 2026")],
  }),
  enrichRecordWithManualDefaults({
    id: "match-demo-005",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-03",
    valueDate: "2026-07-03",
    bookDate: null,
    reference: "UTR002",
    utrNumber: "UTR002",
    chequeNo: null,
    narration: "NEFT CR — Customer B",
    partyLedger: "—",
    deposit: 25000,
    withdrawal: 0,
    source: "Statement Upload",
    matchStatus: "Pending",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "NEFT",
    importedFileName: "hdfc-match-demo.csv",
    importBatchId: "batch-match-demo",
    activity: [act("m5", "Statement Imported", "Same amount different ref scenario B", "System", "03 Jul 2026")],
  }),
  enrichRecordWithManualDefaults({
    id: "match-demo-006",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-04",
    valueDate: "2026-07-04",
    bookDate: null,
    reference: "",
    utrNumber: null,
    chequeNo: null,
    narration: "NEFT CR — Krishna Retail Store collection",
    partyLedger: "Krishna Retail Store",
    deposit: 92000,
    withdrawal: 0,
    source: "Statement Upload",
    matchStatus: "Pending",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "NEFT",
    importedFileName: "hdfc-match-demo.csv",
    importBatchId: "batch-match-demo",
    activity: [act("m6", "Statement Imported", "Missing ref, party+amount suggested match", "System", "04 Jul 2026")],
  }),
  enrichRecordWithManualDefaults({
    id: "match-demo-007",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-05",
    valueDate: "2026-07-05",
    bookDate: null,
    reference: "BCHG-MAY",
    utrNumber: null,
    chequeNo: null,
    narration: "Bank service charges — May",
    partyLedger: "Bank Charges",
    deposit: 0,
    withdrawal: 2500,
    source: "Statement Upload",
    matchStatus: "Pending",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "Other",
    importedFileName: "hdfc-match-demo.csv",
    importBatchId: "batch-match-demo",
    activity: [act("m7", "Statement Imported", "Journal bank line match JV-0001", "System", "05 Jul 2026")],
  }),
  enrichRecordWithManualDefaults({
    id: "match-demo-008",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-06",
    valueDate: "2026-07-06",
    bookDate: null,
    reference: "INT-MAY",
    utrNumber: null,
    chequeNo: null,
    narration: "Interest credit — HDFC current account",
    partyLedger: "Bank Interest Income",
    deposit: 8500,
    withdrawal: 0,
    source: "Statement Upload",
    matchStatus: "Pending",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "Other",
    importedFileName: "hdfc-match-demo.csv",
    importBatchId: "batch-match-demo",
    activity: [act("m8", "Statement Imported", "Interest income JV match", "System", "06 Jul 2026")],
  }),
  enrichRecordWithManualDefaults({
    id: "match-demo-009",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-07",
    valueDate: "2026-07-07",
    bookDate: null,
    reference: "FT-0001",
    utrNumber: null,
    chequeNo: null,
    narration: "Fund transfer HDFC → ICICI",
    partyLedger: "ICICI Bank",
    deposit: 0,
    withdrawal: 200000,
    source: "Statement Upload",
    matchStatus: "Pending",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "Bank Transfer",
    importedFileName: "hdfc-match-demo.csv",
    importBatchId: "batch-match-demo",
    activity: [act("m9", "Statement Imported", "Contra bank leg match", "System", "07 Jul 2026")],
  }),
  enrichRecordWithManualDefaults({
    id: "match-demo-010",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-08",
    valueDate: "2026-07-08",
    bookDate: null,
    reference: "COMBINED-200K",
    utrNumber: null,
    chequeNo: null,
    narration: "Bulk customer receipts — combined deposit",
    partyLedger: "—",
    deposit: 200000,
    withdrawal: 0,
    source: "Statement Upload",
    matchStatus: "Pending",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "NEFT",
    importedFileName: "hdfc-match-demo.csv",
    importBatchId: "batch-match-demo",
    activity: [act("m10", "Statement Imported", "Potential combined match indicator", "System", "08 Jul 2026")],
  }),
];
