/**
 * Step 7 completion demo seed — reconciliation sessions and history.
 */

import type { BankReconSessionRecord } from "@/lib/accounts/bank-recon-completion-types";
import {
  loadBankReconSessions,
  updateCompletionAccountMeta,
  upsertBankReconSession,
} from "@/lib/accounts/bank-recon-completion-store";

const DEMO_VERSION_KEY = "dharitri_bank_recon_completion_demo_v2";
const DEMO_VERSION = "v1";

const DEMO_SESSIONS: BankReconSessionRecord[] = [
  {
    id: "brs-demo-completed-hdfc",
    reconciliationNumber: "BRC-HDFC-202526-00001",
    bankAccountId: "hdfc-current",
    periodFrom: "2026-06-01",
    periodTo: "2026-06-28",
    status: "Completed",
    version: 1,
    previousVersionId: null,
    financialYear: "2025-26",
    statementOpeningBalance: 2650000,
    statementClosingBalance: 2839120.45,
    bookOpeningBalance: 2650000,
    bookClosingBalance: 2839120.45,
    adjustedBookBalance: 2839120.45,
    finalDifference: 0,
    differenceOverrideReason: null,
    differenceApprovedBy: null,
    differenceApprovedOn: null,
    incompletePeriodReason: null,
    preparedBy: "Priya Sharma",
    preparedOn: "2026-06-29T10:00:00.000Z",
    reviewedBy: "Rajesh Kumar",
    approvedBy: "Rajesh Kumar",
    completedBy: "Priya Sharma",
    completedOn: "2026-06-29T11:30:00.000Z",
    reopenedBy: null,
    reopenedOn: null,
    reopenReason: null,
    cancelledBy: null,
    cancelledOn: null,
    cancelReason: null,
    importBatchId: "batch-match-demo",
    statementFileName: "hdfc-jun-2026-partial.csv",
    locked: true,
    snapshotId: "brss-demo-completed-hdfc",
    carryForward: [],
    changeSummary: null,
    differenceBefore: null,
    differenceAfter: null,
  },
  {
    id: "brs-demo-diff-sbi",
    reconciliationNumber: "BRC-SBI-202526-00001",
    bankAccountId: "sbi-cash-credit",
    periodFrom: "2026-05-01",
    periodTo: "2026-05-31",
    status: "Completed with Difference",
    version: 1,
    previousVersionId: null,
    financialYear: "2025-26",
    statementOpeningBalance: 1200000,
    statementClosingBalance: 1241850,
    bookOpeningBalance: 1200000,
    bookClosingBalance: 1250000,
    adjustedBookBalance: 1250000,
    finalDifference: 8150,
    differenceOverrideReason: "Timing difference on bank charges not yet categorized",
    differenceApprovedBy: "Rajesh Kumar",
    differenceApprovedOn: "2026-06-02T09:00:00.000Z",
    incompletePeriodReason: null,
    preparedBy: "Priya Sharma",
    preparedOn: "2026-06-01T14:00:00.000Z",
    reviewedBy: null,
    approvedBy: "Rajesh Kumar",
    completedBy: "Priya Sharma",
    completedOn: "2026-06-02T09:15:00.000Z",
    reopenedBy: null,
    reopenedOn: null,
    reopenReason: null,
    cancelledBy: null,
    cancelledOn: null,
    cancelReason: null,
    importBatchId: null,
    statementFileName: null,
    locked: true,
    snapshotId: "brss-demo-diff-sbi",
    carryForward: [],
    changeSummary: null,
    differenceBefore: null,
    differenceAfter: null,
  },
  {
    id: "brs-demo-draft-icici",
    reconciliationNumber: null,
    bankAccountId: "icici-collection",
    periodFrom: "2026-07-01",
    periodTo: "2026-07-31",
    status: "Draft",
    version: 1,
    previousVersionId: null,
    financialYear: "2025-26",
    statementOpeningBalance: 956780,
    statementClosingBalance: 956780,
    bookOpeningBalance: 956780,
    bookClosingBalance: 956780,
    adjustedBookBalance: 956780,
    finalDifference: 0,
    differenceOverrideReason: null,
    differenceApprovedBy: null,
    differenceApprovedOn: null,
    incompletePeriodReason: null,
    preparedBy: "Admin",
    preparedOn: new Date().toISOString(),
    reviewedBy: null,
    approvedBy: null,
    completedBy: null,
    completedOn: null,
    reopenedBy: null,
    reopenedOn: null,
    reopenReason: null,
    cancelledBy: null,
    cancelledOn: null,
    cancelReason: null,
    importBatchId: null,
    statementFileName: "icici-jun-2026.xlsx",
    locked: false,
    snapshotId: null,
    carryForward: [],
    changeSummary: null,
    differenceBefore: null,
    differenceAfter: null,
  },
  {
    id: "brs-demo-reopened-hdfc",
    reconciliationNumber: "BRC-HDFC-202526-00002",
    bankAccountId: "hdfc-current",
    periodFrom: "2026-06-29",
    periodTo: "2026-06-30",
    status: "Reopened",
    version: 1,
    previousVersionId: "brss-demo-completed-hdfc-v1",
    financialYear: "2025-26",
    statementOpeningBalance: 2839120.45,
    statementClosingBalance: 2847650.45,
    bookOpeningBalance: 2839120.45,
    bookClosingBalance: 2847650.45,
    adjustedBookBalance: 2847650.45,
    finalDifference: 0,
    differenceOverrideReason: null,
    differenceApprovedBy: null,
    differenceApprovedOn: null,
    incompletePeriodReason: null,
    preparedBy: "Priya Sharma",
    preparedOn: "2026-07-01T10:00:00.000Z",
    reviewedBy: null,
    approvedBy: null,
    completedBy: "Priya Sharma",
    completedOn: "2026-07-01T11:00:00.000Z",
    reopenedBy: "Rajesh Kumar",
    reopenedOn: "2026-07-05T14:00:00.000Z",
    reopenReason: "Cheque clearing date correction required",
    cancelledBy: null,
    cancelledOn: null,
    cancelReason: null,
    importBatchId: "batch-match-demo",
    statementFileName: "hdfc-jun-2026-partial.csv",
    locked: false,
    snapshotId: "brss-demo-reopened-hdfc",
    carryForward: [],
    changeSummary: null,
    differenceBefore: 0,
    differenceAfter: null,
  },
];

export function ensureBankReconCompletionSeeded(): void {
  if (typeof window === "undefined") return;
  if (localStorage.getItem(DEMO_VERSION_KEY) === DEMO_VERSION) return;

  const existing = loadBankReconSessions();
  const existingIds = new Set(existing.map((s) => s.id));
  for (const session of DEMO_SESSIONS) {
    if (!existingIds.has(session.id)) upsertBankReconSession(session);
  }

  updateCompletionAccountMeta({
    bankAccountId: "hdfc-current",
    lastReconciledDate: "2026-06-28",
    lastCompletedSessionId: "brs-demo-completed-hdfc",
    nextPeriodFrom: "2026-06-29",
    listingStatus: "Reopened",
  });
  updateCompletionAccountMeta({
    bankAccountId: "icici-collection",
    lastReconciledDate: "2026-06-30",
    lastCompletedSessionId: null,
    nextPeriodFrom: "2026-07-01",
    listingStatus: "Reconciled",
  });
  updateCompletionAccountMeta({
    bankAccountId: "sbi-cash-credit",
    lastReconciledDate: "2026-05-31",
    lastCompletedSessionId: "brs-demo-diff-sbi",
    nextPeriodFrom: "2026-06-01",
    listingStatus: "Completed with Difference",
  });

  localStorage.setItem(DEMO_VERSION_KEY, DEMO_VERSION);
}
