/**
 * Bank reconciliation completion exports — Step 7.
 */

import type { BankReconReviewSnapshot, BankReconSessionRecord } from "@/lib/accounts/bank-recon-completion-types";
import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import { formatMoney } from "@/lib/accounts/money-format";
import {
  ACCOUNTS_COMPANY_NAME,
  buildReportDocumentHtml,
  buildStandardReportTableHtml,
  escapeHtml,
  generatedOnLabel,
  openReportPrintWindow,
  type ReportColumnHeader,
  type ReportHeaderOptions,
} from "@/lib/accounts/report-export-presentation";

export async function exportReconciliationReportToExcel(
  session: BankReconSessionRecord,
  review: BankReconReviewSnapshot,
): Promise<void> {
  const XLSX = await import("xlsx");

  const summary = [
    ["Company", ACCOUNTS_COMPANY_NAME],
    ["Bank", review.bankName],
    ["Account", review.accountNickname],
    ["Account Number", review.maskedAccountNumber],
    ["Reconciliation Number", session.reconciliationNumber ?? "Draft"],
    ["Period", `${review.periodFrom} to ${review.periodTo}`],
    ["Status", session.status],
    ["Book Closing Balance", review.bookClosingBalance],
    ["Adjusted Book Balance", review.formula.adjustedBookBalance],
    ["Statement Closing Balance", review.statementClosingBalance],
    ["Final Difference", review.formula.finalDifference],
    ["Generated By", ACCOUNTS_CURRENT_USER],
    ["Generated On", generatedOnLabel()],
  ];

  const outstanding = review.outstandingBook.map((o) => ({
    "Book Date": o.bookDate,
    "Voucher No.": o.voucherNo,
    Party: o.partyLedger,
    Reference: o.reference,
    Deposit: o.deposit || "",
    Withdrawal: o.withdrawal || "",
    "Expected Clearing": o.expectedClearingDate ?? "",
    Ageing: o.ageingDays,
    Reason: o.reason,
  }));

  const stmtOnly = review.statementOnly.map((s) => ({
    "Statement Date": s.statementDate,
    "Value Date": s.valueDate,
    Reference: s.reference,
    Narration: s.narration,
    Deposit: s.deposit || "",
    Withdrawal: s.withdrawal || "",
    Category: s.category,
    Status: s.status,
  }));

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(summary), "Summary");
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(outstanding), "Outstanding Book");
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(stmtOnly), "Statement Only");
  const suffix = session.reconciliationNumber ?? session.id;
  XLSX.writeFile(wb, `Bank_Reconciliation_${suffix}.xlsx`);
}

export function exportReconciliationReportToPdf(
  session: BankReconSessionRecord,
  review: BankReconReviewSnapshot,
): void {
  const header: ReportHeaderOptions = {
    reportTitle: "Bank Reconciliation Report",
    reportPeriod: `${review.periodFrom} to ${review.periodTo}`,
    filters: [
      { label: "Bank", value: `${review.bankName} — ${review.accountNickname}` },
      { label: "Account", value: review.maskedAccountNumber },
      { label: "Reconciliation No.", value: session.reconciliationNumber ?? "Draft" },
      { label: "Status", value: session.status },
      {
        label: "Completed On",
        value: session.completedOn
          ? new Date(session.completedOn).toLocaleString("en-IN")
          : "—",
      },
    ],
  };

  const balanceSummaryHtml = buildStandardReportTableHtml({
    columns: [
      { label: "Particular" },
      { label: "Amount (₹)", align: "right", className: "num" },
    ],
    bodyHtml: `
      <tr><td>Book Closing Balance</td><td class="num">${formatMoney(review.bookClosingBalance)}</td></tr>
      <tr><td>+ Deposits in Transit</td><td class="num">${formatMoney(review.depositsInTransit)}</td></tr>
      <tr><td>- Unpresented Cheques</td><td class="num">${formatMoney(review.unpresentedCheques)}</td></tr>
      <tr class="subtotal"><td><strong>Adjusted Book Balance</strong></td><td class="num"><strong>${formatMoney(review.formula.adjustedBookBalance)}</strong></td></tr>
      <tr><td>Statement Closing Balance</td><td class="num">${formatMoney(review.statementClosingBalance)}</td></tr>
      <tr class="total"><td><strong>Final Difference</strong></td><td class="num ${Math.abs(review.formula.finalDifference) > 0.009 ? "warn" : ""}"><strong>${formatMoney(review.formula.finalDifference)}</strong></td></tr>`,
  });

  const outstandingColumns: ReportColumnHeader[] = [
    { label: "Date" },
    { label: "Voucher" },
    { label: "Party" },
    { label: "Amount (₹)", align: "right", className: "num" },
    { label: "Reason" },
  ];

  const outstandingHtml = buildStandardReportTableHtml({
    columns: outstandingColumns,
    bodyHtml: review.outstandingBook
      .map(
        (o) =>
          `<tr>
            <td>${escapeHtml(o.bookDate)}</td>
            <td class="mono">${escapeHtml(o.voucherNo)}</td>
            <td>${escapeHtml(o.partyLedger)}</td>
            <td class="num">${formatMoney(o.deposit || o.withdrawal)}</td>
            <td>${escapeHtml(o.reason)}</td>
          </tr>`,
      )
      .join(""),
  });

  const bodyHtml = `
    <p class="report-subtitle" style="text-align:left;margin-top:12px;">Balance Summary</p>
    ${balanceSummaryHtml}
    <p class="report-subtitle" style="text-align:left;margin-top:16px;">Outstanding Book Entries (${review.outstandingBook.length})</p>
    ${outstandingHtml}`;

  const html = buildReportDocumentHtml({
    title: "Bank Reconciliation Report",
    header,
    bodyHtml,
  });
  openReportPrintWindow(html);
}

export async function exportOutstandingItemsReport(
  session: BankReconSessionRecord,
  review: BankReconReviewSnapshot,
): Promise<void> {
  const XLSX = await import("xlsx");
  const rows = [
    ...review.outstandingBook.map((o) => ({
      Type: "Book Outstanding",
      Date: o.bookDate,
      Reference: o.reference,
      Party: o.partyLedger,
      Amount: o.deposit || o.withdrawal,
      Direction: o.deposit > 0 ? "Deposit" : "Withdrawal",
      Ageing: o.ageingDays,
      Status: o.carryForwardStatus,
      Remarks: o.reason,
    })),
    ...review.statementOnly.map((s) => ({
      Type: "Statement Only",
      Date: s.statementDate,
      Reference: s.reference,
      Party: s.narration,
      Amount: s.deposit || s.withdrawal,
      Direction: s.deposit > 0 ? "Deposit" : "Withdrawal",
      Ageing: "",
      Status: s.status,
      Remarks: s.requiredAction,
    })),
  ];
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(rows), "Outstanding Items");
  XLSX.writeFile(wb, `Outstanding_Items_${session.reconciliationNumber ?? session.id}.xlsx`);
}

export async function exportAuditTrailToExcel(
  rows: { timestamp: string; user: string; action: string; reference: string | null; reason: string | null }[],
  bankAccountId: string,
): Promise<void> {
  const XLSX = await import("xlsx");
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(
    wb,
    XLSX.utils.json_to_sheet(
      rows.map((r) => ({
        "Date & Time": new Date(r.timestamp).toLocaleString("en-IN"),
        User: r.user,
        Action: r.action,
        Reference: r.reference ?? "",
        Reason: r.reason ?? "",
      })),
    ),
    "Audit Trail",
  );
  XLSX.writeFile(wb, `Bank_Recon_Audit_${bankAccountId}_${new Date().toISOString().slice(0, 10)}.xlsx`);
}
