/**
 * Step 5 categorize demo — additional uncategorized statement rows for voucher creation testing.
 */

import type { BankReconActivityEvent } from "@/app/(app)/accounts/bank-reconciliation/bank-reconciliation-v2-data";
import type { BankReconTransactionRecord } from "@/lib/accounts/bank-recon-register";
import { enrichRecordWithManualDefaults } from "@/lib/accounts/bank-recon-manual-demo-seed";

function act(
  id: string,
  label: string,
  detail: string,
  tone: BankReconActivityEvent["tone"] = "blue",
): BankReconActivityEvent {
  return {
    id,
    label,
    detail,
    actor: "System",
    timestamp: "11 Jul 2026 09:00",
    tone,
  };
}

export const CATEGORIZE_DEMO_TRANSACTIONS: BankReconTransactionRecord[] = [
  enrichRecordWithManualDefaults({
    id: "cat-demo-receipt-001",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-12",
    valueDate: "2026-07-12",
    bookDate: null,
    reference: "NEFT-CAT-001",
    utrNumber: "NEFT-CAT-001",
    chequeNo: null,
    narration: "NEFT CR — ABC Agro Distributor — categorize as customer receipt",
    partyLedger: "ABC Agro Distributor",
    deposit: 170000,
    withdrawal: 0,
    source: "Statement Upload",
    matchStatus: "Uncategorized",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "NEFT",
    importBatchId: "batch-cat-demo",
    activity: [act("c1", "Statement Imported", "Ready for customer receipt categorization", "blue")],
  }),
  enrichRecordWithManualDefaults({
    id: "cat-demo-receipt-partial",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-13",
    valueDate: "2026-07-13",
    bookDate: null,
    reference: "NEFT-CAT-002",
    utrNumber: "NEFT-CAT-002",
    chequeNo: null,
    narration: "Partial receipt — Krishna Retail",
    partyLedger: "Krishna Retail",
    deposit: 120000,
    withdrawal: 0,
    source: "Statement Upload",
    matchStatus: "Uncategorized",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "NEFT",
    importBatchId: "batch-cat-demo",
    activity: [act("c2", "Statement Imported", "Partial payment scenario", "blue")],
  }),
  enrichRecordWithManualDefaults({
    id: "cat-demo-receipt-advance",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-14",
    valueDate: "2026-07-14",
    bookDate: null,
    reference: "NEFT-CAT-003",
    utrNumber: "NEFT-CAT-003",
    chequeNo: null,
    narration: "Advance receipt — ABC Agro Distributor",
    partyLedger: "ABC Agro Distributor",
    deposit: 200000,
    withdrawal: 0,
    source: "Statement Upload",
    matchStatus: "Uncategorized",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "NEFT",
    importBatchId: "batch-cat-demo",
    activity: [act("c3", "Statement Imported", "Advance receipt scenario", "blue")],
  }),
  enrichRecordWithManualDefaults({
    id: "cat-demo-payment-vendor",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-15",
    valueDate: "2026-07-15",
    bookDate: null,
    reference: "PAY-CAT-001",
    utrNumber: null,
    chequeNo: null,
    narration: "RTGS DR — AgroChem Traders — vendor payment",
    partyLedger: "AgroChem Traders",
    deposit: 0,
    withdrawal: 245000,
    source: "Statement Upload",
    matchStatus: "Uncategorized",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "RTGS",
    importBatchId: "batch-cat-demo",
    activity: [act("c4", "Statement Imported", "Vendor payment categorization", "blue")],
  }),
  enrichRecordWithManualDefaults({
    id: "cat-demo-expense",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-16",
    valueDate: "2026-07-16",
    bookDate: null,
    reference: "CHG-CAT-001",
    utrNumber: null,
    chequeNo: null,
    narration: "Bank service charges — categorize as expense",
    partyLedger: "—",
    deposit: 0,
    withdrawal: 590,
    source: "Statement Upload",
    matchStatus: "Uncategorized",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "Other",
    importBatchId: "batch-cat-demo",
    activity: [act("c5", "Statement Imported", "Bank charges / expense", "blue")],
  }),
  enrichRecordWithManualDefaults({
    id: "cat-demo-interest-in",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-17",
    valueDate: "2026-07-17",
    bookDate: null,
    reference: "INT-CR-001",
    utrNumber: null,
    chequeNo: null,
    narration: "Interest credited by bank",
    partyLedger: "—",
    deposit: 1250,
    withdrawal: 0,
    source: "Statement Upload",
    matchStatus: "Uncategorized",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "Other",
    importBatchId: "batch-cat-demo",
    activity: [act("c6", "Statement Imported", "Interest income", "blue")],
  }),
  enrichRecordWithManualDefaults({
    id: "cat-demo-gst-pay",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-18",
    valueDate: "2026-07-18",
    bookDate: null,
    reference: "GST-CHQ-001",
    utrNumber: null,
    chequeNo: null,
    narration: "GST payment — CGST Q1",
    partyLedger: "—",
    deposit: 0,
    withdrawal: 45000,
    source: "Statement Upload",
    matchStatus: "Uncategorized",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "Cheque",
    importBatchId: "batch-cat-demo",
    activity: [act("c7", "Statement Imported", "GST payment scenario", "blue")],
  }),
  enrichRecordWithManualDefaults({
    id: "cat-demo-transfer",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-19",
    valueDate: "2026-07-19",
    bookDate: null,
    reference: "TRF-CAT-001",
    utrNumber: "TRF-CAT-001",
    chequeNo: null,
    narration: "Transfer to ICICI Collection Account",
    partyLedger: "—",
    deposit: 0,
    withdrawal: 100000,
    source: "Statement Upload",
    matchStatus: "Uncategorized",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "NEFT",
    importBatchId: "batch-cat-demo",
    activity: [act("c8", "Statement Imported", "Bank transfer — contra", "blue")],
  }),
];
