/**
 * Step 3 demo manual transactions — appended on register migration.
 */

import type { BankReconActivityEvent } from "@/app/(app)/accounts/bank-reconciliation/bank-reconciliation-v2-data";
import type { BankReconTransactionRecord } from "@/lib/accounts/bank-recon-register";

function act(
  id: string,
  label: string,
  detail: string,
  actor: string,
  timestamp: string,
  tone: BankReconActivityEvent["tone"] = "blue",
): BankReconActivityEvent {
  return { id, label, detail, actor, timestamp, tone };
}

const MANUAL_DEFAULTS: Omit<
  BankReconTransactionRecord,
  | "id"
  | "bankAccountId"
  | "statementDate"
  | "valueDate"
  | "bookDate"
  | "reference"
  | "utrNumber"
  | "chequeNo"
  | "narration"
  | "partyLedger"
  | "deposit"
  | "withdrawal"
  | "source"
  | "matchStatus"
  | "verificationStatus"
  | "activity"
> = {
  runningBalance: null,
  reconciliationDate: null,
  relatedRecord: null,
  importedFileName: null,
  importBatchId: null,
  importedBy: null,
  importedOn: null,
  originalRowNumber: null,
  originalRawData: null,
  savedFormatId: null,
  statementPeriodFrom: null,
  statementPeriodTo: null,
  internalStatementId: null,
  linkedManualTransactionId: null,
  manualTransactionNumber: null,
  manualEntryStatus: null,
  transactionMode: null,
  transactionDate: null,
  expectedClearingDate: null,
  chequeDate: null,
  depositedDate: null,
  drawerBank: null,
  drawerBranch: null,
  transactionIdRef: null,
  instrumentNumber: null,
  bankSlipNumber: null,
  externalReference: null,
  partyType: null,
  expectedVoucherType: null,
  existingVoucherRef: null,
  customerVendorRef: null,
  invoiceReference: null,
  purposeCategory: null,
  costCentre: null,
  internalRemarks: null,
  bankNarration: null,
  importedNarration: null,
  followUpNote: null,
  referenceStatus: null,
  currency: "INR",
  attachments: [],
  createdBy: null,
  createdOn: null,
  updatedBy: null,
  updatedOn: null,
  cancelReason: null,
  possibleDuplicateOverrideReason: null,
};

export function enrichRecordWithManualDefaults(
  t: Partial<BankReconTransactionRecord> & Pick<BankReconTransactionRecord, "id" | "bankAccountId">,
): BankReconTransactionRecord {
  const isManual = t.source === "Manual" || t.source === "Manual + Statement";
  return {
    ...MANUAL_DEFAULTS,
    statementDate: t.statementDate ?? "",
    valueDate: t.valueDate ?? "",
    bookDate: t.bookDate ?? null,
    reference: t.reference ?? "",
    utrNumber: t.utrNumber ?? null,
    chequeNo: t.chequeNo ?? null,
    narration: t.narration ?? "",
    partyLedger: t.partyLedger ?? "—",
    deposit: t.deposit ?? 0,
    withdrawal: t.withdrawal ?? 0,
    source: t.source ?? "Statement Upload",
    matchStatus: t.matchStatus ?? "Pending",
    verificationStatus: t.verificationStatus ?? "Not Applicable",
    activity: t.activity ?? [],
    manualEntryStatus:
      t.manualEntryStatus ??
      (isManual ? (t.source === "Manual + Statement" ? "Recorded" : "Recorded") : null),
    manualTransactionNumber: t.manualTransactionNumber ?? null,
    transactionMode: t.transactionMode ?? null,
    transactionDate: t.transactionDate ?? t.bookDate ?? null,
    expectedClearingDate: t.expectedClearingDate ?? null,
    chequeDate: t.chequeDate ?? null,
    depositedDate: t.depositedDate ?? null,
    drawerBank: t.drawerBank ?? null,
    drawerBranch: t.drawerBranch ?? null,
    transactionIdRef: t.transactionIdRef ?? null,
    instrumentNumber: t.instrumentNumber ?? null,
    bankSlipNumber: t.bankSlipNumber ?? null,
    externalReference: t.externalReference ?? null,
    partyType: t.partyType ?? null,
    expectedVoucherType: t.expectedVoucherType ?? null,
    existingVoucherRef: t.existingVoucherRef ?? null,
    customerVendorRef: t.customerVendorRef ?? null,
    invoiceReference: t.invoiceReference ?? null,
    purposeCategory: t.purposeCategory ?? null,
    costCentre: t.costCentre ?? null,
    internalRemarks: t.internalRemarks ?? null,
    bankNarration: t.bankNarration ?? null,
    importedNarration: t.importedNarration ?? null,
    followUpNote: t.followUpNote ?? null,
    referenceStatus:
      t.referenceStatus ??
      (isManual && !t.reference?.trim() && !t.utrNumber?.trim() && !t.chequeNo?.trim()
        ? "Pending"
        : isManual
          ? "Available"
          : null),
    currency: t.currency ?? "INR",
    attachments: t.attachments ?? [],
    createdBy: t.createdBy ?? null,
    createdOn: t.createdOn ?? null,
    updatedBy: t.updatedBy ?? null,
    updatedOn: t.updatedOn ?? null,
    cancelReason: t.cancelReason ?? null,
    possibleDuplicateOverrideReason: t.possibleDuplicateOverrideReason ?? null,
    runningBalance: t.runningBalance ?? null,
    reconciliationDate: t.reconciliationDate ?? null,
    relatedRecord: t.relatedRecord ?? null,
    importedFileName: t.importedFileName ?? null,
    importBatchId: t.importBatchId ?? null,
    importedBy: t.importedBy ?? null,
    importedOn: t.importedOn ?? null,
    originalRowNumber: t.originalRowNumber ?? null,
    originalRawData: t.originalRawData ?? null,
    savedFormatId: t.savedFormatId ?? null,
    statementPeriodFrom: t.statementPeriodFrom ?? null,
    statementPeriodTo: t.statementPeriodTo ?? null,
    internalStatementId: t.internalStatementId ?? null,
    linkedManualTransactionId: t.linkedManualTransactionId ?? null,
    ...t,
  };
}

export const MANUAL_DEMO_TRANSACTIONS: BankReconTransactionRecord[] = [
  enrichRecordWithManualDefaults({
    id: "manual-demo-001",
    bankAccountId: "hdfc-current",
    manualTransactionNumber: "MBT-HDFC-2026-00001",
    manualEntryStatus: "Recorded",
    statementDate: "",
    valueDate: "",
    bookDate: "2026-07-08",
    transactionDate: "2026-07-08",
    expectedClearingDate: "2026-07-10",
    chequeDate: "2026-07-05",
    depositedDate: "2026-07-08",
    reference: "",
    utrNumber: null,
    chequeNo: "458921",
    transactionMode: "Cheque",
    narration: "Customer cheque — Punjab Agro Distributors",
    bankNarration: "CHQ DEP 458921",
    partyLedger: "Punjab Agro Distributors",
    partyType: "Customer",
    expectedVoucherType: "Customer Receipt",
    deposit: 200000,
    withdrawal: 0,
    source: "Manual",
    matchStatus: "Pending",
    verificationStatus: "Awaiting Statement",
    referenceStatus: "Available",
    createdBy: "Priya Sharma",
    createdOn: "2026-07-08T10:15:00",
    activity: [
      act("md1-a", "Manual transaction created", "Customer cheque receipt ₹2,00,000", "Priya Sharma", "08 Jul 2026, 10:15 AM"),
    ],
  }),
  enrichRecordWithManualDefaults({
    id: "manual-demo-002",
    bankAccountId: "hdfc-current",
    manualTransactionNumber: "MBT-HDFC-2026-00002",
    manualEntryStatus: "Recorded",
    statementDate: "",
    valueDate: "",
    bookDate: "2026-07-09",
    transactionDate: "2026-07-09",
    expectedClearingDate: "2026-07-09",
    reference: "UTR HDFC2407090156",
    utrNumber: "UTR HDFC2407090156",
    chequeNo: null,
    transactionMode: "NEFT",
    narration: "NEFT from Maharashtra Seeds Corporation",
    partyLedger: "Maharashtra Seeds Corporation",
    partyType: "Customer",
    expectedVoucherType: "Customer Receipt",
    deposit: 150000,
    withdrawal: 0,
    source: "Manual",
    matchStatus: "Pending",
    verificationStatus: "Awaiting Statement",
    referenceStatus: "Available",
    createdBy: "Rajesh Kumar",
    createdOn: "2026-07-09T11:30:00",
    activity: [
      act("md2-a", "Manual transaction created", "NEFT receipt with UTR", "Rajesh Kumar", "09 Jul 2026, 11:30 AM"),
    ],
  }),
  enrichRecordWithManualDefaults({
    id: "manual-demo-003",
    bankAccountId: "icici-collection",
    manualTransactionNumber: "MBT-ICIC-2026-00001",
    manualEntryStatus: "Recorded",
    statementDate: "",
    valueDate: "",
    bookDate: "2026-07-07",
    transactionDate: "2026-07-07",
    expectedClearingDate: "2026-07-08",
    reference: "PAY-REF-ICICI-77821",
    utrNumber: null,
    chequeNo: null,
    transactionMode: "RTGS",
    narration: "Vendor payment — Gujarat Fertilizers Ltd",
    partyLedger: "Gujarat Fertilizers Ltd",
    partyType: "Vendor",
    expectedVoucherType: "Vendor Payment",
    deposit: 0,
    withdrawal: 75000,
    source: "Manual",
    matchStatus: "Pending",
    verificationStatus: "Awaiting Statement",
    referenceStatus: "Available",
    createdBy: "Priya Sharma",
    createdOn: "2026-07-07T14:00:00",
    activity: [
      act("md3-a", "Manual transaction created", "Vendor RTGS payment", "Priya Sharma", "07 Jul 2026, 2:00 PM"),
    ],
  }),
  enrichRecordWithManualDefaults({
    id: "manual-demo-004",
    bankAccountId: "hdfc-current",
    manualTransactionNumber: "MBT-HDFC-2026-00003",
    manualEntryStatus: "Recorded",
    statementDate: "",
    valueDate: "",
    bookDate: "2026-07-10",
    transactionDate: "2026-07-10",
    expectedClearingDate: "2026-07-11",
    reference: "",
    utrNumber: null,
    chequeNo: null,
    transactionMode: "Other",
    narration: "Bank charges — SMS & maintenance",
    partyLedger: "Bank Charges",
    partyType: "Expense Ledger",
    expectedVoucherType: "Bank Charges",
    deposit: 0,
    withdrawal: 590,
    source: "Manual",
    matchStatus: "Pending",
    verificationStatus: "Reference Pending",
    referenceStatus: "Pending",
    createdBy: "System",
    createdOn: "2026-07-10T09:00:00",
    activity: [
      act("md4-a", "Manual transaction created", "Bank charges — reference pending", "System", "10 Jul 2026, 9:00 AM", "amber"),
    ],
  }),
  enrichRecordWithManualDefaults({
    id: "manual-demo-005",
    bankAccountId: "sbi-cash-credit",
    manualTransactionNumber: "MBT-SBIC-2026-00001",
    manualEntryStatus: "Recorded",
    statementDate: "",
    valueDate: "",
    bookDate: "2026-07-06",
    transactionDate: "2026-07-06",
    expectedClearingDate: "2026-07-06",
    reference: "SLIP-SBI-4421",
    bankSlipNumber: "SLIP-SBI-4421",
    utrNumber: null,
    chequeNo: null,
    transactionMode: "Cash Deposit",
    narration: "Cash deposit — field collection",
    partyLedger: "Cash in Hand",
    partyType: "Bank",
    expectedVoucherType: "Contra Voucher",
    deposit: 50000,
    withdrawal: 0,
    source: "Manual",
    matchStatus: "Pending",
    verificationStatus: "Awaiting Statement",
    referenceStatus: "Available",
    attachments: [
      {
        id: "att-demo-001",
        fileName: "deposit-slip-sbi-4421.pdf",
        fileType: "application/pdf",
        fileSize: 245760,
        category: "Deposit Slip",
        uploadedBy: "Field Agent — Amit",
        uploadedOn: "2026-07-06T16:45:00",
      },
    ],
    createdBy: "Amit Verma",
    createdOn: "2026-07-06T16:45:00",
    activity: [
      act("md5-a", "Manual transaction created", "Cash deposit with slip attached", "Amit Verma", "06 Jul 2026, 4:45 PM"),
      act("md5-b", "Attachment added", "deposit-slip-sbi-4421.pdf", "Amit Verma", "06 Jul 2026, 4:46 PM", "purple"),
    ],
  }),
  enrichRecordWithManualDefaults({
    id: "manual-demo-006",
    bankAccountId: "hdfc-current",
    manualTransactionNumber: "MBT-HDFC-2026-00004",
    manualEntryStatus: "Recorded",
    statementDate: "",
    valueDate: "",
    bookDate: "2026-07-09",
    transactionDate: "2026-07-09",
    expectedClearingDate: "2026-07-10",
    reference: "UTR HDFC2407090156X",
    utrNumber: "UTR HDFC2407090156X",
    chequeNo: null,
    transactionMode: "NEFT",
    narration: "NEFT from Maharashtra Seeds Corporation",
    partyLedger: "Maharashtra Seeds Corporation",
    partyType: "Customer",
    expectedVoucherType: "Customer Receipt",
    deposit: 150000,
    withdrawal: 0,
    source: "Manual",
    matchStatus: "Possible Duplicate",
    verificationStatus: "Review Required",
    referenceStatus: "Available",
    possibleDuplicateOverrideReason: "Confirmed separate NEFT — client sent correction with suffix X",
    createdBy: "Rajesh Kumar",
    createdOn: "2026-07-09T15:00:00",
    activity: [
      act("md6-a", "Duplicate warning shown", "Possible duplicate of MBT-HDFC-2026-00002", "System", "09 Jul 2026, 3:00 PM", "amber"),
      act("md6-b", "Possible duplicate overridden", "Confirmed separate NEFT — client sent correction with suffix X", "Rajesh Kumar", "09 Jul 2026, 3:05 PM", "amber"),
      act("md6-c", "Manual transaction created", "Saved after duplicate review", "Rajesh Kumar", "09 Jul 2026, 3:05 PM"),
    ],
  }),
  enrichRecordWithManualDefaults({
    id: "manual-demo-007",
    bankAccountId: "hdfc-current",
    manualTransactionNumber: "MBT-HDFC-2025-00012",
    manualEntryStatus: "Recorded",
    statementDate: "2026-06-04",
    valueDate: "2026-06-04",
    bookDate: "2026-06-03",
    transactionDate: "2026-06-03",
    expectedClearingDate: "2026-06-04",
    reference: "UTR HDFC2406030088",
    utrNumber: "UTR HDFC2406030088",
    chequeNo: null,
    transactionMode: "NEFT",
    narration: "NEFT from Agro Solutions Pvt Ltd",
    importedNarration: "NEFT CR-AGRO SOLUTIONS PVT LTD",
    partyLedger: "Agro Solutions Pvt Ltd",
    partyType: "Customer",
    expectedVoucherType: "Customer Receipt",
    deposit: 325000,
    withdrawal: 0,
    source: "Manual + Statement",
    matchStatus: "Pending",
    verificationStatus: "Verified",
    referenceStatus: "Available",
    importBatchId: "batch-demo-linked",
    importedFileName: "hdfc-jun-2026-partial.csv",
    importedBy: "Priya Sharma",
    importedOn: "2026-06-05T10:00:00",
    createdBy: "Priya Sharma",
    createdOn: "2026-06-03T09:30:00",
    updatedBy: "Priya Sharma",
    updatedOn: "2026-06-05T10:00:00",
    activity: [
      act("md7-a", "Manual transaction created", "NEFT recorded before statement", "Priya Sharma", "03 Jun 2026, 9:30 AM"),
      act("md7-b", "Statement linked", "Book date preserved — statement date 04 Jun 2026", "Priya Sharma", "05 Jun 2026, 10:00 AM", "emerald"),
    ],
  }),
  enrichRecordWithManualDefaults({
    id: "manual-demo-008",
    bankAccountId: "icici-collection",
    manualTransactionNumber: "MBT-ICIC-2026-00002",
    manualEntryStatus: "Cancelled",
    statementDate: "",
    valueDate: "",
    bookDate: "2026-07-05",
    transactionDate: "2026-07-05",
    reference: "WRONG-ENTRY-001",
    utrNumber: null,
    chequeNo: null,
    transactionMode: "UPI",
    narration: "Erroneous UPI entry — duplicate of existing receipt",
    partyLedger: "—",
    deposit: 25000,
    withdrawal: 0,
    source: "Manual",
    matchStatus: "Pending",
    verificationStatus: "Awaiting Statement",
    cancelReason: "Entered twice by mistake — original receipt already recorded",
    createdBy: "Rajesh Kumar",
    createdOn: "2026-07-05T12:00:00",
    updatedBy: "Rajesh Kumar",
    updatedOn: "2026-07-05T12:30:00",
    activity: [
      act("md8-a", "Manual transaction created", "UPI deposit entry", "Rajesh Kumar", "05 Jul 2026, 12:00 PM"),
      act("md8-b", "Transaction cancelled", "Entered twice by mistake — original receipt already recorded", "Rajesh Kumar", "05 Jul 2026, 12:30 PM", "slate"),
    ],
  }),
];
