/**
 * Step 6 manual reconciliation demo — additional statement rows for matching scenarios.
 */

import type { BankReconActivityEvent } from "@/app/(app)/accounts/bank-reconciliation/bank-reconciliation-v2-data";
import type { BankReconTransactionRecord } from "@/lib/accounts/bank-recon-register";
import { enrichRecordWithManualDefaults } from "@/lib/accounts/bank-recon-manual-demo-seed";

function act(
  id: string,
  label: string,
  detail: string,
  actor: string,
  timestamp: string,
  tone: BankReconActivityEvent["tone"] = "blue",
): BankReconActivityEvent {
  return { id, label, detail, actor, timestamp, tone };
}

/** Appended on v2-step6 migration */
export const MANUAL_RECON_DEMO_TRANSACTIONS: BankReconTransactionRecord[] = [
  enrichRecordWithManualDefaults({
    id: "mrecon-demo-001",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-11",
    valueDate: "2026-07-11",
    bookDate: null,
    reference: "SPLIT-A",
    utrNumber: "SPLIT-A",
    chequeNo: null,
    narration: "NEFT CR — partial split A",
    partyLedger: "—",
    deposit: 120000,
    withdrawal: 0,
    source: "Statement Upload",
    matchStatus: "Pending",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "NEFT",
    importedFileName: "hdfc-mrecon-demo.csv",
    importBatchId: "batch-mrecon-demo",
    activity: [act("mr1", "Statement Imported", "One-to-many split part 1", "System", "11 Jul 2026")],
  }),
  enrichRecordWithManualDefaults({
    id: "mrecon-demo-002",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-11",
    valueDate: "2026-07-11",
    bookDate: null,
    reference: "SPLIT-B",
    utrNumber: "SPLIT-B",
    chequeNo: null,
    narration: "NEFT CR — partial split B",
    partyLedger: "—",
    deposit: 80000,
    withdrawal: 0,
    source: "Statement Upload",
    matchStatus: "Pending",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "NEFT",
    importedFileName: "hdfc-mrecon-demo.csv",
    importBatchId: "batch-mrecon-demo",
    activity: [act("mr2", "Statement Imported", "One-to-many split part 2", "System", "11 Jul 2026")],
  }),
  enrichRecordWithManualDefaults({
    id: "mrecon-demo-003",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-12",
    valueDate: "2026-07-12",
    bookDate: null,
    reference: "PARTIAL-120K",
    utrNumber: "PARTIAL-120K",
    chequeNo: null,
    narration: "NEFT CR — partial reconciliation candidate",
    partyLedger: "—",
    deposit: 120000,
    withdrawal: 0,
    source: "Statement Upload",
    matchStatus: "Pending",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "NEFT",
    importedFileName: "hdfc-mrecon-demo.csv",
    importBatchId: "batch-mrecon-demo",
    activity: [act("mr3", "Statement Imported", "Partial match against ₹2L book", "System", "12 Jul 2026")],
  }),
  enrichRecordWithManualDefaults({
    id: "mrecon-demo-004",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-13",
    valueDate: "2026-07-13",
    bookDate: null,
    reference: "GRP-A",
    utrNumber: null,
    chequeNo: null,
    narration: "Grouped deposit A",
    partyLedger: "—",
    deposit: 100000,
    withdrawal: 0,
    source: "Statement Upload",
    matchStatus: "Pending",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "NEFT",
    importedFileName: "hdfc-mrecon-demo.csv",
    importBatchId: "batch-mrecon-demo",
    activity: [act("mr4", "Statement Imported", "Many-to-many group A", "System", "13 Jul 2026")],
  }),
  enrichRecordWithManualDefaults({
    id: "mrecon-demo-005",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-13",
    valueDate: "2026-07-13",
    bookDate: null,
    reference: "GRP-B",
    utrNumber: null,
    chequeNo: null,
    narration: "Grouped deposit B",
    partyLedger: "—",
    deposit: 100000,
    withdrawal: 0,
    source: "Statement Upload",
    matchStatus: "Pending",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "NEFT",
    importedFileName: "hdfc-mrecon-demo.csv",
    importBatchId: "batch-mrecon-demo",
    activity: [act("mr5", "Statement Imported", "Many-to-many group B", "System", "13 Jul 2026")],
  }),
  enrichRecordWithManualDefaults({
    id: "mrecon-demo-006",
    bankAccountId: "hdfc-current",
    statementDate: "2026-07-14",
    valueDate: "2026-07-14",
    bookDate: null,
    reference: "STMT-ONLY-CHG",
    utrNumber: null,
    chequeNo: null,
    narration: "SMS alert charges",
    partyLedger: "Bank Charges",
    deposit: 0,
    withdrawal: 118,
    source: "Statement Upload",
    matchStatus: "Pending",
    verificationStatus: "Verified Statement Entry",
    transactionMode: "Other",
    importedFileName: "hdfc-mrecon-demo.csv",
    importBatchId: "batch-mrecon-demo",
    activity: [act("mr6", "Statement Imported", "Statement-only bank charge", "System", "14 Jul 2026")],
  }),
];
