import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import { formatMoney, formatMoneyNumber } from "@/lib/accounts/money-format";
import type { SupplierInvoiceOutstandingRow, VendorAgeingRow } from "@/lib/accounts/payables-data";
import type { PaymentAllocationVendorRow } from "@/lib/accounts/payables-data";

const COMPANY_NAME = "Dharitri Sutra Agri Solutions Pvt Ltd";

export interface PayablesExportMeta {
  reportName: string;
  financialYear: string;
  dateFrom?: string;
  dateTo?: string;
  asOnDate?: string;
  supplier: string;
  paymentStatus: string;
  search: string;
}

function generatedOnLabel(): string {
  return new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function metaRows(meta: PayablesExportMeta) {
  const rows: string[][] = [
    ["Company Name", COMPANY_NAME],
    ["Report Name", meta.reportName],
    ["Financial Year", meta.financialYear],
    ["Supplier", meta.supplier],
    ["Payment Status", meta.paymentStatus],
    ["Search", meta.search || "—"],
    ["Generated By", ACCOUNTS_CURRENT_USER],
    ["Generated On", generatedOnLabel()],
  ];
  if (meta.dateFrom && meta.dateTo) {
    rows.splice(3, 0, ["Date Range", `${meta.dateFrom} to ${meta.dateTo}`]);
  }
  if (meta.asOnDate) {
    rows.splice(3, 0, ["As On Date", meta.asOnDate]);
  }
  return rows;
}

function statusLabel(status: string): string {
  return status.replaceAll("_", " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

export async function exportSupplierOutstandingToExcel(
  rows: SupplierInvoiceOutstandingRow[],
  meta: PayablesExportMeta,
): Promise<void> {
  const XLSX = await import("xlsx");

  const dataRows = rows.map((r) => ({
    Supplier: r.vendorName,
    "Supplier Code": r.vendorCode,
    GSTIN: r.gstin,
    "Invoice No.": r.invoiceNo,
    "Invoice Date": r.invoiceDate,
    "Due Date": r.dueDate,
    "Bill Amount (₹)": r.billAmount,
    "Paid Amount (₹)": r.paidAmount,
    "Outstanding (₹)": r.outstanding,
    "Overdue Days": r.overdueDays,
    Status: statusLabel(r.status),
  }));

  const sheet = XLSX.utils.json_to_sheet(dataRows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, sheet, "Supplier Outstanding");

  const info = XLSX.utils.aoa_to_sheet(metaRows(meta));
  XLSX.utils.book_append_sheet(wb, info, "Report Info");

  const date = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `Supplier_Outstanding_${date}.xlsx`);
}

export function exportSupplierOutstandingToPdf(
  rows: SupplierInvoiceOutstandingRow[],
  meta: PayablesExportMeta,
): void {
  const tableRows = rows
    .map(
      (r) => `
    <tr>
      <td>${r.vendorName}</td>
      <td>${r.vendorCode}</td>
      <td>${r.gstin}</td>
      <td>${r.invoiceNo}</td>
      <td>${r.invoiceDate}</td>
      <td>${r.dueDate}</td>
      <td class="num">${formatMoneyNumber(r.billAmount)}</td>
      <td class="num">${formatMoneyNumber(r.paidAmount)}</td>
      <td class="num">${formatMoneyNumber(r.outstanding)}</td>
      <td class="num">${r.overdueDays}</td>
      <td>${statusLabel(r.status)}</td>
    </tr>`,
    )
    .join("");

  const metaHtml = metaRows(meta)
    .map(([k, v]) => `<tr><td><strong>${k}</strong></td><td>${v}</td></tr>`)
    .join("");

  const html = `<!DOCTYPE html><html><head><title>${meta.reportName}</title>
    <style>
      body { font-family: Arial, sans-serif; font-size: 11px; padding: 24px; }
      h1 { font-size: 16px; margin-bottom: 4px; }
      table { width: 100%; border-collapse: collapse; margin-top: 16px; }
      th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; }
      th { background: #f3f4f6; font-size: 10px; }
      .num { text-align: right; }
      .meta { margin-bottom: 16px; }
      .meta td { border: none; padding: 2px 8px 2px 0; }
    </style></head><body>
    <h1>${meta.reportName}</h1>
    <table class="meta">${metaHtml}</table>
    <table>
      <thead><tr>
        <th>Supplier</th><th>Code</th><th>GSTIN</th><th>Invoice No.</th>
        <th>Invoice Date</th><th>Due Date</th><th>Bill Amount</th>
        <th>Paid</th><th>Outstanding</th><th>Overdue Days</th><th>Status</th>
      </tr></thead>
      <tbody>${tableRows}</tbody>
    </table>
  </body></html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
  win.print();
}

export async function exportSupplierAgeingToExcel(
  rows: VendorAgeingRow[],
  meta: PayablesExportMeta,
): Promise<void> {
  const XLSX = await import("xlsx");

  const dataRows = rows.map((r) => ({
    Supplier: r.vendorName,
    "Total Outstanding (₹)": r.totalOutstanding,
    "0-30 Days (₹)": r.bucket0_30,
    "31-60 Days (₹)": r.bucket31_60,
    "61-90 Days (₹)": r.bucket61_90,
    "91-120 Days (₹)": r.bucket91_120,
    "Above 120 Days (₹)": r.bucketAbove120,
  }));

  const sheet = XLSX.utils.json_to_sheet(dataRows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, sheet, "Supplier Ageing");

  const info = XLSX.utils.aoa_to_sheet(metaRows(meta));
  XLSX.utils.book_append_sheet(wb, info, "Report Info");

  const date = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `Supplier_Ageing_${date}.xlsx`);
}

export function exportSupplierAgeingToPdf(rows: VendorAgeingRow[], meta: PayablesExportMeta): void {
  const tableRows = rows
    .map(
      (r) => `
    <tr>
      <td>${r.vendorName}</td>
      <td class="num">${formatMoneyNumber(r.totalOutstanding)}</td>
      <td class="num">${formatMoneyNumber(r.bucket0_30)}</td>
      <td class="num">${formatMoneyNumber(r.bucket31_60)}</td>
      <td class="num">${formatMoneyNumber(r.bucket61_90)}</td>
      <td class="num">${formatMoneyNumber(r.bucket91_120)}</td>
      <td class="num">${formatMoneyNumber(r.bucketAbove120)}</td>
    </tr>`,
    )
    .join("");

  const metaHtml = metaRows(meta)
    .map(([k, v]) => `<tr><td><strong>${k}</strong></td><td>${v}</td></tr>`)
    .join("");

  const html = `<!DOCTYPE html><html><head><title>${meta.reportName}</title>
    <style>
      body { font-family: Arial, sans-serif; font-size: 11px; padding: 24px; }
      h1 { font-size: 16px; }
      table { width: 100%; border-collapse: collapse; margin-top: 16px; }
      th, td { border: 1px solid #ccc; padding: 6px 8px; }
      th { background: #f3f4f6; }
      .num { text-align: right; }
      .meta td { border: none; padding: 2px 8px 2px 0; }
    </style></head><body>
    <h1>${meta.reportName}</h1>
    <table class="meta">${metaHtml}</table>
    <table>
      <thead><tr>
        <th>Supplier</th><th>Total Outstanding</th><th>0-30 Days</th>
        <th>31-60 Days</th><th>61-90 Days</th><th>91-120 Days</th><th>Above 120 Days</th>
      </tr></thead>
      <tbody>${tableRows}</tbody>
    </table>
  </body></html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
  win.print();
}

export async function exportPaymentAllocationToExcel(
  rows: PaymentAllocationVendorRow[],
  meta: PayablesExportMeta,
): Promise<void> {
  const XLSX = await import("xlsx");

  const dataRows = rows.map((r) => ({
    Supplier: r.vendorName,
    "Supplier Code": r.vendorCode,
    "Total Outstanding (₹)": r.totalOutstanding,
    "Payment Available (₹)": r.totalPaymentAvailable,
    "Unallocated Balance (₹)": r.unallocatedBalance,
    Status: statusLabel(r.status),
  }));

  const sheet = XLSX.utils.json_to_sheet(dataRows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, sheet, "Payment Allocation");

  const info = XLSX.utils.aoa_to_sheet(metaRows(meta));
  XLSX.utils.book_append_sheet(wb, info, "Report Info");

  const date = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `Payment_Allocation_${date}.xlsx`);
}

export function exportPaymentAllocationToPdf(
  rows: PaymentAllocationVendorRow[],
  meta: PayablesExportMeta,
): void {
  const tableRows = rows
    .map(
      (r) => `
    <tr>
      <td>${r.vendorName}</td>
      <td>${r.vendorCode}</td>
      <td class="num">${formatMoney(r.totalOutstanding)}</td>
      <td class="num">${formatMoney(r.totalPaymentAvailable)}</td>
      <td class="num">${formatMoney(r.unallocatedBalance)}</td>
      <td>${statusLabel(r.status)}</td>
    </tr>`,
    )
    .join("");

  const metaHtml = metaRows(meta)
    .map(([k, v]) => `<tr><td><strong>${k}</strong></td><td>${v}</td></tr>`)
    .join("");

  const html = `<!DOCTYPE html><html><head><title>${meta.reportName}</title>
    <style>
      body { font-family: Arial, sans-serif; font-size: 11px; padding: 24px; }
      table { width: 100%; border-collapse: collapse; margin-top: 16px; }
      th, td { border: 1px solid #ccc; padding: 6px 8px; }
      th { background: #f3f4f6; }
      .num { text-align: right; }
      .meta td { border: none; }
    </style></head><body>
    <h1>${meta.reportName}</h1>
    <table class="meta">${metaHtml}</table>
    <table>
      <thead><tr>
        <th>Supplier</th><th>Code</th><th>Total Outstanding</th>
        <th>Payment Available</th><th>Unallocated Balance</th><th>Status</th>
      </tr></thead>
      <tbody>${tableRows}</tbody>
    </table>
  </body></html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
  win.print();
}
