import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import { formatMoney, formatMoneyNumber, formatMoneyOrDash } from "@/lib/accounts/money-format";

/** Standard company name for all accounting report exports. */
export const ACCOUNTS_COMPANY_NAME = "Dharitri Sutra Agri Solutions Pvt Ltd";

/** Accounting hierarchy row types used across financial statement exports. */
export type HierarchyRowType =
  | "title"
  | "primary"
  | "group"
  | "subgroup"
  | "header"
  | "section"
  | "line"
  | "subtotal"
  | "total"
  | "net"
  | "summary";

export interface ReportFilterLine {
  label: string;
  value: string;
}

export interface ReportHeaderOptions {
  reportTitle: string;
  financialYear?: string;
  /** Pre-formatted period label, e.g. "01 Apr 2024 to 31 Mar 2025" or "As on 31 Mar 2025". */
  reportPeriod?: string;
  dateFrom?: string;
  dateTo?: string;
  asOnDate?: string;
  subtitle?: string;
  filters?: ReportFilterLine[];
}

export interface ReportColumnHeader {
  label: string;
  align?: "left" | "right" | "center";
  className?: string;
}

export interface TAccountExportRow {
  rowType: HierarchyRowType | "title";
  leftParticular: string;
  leftIndent: number;
  leftAmount: number | null;
  leftBold?: boolean;
  rightParticular: string;
  rightIndent: number;
  rightAmount: number | null;
  rightBold?: boolean;
}

export interface ReportDocumentOptions {
  title: string;
  header: ReportHeaderOptions;
  bodyHtml: string;
  footerHtml?: string;
  landscape?: boolean;
  compact?: boolean;
}

const INDENT_SPACES = 4;

export function generatedOnLabel(): string {
  return new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Indent label for accounting hierarchy (Primary → Group → Sub Group → Ledger). */
export function indentParticular(label: string, indent: number, spacesPerLevel = INDENT_SPACES): string {
  if (!label) return "";
  return `${" ".repeat(spacesPerLevel * Math.max(0, indent))}${label}`;
}

export function formatExportAmount(
  amount: number | null | undefined,
  options?: { isReturn?: boolean; dashWhenZero?: boolean; rawNumber?: boolean },
): string {
  if (amount == null) return "";
  if (options?.dashWhenZero && amount === 0) return "—";
  if (options?.rawNumber) return formatMoneyNumber(amount);
  if (options?.isReturn && amount > 0) return `(${formatMoney(amount)})`;
  if (amount < 0) return `(${formatMoney(Math.abs(amount))})`;
  return formatMoney(amount);
}

export function formatExportAmountOrDash(amount: number): string {
  return formatMoneyOrDash(amount);
}

export function hierarchyRowClass(rowType: HierarchyRowType | "title"): string {
  return rowType;
}

export function resolveReportPeriod(header: ReportHeaderOptions): string {
  if (header.reportPeriod) return header.reportPeriod;
  if (header.asOnDate) return `As on ${header.asOnDate}`;
  if (header.dateFrom && header.dateTo) return `${header.dateFrom} to ${header.dateTo}`;
  return "";
}

export function buildMetaRows(header: ReportHeaderOptions, extraRows: string[][] = []): string[][] {
  const rows: string[][] = [
    ["Company Name", ACCOUNTS_COMPANY_NAME],
    ["Report Name", header.reportTitle],
  ];
  const period = resolveReportPeriod(header);
  if (header.financialYear) rows.push(["Financial Year", header.financialYear]);
  if (period) rows.push(["Report Period", period]);
  if (header.subtitle) rows.push(["Subtitle", header.subtitle]);
  for (const filter of header.filters ?? []) {
    rows.push([filter.label, filter.value]);
  }
  rows.push(["Generated By", ACCOUNTS_CURRENT_USER]);
  rows.push(["Generated On", generatedOnLabel()]);
  return [...rows, ...extraRows];
}

function buildFilterLinesHtml(header: ReportHeaderOptions): string {
  const lines: string[] = [];
  if (header.subtitle) {
    lines.push(`<p class="report-subtitle">${escapeHtml(header.subtitle)}</p>`);
  }
  for (const filter of header.filters ?? []) {
    lines.push(
      `<p class="report-filter"><span class="filter-label">${escapeHtml(filter.label)}:</span> ${escapeHtml(filter.value)}</p>`,
    );
  }
  lines.push(
    `<p class="report-generated">Generated by ${escapeHtml(ACCOUNTS_CURRENT_USER)} · ${escapeHtml(generatedOnLabel())}</p>`,
  );
  return lines.join("\n");
}

/** Centered report header — company name, title, FY, and period. */
export function buildReportHeaderHtml(header: ReportHeaderOptions): string {
  const period = resolveReportPeriod(header);
  const fyLine = header.financialYear
    ? `<p class="report-fy"><strong>Financial Year:</strong> ${escapeHtml(header.financialYear)}</p>`
    : "";
  const periodLine = period
    ? `<p class="report-period"><strong>Report Period:</strong> ${escapeHtml(period)}</p>`
    : "";

  return `<header class="report-header">
  <p class="report-company">${escapeHtml(ACCOUNTS_COMPANY_NAME)}</p>
  <h1 class="report-title">${escapeHtml(header.reportTitle)}</h1>
  ${fyLine}
  ${periodLine}
  ${buildFilterLinesHtml(header)}
</header>`;
}

export function buildBalanceMessageHtml(
  message: string,
  variant: "balanced" | "unbalanced" | "info" | "warning",
): string {
  return `<p class="balance-msg ${variant}">${escapeHtml(message)}</p>`;
}

export function buildStandardReportTableHtml(options: {
  columns: ReportColumnHeader[];
  bodyHtml: string;
  footerHtml?: string;
  tableClass?: string;
}): string {
  const headCells = options.columns
    .map((col) => {
      const align = col.align ?? "left";
      const cls = [align !== "left" ? align : "", col.className ?? ""].filter(Boolean).join(" ");
      return `<th class="${cls}">${escapeHtml(col.label)}</th>`;
    })
    .join("");

  const tfoot = options.footerHtml ? `<tfoot>${options.footerHtml}</tfoot>` : "";
  const tableClass = options.tableClass ? ` class="${options.tableClass}"` : "";

  return `<table${tableClass}>
  <thead><tr>${headCells}</tr></thead>
  <tbody>${options.bodyHtml}</tbody>
  ${tfoot}
</table>`;
}

export function buildTAccountTableHtml(options: {
  leftTitle: string;
  leftAmountHeader: string;
  rightTitle: string;
  rightAmountHeader: string;
  rowsHtml: string;
}): string {
  return `<table class="t-account">
  <thead>
    <tr>
      <th class="label-col">${escapeHtml(options.leftTitle)}</th>
      <th class="num">${escapeHtml(options.leftAmountHeader)}</th>
      <th class="divider" aria-hidden="true"></th>
      <th class="label-col">${escapeHtml(options.rightTitle)}</th>
      <th class="num">${escapeHtml(options.rightAmountHeader)}</th>
    </tr>
  </thead>
  <tbody>${options.rowsHtml}</tbody>
</table>`;
}

export function buildTAccountRowHtml(row: TAccountExportRow): string {
  const rowClass = hierarchyRowClass(row.rowType);
  const leftLabel = escapeHtml(indentParticular(row.leftParticular, row.leftIndent));
  const rightLabel = escapeHtml(indentParticular(row.rightParticular, row.rightIndent));
  const leftBold = row.leftBold ? " bold" : "";
  const rightBold = row.rightBold ? " bold" : "";
  const leftAmount = formatExportAmount(row.leftAmount);
  const rightAmount = formatExportAmount(row.rightAmount);

  if (row.rowType === "title") {
    return `<tr class="${rowClass}">
      <td class="label bold" colspan="2">${leftLabel}</td>
      <td class="divider"></td>
      <td class="label" colspan="2"></td>
    </tr>`;
  }

  return `<tr class="${rowClass}">
    <td class="label${leftBold}">${leftLabel}</td>
    <td class="num${leftBold}">${leftAmount}</td>
    <td class="divider"></td>
    <td class="label${rightBold}">${rightLabel}</td>
    <td class="num${rightBold}">${rightAmount}</td>
  </tr>`;
}

/** Shared print CSS for all accounting report PDF exports. */
export function buildReportPrintCss(options?: { landscape?: boolean; compact?: boolean }): string {
  const pageSize = options?.landscape ? "landscape" : "portrait";
  const bodySize = options?.compact ? "9px" : "10px";
  const cellPad = options?.compact ? "4px 6px" : "5px 8px";

  return `
    @page {
      size: ${pageSize};
      margin: 14mm 12mm 18mm 12mm;
    }
    @media print {
      html, body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      thead { display: table-header-group; }
      tfoot { display: table-footer-group; }
      tr { page-break-inside: avoid; }
      .report-page-footer {
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
        text-align: center;
        font-size: 8px;
        color: #666;
        padding: 4px 0;
      }
    }
    * { box-sizing: border-box; }
    body {
      font-family: "Segoe UI", system-ui, -apple-system, sans-serif;
      font-size: ${bodySize};
      line-height: 1.45;
      color: #111827;
      padding: 16px 20px 28px;
      margin: 0;
    }
    .report-header {
      text-align: center;
      margin-bottom: 16px;
      padding-bottom: 12px;
      border-bottom: 2px solid #D96A10;
    }
    .report-company {
      font-size: 13px;
      font-weight: 700;
      color: #1A3A96;
      margin: 0 0 4px;
      letter-spacing: 0.01em;
    }
    .report-title {
      font-size: 16px;
      font-weight: 700;
      color: #111827;
      margin: 0 0 8px;
    }
    .report-fy, .report-period {
      font-size: 10px;
      margin: 2px 0;
      color: #374151;
    }
    .report-subtitle {
      font-size: 10px;
      font-weight: 600;
      margin: 6px 0 2px;
      color: #1A3A96;
    }
    .report-filter {
      font-size: 9px;
      margin: 1px 0;
      color: #4b5563;
    }
    .filter-label { font-weight: 600; }
    .report-generated {
      font-size: 8px;
      color: #6b7280;
      margin: 8px 0 0;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 8px;
      table-layout: fixed;
    }
    th, td {
      border: 1px solid #d1d5db;
      padding: ${cellPad};
      text-align: left;
      vertical-align: top;
      word-wrap: break-word;
    }
    th {
      background: #FFF3E8;
      font-size: 9px;
      font-weight: 700;
      color: #1A3A96;
      text-transform: none;
    }
    th.num, th.right, td.num, td.right { text-align: right; }
    th.center, td.center { text-align: center; }
    td.num, td.right {
      font-variant-numeric: tabular-nums;
      white-space: nowrap;
    }
    td.mono, .mono {
      font-family: ui-monospace, "Cascadia Code", monospace;
      font-size: 9px;
      color: #B85508;
    }
    td.indent-1 { padding-left: 16px; }
    td.indent-2 { padding-left: 28px; }
    td.indent-3 { padding-left: 40px; }
    tr.title td {
      font-weight: 700;
      font-size: 11px;
      text-align: center;
      background: #f8fafc;
      color: #1A3A96;
      border-bottom: 2px solid #D96A10;
    }
    tr.primary td, tr.header td, tr.section td {
      font-weight: 700;
      background: #FFF3E8;
      color: #1A3A96;
    }
    tr.group td.label, tr.group td:first-child {
      font-weight: 700;
      background: #fafafa;
    }
    tr.subgroup td.label, tr.subgroup td:first-child {
      font-weight: 700;
    }
    tr.subtotal td {
      font-weight: 700;
      background: #f9fafb;
    }
    tr.total td, tfoot td {
      font-weight: 700;
      background: #FFF3E8;
      border-top: 2px solid #D96A10;
      color: #B85508;
    }
    tr.net td {
      font-weight: 700;
      background: #F0F9F0;
      color: #1A5F22;
    }
    tr.net.loss td {
      background: #FEF2F2;
      color: #B91C1C;
    }
    tr.summary td, tr.summary-row td {
      font-weight: 700;
      background: #f3f4f6;
    }
    tr.line td.label:not(.bold) { font-weight: 400; }
    td.bold, .bold { font-weight: 700; }
    table.t-account td.divider, table.t-account th.divider {
      width: 6px;
      padding: 0;
      background: #e5e7eb;
      border-top: none;
      border-bottom: none;
    }
    table.t-account .label-col { width: 36%; }
    .balance-msg {
      margin-top: 12px;
      font-size: 10px;
      font-weight: 700;
      text-align: center;
      padding: 8px 12px;
      border-radius: 6px;
    }
    .balance-msg.balanced {
      background: #F0F9F0;
      color: #267A2E;
      border: 1px solid #B0E0B0;
    }
    .balance-msg.unbalanced {
      background: #fef2f2;
      color: #dc2626;
      border: 1px solid #fecaca;
    }
    .balance-msg.info {
      background: #EEF2FF;
      color: #1A3A96;
      border: 1px solid #D8E2FF;
    }
    .balance-msg.warning {
      background: #fffbeb;
      color: #b45309;
      border: 1px solid #fde68a;
    }
    .report-footer-note {
      margin-top: 12px;
      font-size: 9px;
      color: #6b7280;
      text-align: center;
      font-weight: 600;
    }
    .summary-strip {
      display: flex;
      flex-wrap: wrap;
      gap: 12px;
      margin: 10px 0 12px;
      justify-content: center;
    }
    .summary-strip-item {
      border: 1px solid #d1d5db;
      border-radius: 6px;
      padding: 6px 10px;
      font-size: 9px;
      min-width: 120px;
      text-align: center;
    }
    .summary-strip-item label {
      display: block;
      font-size: 8px;
      font-weight: 700;
      text-transform: uppercase;
      color: #6b7280;
      margin-bottom: 2px;
    }
    .summary-strip-item strong {
      font-variant-numeric: tabular-nums;
      color: #111827;
    }
    tr.unbalanced td { background: #FEF2F2; }
    .warn { color: #dc2626; font-weight: 700; }
  `;
}

/** Shared Excel HTML CSS — mirrors print styles for visual consistency. */
export function buildReportExcelCss(): string {
  return `
    body { font-family: Calibri, Arial, sans-serif; font-size: 11pt; color: #111827; }
    .report-header { text-align: center; margin-bottom: 14px; padding-bottom: 10px; border-bottom: 2px solid #D96A10; }
    .report-company { font-size: 13pt; font-weight: bold; color: #1A3A96; margin: 0 0 4px; }
    .report-title { font-size: 16pt; font-weight: bold; margin: 0 0 8px; }
    .report-fy, .report-period { font-size: 10pt; margin: 2px 0; }
    .report-filter { font-size: 9pt; margin: 1px 0; color: #4b5563; }
    .report-generated { font-size: 8pt; color: #6b7280; margin-top: 8px; }
    table { border-collapse: collapse; width: 100%; margin-top: 8px; }
    th, td { border: 1px solid #ccc; padding: 4px 6px; vertical-align: top; }
    th { background: #FFF3E8; font-weight: bold; color: #1A3A96; }
    .num { mso-number-format: "\\@"; text-align: right; white-space: nowrap; }
    tr.title td { font-weight: bold; text-align: center; background: #f8fafc; color: #1A3A96; }
    tr.primary td, tr.header td, tr.section td { font-weight: bold; background: #FFF3E8; color: #1A3A96; }
    tr.group td { font-weight: bold; background: #fafafa; }
    tr.subgroup td { font-weight: bold; }
    tr.subtotal td { font-weight: bold; background: #f9fafb; }
    tr.total td, tfoot td { font-weight: bold; background: #FFF3E8; border-top: 2px solid #D96A10; color: #B85508; }
    tr.net td { font-weight: bold; background: #F0F9F0; color: #1A5F22; }
    td.bold, .bold { font-weight: bold; }
    td.divider, th.divider { width: 6px; background: #e5e7eb; border-top: none; border-bottom: none; }
    .balance-msg { margin-top: 10px; font-weight: bold; text-align: center; padding: 6px; }
    .balance-msg.balanced { color: #267A2E; }
    .balance-msg.unbalanced { color: #dc2626; }
    .report-footer-note { margin-top: 10px; font-size: 9pt; text-align: center; color: #666; }
  `;
}

export function buildReportDocumentHtml(options: ReportDocumentOptions): string {
  const css = buildReportPrintCss({
    landscape: options.landscape,
    compact: options.compact,
  });
  const headerHtml = buildReportHeaderHtml(options.header);
  const footerNote = options.footerHtml ?? "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(options.title)}</title>
  <style>${css}</style>
</head>
<body>
  ${headerHtml}
  ${options.bodyHtml}
  ${footerNote}
  <script>window.onload = function() { window.print(); };</script>
</body>
</html>`;
}

export function buildReportExcelDocumentHtml(options: ReportDocumentOptions): string {
  const headerHtml = buildReportHeaderHtml(options.header);
  const footerNote = options.footerHtml ?? "";
  const sheetName = options.header.reportTitle.slice(0, 31).replace(/[\\/*?:[\]]/g, "");

  return `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel">
<head>
  <meta charset="utf-8" />
  <!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>${escapeHtml(sheetName)}</x:Name></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]-->
  <style>${buildReportExcelCss()}</style>
</head>
<body>
  ${headerHtml}
  ${options.bodyHtml}
  ${footerNote}
</body>
</html>`;
}

export function openReportPrintWindow(html: string): void {
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
}

export function downloadReportExcelHtml(html: string, filename: string): void {
  const blob = new Blob([html], { type: "application/vnd.ms-excel;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename.endsWith(".xls") ? filename : `${filename}.xls`;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function exportReportToPdf(options: ReportDocumentOptions): void {
  openReportPrintWindow(buildReportDocumentHtml(options));
}

export function exportReportToExcelHtml(options: ReportDocumentOptions, filename: string): void {
  downloadReportExcelHtml(buildReportExcelDocumentHtml(options), filename);
}

export function todayExportDateSuffix(): string {
  return new Date().toISOString().slice(0, 10);
}

/** Build a standard tabular PDF from headers + row HTML. */
export function exportTabularReportToPdf(options: {
  title: string;
  header: ReportHeaderOptions;
  columns: ReportColumnHeader[];
  bodyHtml: string;
  footerHtml?: string;
  footerNote?: string;
  landscape?: boolean;
}): void {
  const tableHtml = buildStandardReportTableHtml({
    columns: options.columns,
    bodyHtml: options.bodyHtml,
    footerHtml: options.footerHtml,
  });
  exportReportToPdf({
    title: options.title,
    header: options.header,
    bodyHtml: tableHtml,
    footerHtml: options.footerNote ? `<p class="report-footer-note">${options.footerNote}</p>` : undefined,
    landscape: options.landscape,
  });
}

/** Build a standard tabular Excel HTML export matching the PDF layout. */
export function exportTabularReportToExcelHtml(options: {
  title: string;
  header: ReportHeaderOptions;
  columns: ReportColumnHeader[];
  bodyHtml: string;
  footerHtml?: string;
  footerNote?: string;
  filename: string;
}): void {
  const tableHtml = buildStandardReportTableHtml({
    columns: options.columns,
    bodyHtml: options.bodyHtml,
    footerHtml: options.footerHtml,
  });
  exportReportToExcelHtml(
    {
      title: options.title,
      header: options.header,
      bodyHtml: tableHtml,
      footerHtml: options.footerNote ? `<p class="report-footer-note">${options.footerNote}</p>` : undefined,
    },
    options.filename,
  );
}
