import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import { formatMoney, formatMoneyOrDash, formatMoneyWithSide } from "@/lib/accounts/money-format";
import type { CustomerLedgerDisplayRow, CustomerLedgerSummary } from "./customer-ledger-data";

const COMPANY_NAME = "Dharitri Sutra Agri Solutions Pvt Ltd";
const REPORT_NAME = "Customer Ledger";

export interface CustomerLedgerExportMeta {
  dateFrom: string;
  dateTo: string;
  financialYear: string;
}

function generatedOnLabel(): string {
  return new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function balanceLabel(row: CustomerLedgerDisplayRow): string {
  return formatMoneyWithSide(row.runningBalance, row.runningBalanceType);
}

export async function exportCustomerLedgerToExcel(
  rows: CustomerLedgerDisplayRow[],
  summary: CustomerLedgerSummary,
  meta: CustomerLedgerExportMeta,
): Promise<void> {
  const XLSX = await import("xlsx");

  const dataRows = rows.map((r) => ({
    Date: r.date,
    "Voucher No.": r.kind === "closing" ? "—" : r.voucherNo,
    "Voucher Type": r.voucherType,
    Particular: r.particular,
    Narration: r.narration,
    "Debit (₹)": r.debit || "",
    "Credit (₹)": r.credit || "",
    "Running Balance": balanceLabel(r),
  }));

  const sheet = XLSX.utils.json_to_sheet(dataRows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, sheet, "Customer Ledger");

  const info = XLSX.utils.aoa_to_sheet([
    ["Company Name", COMPANY_NAME],
    ["Report Name", REPORT_NAME],
    ["Customer Name", summary.customerName],
    ["Customer Code", summary.customerCode],
    ["GSTIN", summary.gstin],
    ["PAN", summary.pan],
    ["Date Range", `${meta.dateFrom} to ${meta.dateTo}`],
    ["Financial Year", meta.financialYear],
    ["Opening Balance", formatMoneyWithSide(summary.openingBalance, summary.openingBalanceType)],
    ["Total Debit", summary.totalDebit],
    ["Total Credit", summary.totalCredit],
    ["Closing Balance", formatMoneyWithSide(summary.closingBalance, summary.closingBalanceType)],
    ["Generated By", ACCOUNTS_CURRENT_USER],
    ["Generated On", generatedOnLabel()],
  ]);
  XLSX.utils.book_append_sheet(wb, info, "Report Info");

  const safeName = summary.customerCode.replace(/[^\w-]+/g, "_");
  const date = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `Customer_Ledger_${safeName}_${date}.xlsx`);
}

export function exportCustomerLedgerToPdf(
  rows: CustomerLedgerDisplayRow[],
  summary: CustomerLedgerSummary,
  meta: CustomerLedgerExportMeta,
): void {
  const tableRows = rows
    .map(
      (r) => `
    <tr class="${r.kind !== "transaction" ? "summary-row" : ""}">
      <td>${r.date}</td>
      <td>${r.kind === "transaction" || r.kind === "opening" ? r.voucherNo : "—"}</td>
      <td>${r.voucherType}</td>
      <td>${r.particular}</td>
      <td>${r.narration}</td>
      <td class="num">${formatMoneyOrDash(r.debit)}</td>
      <td class="num">${formatMoneyOrDash(r.credit)}</td>
      <td class="num">${balanceLabel(r)}</td>
    </tr>`,
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Customer Ledger — ${summary.customerName}</title>
  <style>
    body { font-family: system-ui, sans-serif; font-size: 11px; padding: 24px; color: #111; }
    h1 { font-size: 16px; margin: 0 0 4px; color: #1A3A96; }
    .meta { color: #555; margin-bottom: 16px; font-size: 10px; line-height: 1.5; }
    table { width: 100%; border-collapse: collapse; }
    th, td { border: 1px solid #ddd; padding: 6px 8px; text-align: left; }
    th { background: #fff; font-size: 10px; text-transform: uppercase; }
    .num { text-align: right; font-variant-numeric: tabular-nums; }
    .summary-row td { font-weight: 600; background: #fafafa; }
  </style>
</head>
<body>
  <h1>${summary.customerName}</h1>
  <p class="meta">
    ${summary.customerCode} · GSTIN: ${summary.gstin} · PAN: ${summary.pan}<br />
    Period: ${meta.dateFrom} to ${meta.dateTo} · Financial Year: ${meta.financialYear}<br />
    Opening: ${formatMoneyWithSide(summary.openingBalance, summary.openingBalanceType)} ·
    Total Debit: ${formatMoney(summary.totalDebit)} ·
    Total Credit: ${formatMoney(summary.totalCredit)} ·
    Closing: ${formatMoneyWithSide(summary.closingBalance, summary.closingBalanceType)}
  </p>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Voucher No.</th>
        <th>Voucher Type</th>
        <th>Particular</th>
        <th>Narration</th>
        <th>Debit (₹)</th>
        <th>Credit (₹)</th>
        <th>Running Balance</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
  </table>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 400);
}
