import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import { demoDateAt, demoDocNo, demoTimestamp } from "@/lib/accounts/demo-date-utils";
import type { CreditNoteLine, CreditNoteRecord } from "./credit-notes-data";

function line(
  id: string,
  productName: string,
  qty: number,
  rate: number,
  taxPct: number,
  creditAmount: number,
): CreditNoteLine {
  const taxable = Math.round((creditAmount / (1 + taxPct / 100)) * 100) / 100;
  const gst = Math.round((creditAmount - taxable) * 100) / 100;
  return {
    id,
    sourceLineId: id,
    productId: null,
    productName,
    sku: `SKU-${id}`,
    hsn: "31021000",
    description: productName,
    invoiceQty: qty + 2,
    unitPrice: rate,
    discountPct: 0,
    taxPct,
    gstAmount: gst,
    lineAmount: Math.round(qty * rate * (1 + taxPct / 100) * 100) / 100,
    returnQty: qty,
    creditAmount,
    reason: "",
  };
}

export function buildCreditNotesSeed(): CreditNoteRecord[] {
  const d1 = demoDateAt(18);
  const d2 = demoDateAt(22);
  const d3 = demoDateAt(8);
  const d4 = demoDateAt(12);
  const d5 = demoDateAt(28);

  const inv1 = demoDocNo("INV", 1);
  const inv2 = demoDocNo("INV", 2);
  const inv4 = demoDocNo("INV", 4);
  const ret1 = "SRET-2026-001";
  const ret2 = "SRET-2026-002";

  const cn1Lines = [line("cnl-1", "Urea 50kg", 5, 1400, 18, 8260)];
  const cn2Lines = [line("cnl-2", "DAP 50kg", 3, 1850, 18, 6552)];
  const cn3Lines = [line("cnl-3", "NPK 10:26:26", 2, 1600, 18, 3776)];
  const cn4Lines = [line("cnl-4", "Hybrid Maize Seed 1kg", 10, 220, 12, 2464)];
  const cn5Lines = [line("cnl-5", "Bio Stimulant", 1, 4500, 18, 5310)];

  return [
    {
      id: 1,
      creditNoteNo: demoDocNo("CN", 1),
      creditNoteDate: d1,
      againstType: "sales_invoice",
      source: "sales_return",
      sourceReturnId: "sret-seed-1",
      sourceReturnNo: ret1,
      sourceInvoiceId: 1,
      sourceInvoiceNo: inv1,
      sourceOrderId: null,
      sourceOrderNo: "SO-2026-0001",
      customerId: 1,
      customerName: "ABC Agro Distributor",
      receivableLedger: "ABC Agro Distributor",
      originalAmount: 150000,
      alreadyAdjustedAmount: 0,
      currentCreditAmount: 8260,
      balanceAfterAdjustment: 141740,
      taxCreditAmount: 1260,
      taxableValue: 7000,
      cgstAmount: 630,
      sgstAmount: 630,
      igstAmount: 0,
      lineItems: cn1Lines,
      reason: "Damaged bags on transit",
      remarks: `Auto-generated from Sales Return ${ret1}`,
      status: "approved",
      activity: [
        {
          at: demoTimestamp(d1, "10:00:00"),
          action: "approved",
          by: ACCOUNTS_CURRENT_USER,
          detail: `Credit note from ${ret1}`,
        },
      ],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      approvedBy: ACCOUNTS_CURRENT_USER,
      approvedAt: demoTimestamp(d1, "10:00:00"),
      createdAt: demoTimestamp(d1, "09:00:00"),
      updatedAt: demoTimestamp(d1, "10:00:00"),
    },
    {
      id: 2,
      creditNoteNo: demoDocNo("CN", 2),
      creditNoteDate: d2,
      againstType: "sales_invoice",
      source: "sales_return",
      sourceReturnId: "sret-seed-2",
      sourceReturnNo: ret2,
      sourceInvoiceId: 2,
      sourceInvoiceNo: inv2,
      sourceOrderId: null,
      sourceOrderNo: "SO-2026-0002",
      customerId: 1,
      customerName: "ABC Agro Distributor",
      receivableLedger: "ABC Agro Distributor",
      originalAmount: 98000,
      alreadyAdjustedAmount: 0,
      currentCreditAmount: 6552,
      balanceAfterAdjustment: 91448,
      taxCreditAmount: 1000,
      taxableValue: 5552,
      cgstAmount: 500,
      sgstAmount: 500,
      igstAmount: 0,
      lineItems: cn2Lines,
      reason: "Customer return — excess stock",
      remarks: `Auto-generated from Sales Return ${ret2}`,
      status: "approved",
      activity: [
        {
          at: demoTimestamp(d2, "11:00:00"),
          action: "approved",
          by: ACCOUNTS_CURRENT_USER,
          detail: `Credit note from ${ret2}`,
        },
      ],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      approvedBy: ACCOUNTS_CURRENT_USER,
      approvedAt: demoTimestamp(d2, "11:00:00"),
      createdAt: demoTimestamp(d2, "10:00:00"),
      updatedAt: demoTimestamp(d2, "11:00:00"),
    },
    {
      id: 3,
      creditNoteNo: demoDocNo("CN", 3),
      creditNoteDate: d3,
      againstType: "sales_invoice",
      source: "payment_discount_scheme",
      schemeName: "Early Payment 5% — ABC Distributor",
      schemeCode: "PAY-EARLY-001",
      discountPercent: 5,
      sourceInvoiceId: 4,
      sourceInvoiceNo: inv4,
      sourceOrderId: null,
      sourceOrderNo: "",
      customerId: 4,
      customerName: "Green Harvest Agro",
      receivableLedger: "Green Harvest Agro",
      originalAmount: 120000,
      alreadyAdjustedAmount: 0,
      currentCreditAmount: 3776,
      balanceAfterAdjustment: 116224,
      taxCreditAmount: 576,
      taxableValue: 3200,
      cgstAmount: 288,
      sgstAmount: 288,
      igstAmount: 0,
      lineItems: cn3Lines,
      reason: "Payment discount scheme",
      remarks: "Payment received within 3 days — 5% discount applied",
      status: "approved",
      schemeSettlementAmount: 3776,
      activity: [
        {
          at: demoTimestamp(d3, "14:00:00"),
          action: "approved",
          by: ACCOUNTS_CURRENT_USER,
          detail: "Payment discount credit note",
        },
      ],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      approvedBy: ACCOUNTS_CURRENT_USER,
      approvedAt: demoTimestamp(d3, "14:00:00"),
      createdAt: demoTimestamp(d3, "13:30:00"),
      updatedAt: demoTimestamp(d3, "14:00:00"),
    },
    {
      id: 4,
      creditNoteNo: demoDocNo("CN", 4),
      creditNoteDate: d4,
      againstType: "sales_invoice",
      source: "payment_discount_scheme",
      schemeName: "ABC Distributor Outstanding Settlement",
      schemeCode: "PAY-001",
      discountPercent: 30,
      sourceInvoiceId: 1,
      sourceInvoiceNo: inv1,
      sourceOrderId: null,
      sourceOrderNo: "",
      customerId: 1,
      customerName: "ABC Agro Distributor",
      receivableLedger: "ABC Agro Distributor",
      originalAmount: 150000,
      alreadyAdjustedAmount: 8260,
      currentCreditAmount: 2464,
      balanceAfterAdjustment: 139276,
      taxCreditAmount: 264,
      taxableValue: 2200,
      cgstAmount: 132,
      sgstAmount: 132,
      igstAmount: 0,
      lineItems: cn4Lines,
      reason: "Payment discount scheme",
      remarks: "Partial collection waiver under PAY-001",
      status: "approved",
      schemeSettlementAmount: 2464,
      activity: [
        {
          at: demoTimestamp(d4, "09:30:00"),
          action: "approved",
          by: ACCOUNTS_CURRENT_USER,
          detail: "Scheme settlement CN",
        },
      ],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      approvedBy: ACCOUNTS_CURRENT_USER,
      approvedAt: demoTimestamp(d4, "09:30:00"),
      createdAt: demoTimestamp(d4, "09:00:00"),
      updatedAt: demoTimestamp(d4, "09:30:00"),
    },
    {
      id: 5,
      creditNoteNo: demoDocNo("CN", 5),
      creditNoteDate: d5,
      againstType: "general",
      source: "manual",
      sourceInvoiceId: null,
      sourceInvoiceNo: "",
      sourceOrderId: null,
      sourceOrderNo: "",
      customerId: 6,
      customerName: "Krishna Retail Store",
      receivableLedger: "Krishna Retail Store",
      originalAmount: 5310,
      alreadyAdjustedAmount: 0,
      currentCreditAmount: 5310,
      balanceAfterAdjustment: 0,
      taxCreditAmount: 810,
      taxableValue: 4500,
      cgstAmount: 405,
      sgstAmount: 405,
      igstAmount: 0,
      lineItems: cn5Lines,
      reason: "Commercial Settlement",
      remarks: "One-time commercial settlement agreed with customer",
      status: "approved",
      activity: [
        {
          at: demoTimestamp(d5, "16:00:00"),
          action: "approved",
          by: ACCOUNTS_CURRENT_USER,
          detail: "Manual credit note posted",
        },
      ],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      approvedBy: ACCOUNTS_CURRENT_USER,
      approvedAt: demoTimestamp(d5, "16:00:00"),
      createdAt: demoTimestamp(d5, "15:00:00"),
      updatedAt: demoTimestamp(d5, "16:00:00"),
    },
    {
      id: 6,
      creditNoteNo: demoDocNo("CN", 6),
      creditNoteDate: demoDateAt(4),
      againstType: "sales_invoice",
      source: "sales_return",
      sourceReturnId: "sret-seed-3",
      sourceReturnNo: "SRET-2026-003",
      sourceInvoiceId: 3,
      sourceInvoiceNo: demoDocNo("INV", 3),
      sourceOrderId: null,
      sourceOrderNo: "SO-2026-0003",
      customerId: 2,
      customerName: "XYZ Traders",
      receivableLedger: "XYZ Traders",
      originalAmount: 88000,
      alreadyAdjustedAmount: 0,
      currentCreditAmount: 4720,
      balanceAfterAdjustment: 83280,
      taxCreditAmount: 720,
      taxableValue: 4000,
      cgstAmount: 360,
      sgstAmount: 360,
      igstAmount: 0,
      lineItems: [line("cnl-6", "DAP 50kg", 2, 1850, 18, 4720)],
      reason: "Quality issue — partial return",
      remarks: "Draft CN awaiting review",
      status: "draft",
      activity: [{ at: demoTimestamp(demoDateAt(4), "11:00:00"), action: "created", by: ACCOUNTS_CURRENT_USER, detail: "Draft saved" }],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      createdAt: demoTimestamp(demoDateAt(4), "11:00:00"),
      updatedAt: demoTimestamp(demoDateAt(4), "11:00:00"),
      branch: "Maharashtra",
    } as CreditNoteRecord & { branch?: string },
    {
      id: 7,
      creditNoteNo: demoDocNo("CN", 7),
      creditNoteDate: demoDateAt(6),
      againstType: "sales_invoice",
      source: "payment_discount_scheme",
      schemeName: "Volume Rebate Q1",
      schemeCode: "VOL-Q1",
      discountPercent: 3,
      sourceInvoiceId: 2,
      sourceInvoiceNo: demoDocNo("INV", 2),
      sourceOrderId: null,
      sourceOrderNo: "",
      customerId: 4,
      customerName: "Green Harvest Agro",
      receivableLedger: "Green Harvest Agro",
      originalAmount: 120000,
      alreadyAdjustedAmount: 0,
      currentCreditAmount: 2950,
      balanceAfterAdjustment: 117050,
      taxCreditAmount: 450,
      taxableValue: 2500,
      cgstAmount: 225,
      sgstAmount: 225,
      igstAmount: 0,
      lineItems: [line("cnl-7", "NPK 10:26:26", 1, 1600, 18, 2950)],
      reason: "Scheme settlement pending approval",
      remarks: "Awaiting finance approval",
      status: "pending_approval",
      activity: [{ at: demoTimestamp(demoDateAt(6), "14:30:00"), action: "submitted", by: ACCOUNTS_CURRENT_USER, detail: "Sent for approval" }],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      createdAt: demoTimestamp(demoDateAt(6), "14:00:00"),
      updatedAt: demoTimestamp(demoDateAt(6), "14:30:00"),
      branch: "Gujarat",
    } as CreditNoteRecord & { branch?: string },
    {
      id: 8,
      creditNoteNo: demoDocNo("CN", 8),
      creditNoteDate: demoDateAt(10),
      againstType: "general",
      source: "manual",
      sourceInvoiceId: null,
      sourceInvoiceNo: "",
      sourceOrderId: null,
      sourceOrderNo: "",
      customerId: 2,
      customerName: "XYZ Traders",
      receivableLedger: "XYZ Traders",
      originalAmount: 1180,
      alreadyAdjustedAmount: 0,
      currentCreditAmount: 1180,
      balanceAfterAdjustment: 0,
      taxCreditAmount: 180,
      taxableValue: 1000,
      cgstAmount: 90,
      sgstAmount: 90,
      igstAmount: 0,
      lineItems: [line("cnl-8", "Rate difference adjustment", 1, 1000, 18, 1180)],
      reason: "Rate Difference",
      remarks: "Cancelled — duplicate entry",
      status: "cancelled",
      activity: [{ at: demoTimestamp(demoDateAt(10), "16:00:00"), action: "cancelled", by: ACCOUNTS_CURRENT_USER, detail: "Duplicate CN voided" }],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      createdAt: demoTimestamp(demoDateAt(10), "15:00:00"),
      updatedAt: demoTimestamp(demoDateAt(10), "16:00:00"),
      branch: "Maharashtra",
    } as CreditNoteRecord & { branch?: string },
    {
      id: 9,
      creditNoteNo: demoDocNo("CN", 9),
      creditNoteDate: demoDateAt(14),
      againstType: "sales_invoice",
      source: "sales_return",
      sourceReturnId: "sret-seed-4",
      sourceReturnNo: "SRET-2026-004",
      sourceInvoiceId: 1,
      sourceInvoiceNo: inv1,
      sourceOrderId: null,
      sourceOrderNo: "SO-2026-0004",
      customerId: 1,
      customerName: "ABC Agro Distributor",
      receivableLedger: "ABC Agro Distributor",
      originalAmount: 150000,
      alreadyAdjustedAmount: 8260,
      currentCreditAmount: 3540,
      balanceAfterAdjustment: 138200,
      taxCreditAmount: 540,
      taxableValue: 3000,
      cgstAmount: 270,
      sgstAmount: 270,
      igstAmount: 0,
      lineItems: [line("cnl-9", "Hybrid Maize Seed 1kg", 8, 220, 12, 3540)],
      reason: "Near-expiry return",
      remarks: "Posted CN from sales return",
      status: "approved",
      activity: [{ at: demoTimestamp(demoDateAt(14), "10:00:00"), action: "approved", by: ACCOUNTS_CURRENT_USER, detail: "Posted" }],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      approvedBy: ACCOUNTS_CURRENT_USER,
      approvedAt: demoTimestamp(demoDateAt(14), "10:00:00"),
      createdAt: demoTimestamp(demoDateAt(14), "09:30:00"),
      updatedAt: demoTimestamp(demoDateAt(14), "10:00:00"),
      branch: "Maharashtra",
    } as CreditNoteRecord & { branch?: string },
    {
      id: 10,
      creditNoteNo: demoDocNo("CN", 10),
      creditNoteDate: demoDateAt(20),
      againstType: "sales_invoice",
      source: "manual",
      sourceInvoiceId: 2,
      sourceInvoiceNo: inv2,
      sourceOrderId: null,
      sourceOrderNo: "",
      customerId: 1,
      customerName: "ABC Agro Distributor",
      receivableLedger: "ABC Agro Distributor",
      originalAmount: 98000,
      alreadyAdjustedAmount: 6552,
      currentCreditAmount: 2124,
      balanceAfterAdjustment: 89324,
      taxCreditAmount: 324,
      taxableValue: 1800,
      cgstAmount: 162,
      sgstAmount: 162,
      igstAmount: 0,
      lineItems: [line("cnl-10", "Commercial discount", 1, 1800, 18, 2124)],
      reason: "Commercial Discount",
      remarks: "Goodwill adjustment",
      status: "approved",
      activity: [{ at: demoTimestamp(demoDateAt(20), "11:00:00"), action: "approved", by: ACCOUNTS_CURRENT_USER, detail: "Manual CN posted" }],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      approvedBy: ACCOUNTS_CURRENT_USER,
      approvedAt: demoTimestamp(demoDateAt(20), "11:00:00"),
      createdAt: demoTimestamp(demoDateAt(20), "10:30:00"),
      updatedAt: demoTimestamp(demoDateAt(20), "11:00:00"),
      branch: "Karnataka",
    } as CreditNoteRecord & { branch?: string },
  ];
}
