import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import { demoDateAt, demoDocNo, demoTimestamp } from "@/lib/accounts/demo-date-utils";
import type { CreditNoteLine, CreditNoteRecord } from "./credit-notes-data";

function line(
  id: string,
  productName: string,
  qty: number,
  rate: number,
  taxPct: number,
  creditAmount: number,
): CreditNoteLine {
  const taxable = Math.round((creditAmount / (1 + taxPct / 100)) * 100) / 100;
  const gst = Math.round((creditAmount - taxable) * 100) / 100;
  return {
    id,
    sourceLineId: id,
    productId: null,
    productName,
    sku: `SKU-${id}`,
    hsn: "31021000",
    description: productName,
    invoiceQty: qty + 2,
    unitPrice: rate,
    discountPct: 0,
    taxPct,
    gstAmount: gst,
    lineAmount: Math.round(qty * rate * (1 + taxPct / 100) * 100) / 100,
    returnQty: qty,
    creditAmount,
    reason: "",
  };
}

export function buildCreditNotesSeed(): CreditNoteRecord[] {
  const d1 = demoDateAt(18);
  const d2 = demoDateAt(22);
  const d3 = demoDateAt(8);
  const d4 = demoDateAt(12);
  const d5 = demoDateAt(28);

  const inv1 = demoDocNo("INV", 1);
  const inv2 = demoDocNo("INV", 2);
  const inv4 = demoDocNo("INV", 4);
  const ret1 = "SRET-2026-001";
  const ret2 = "SRET-2026-002";

  const cn1Lines = [line("cnl-1", "Urea 50kg", 5, 1400, 18, 8260)];
  const cn2Lines = [line("cnl-2", "DAP 50kg", 3, 1850, 18, 6552)];
  const cn3Lines = [line("cnl-3", "NPK 10:26:26", 2, 1600, 18, 3776)];
  const cn4Lines = [line("cnl-4", "Hybrid Maize Seed 1kg", 10, 220, 12, 2464)];
  const cn5Lines = [line("cnl-5", "Bio Stimulant", 1, 4500, 18, 5310)];

  return [
    {
      id: 1,
      creditNoteNo: demoDocNo("CN", 1),
      creditNoteDate: d1,
      againstType: "sales_invoice",
      source: "sales_return",
      sourceReturnId: "sret-seed-1",
      sourceReturnNo: ret1,
      sourceInvoiceId: 1,
      sourceInvoiceNo: inv1,
      sourceOrderId: null,
      sourceOrderNo: "SO-2026-0001",
      customerId: 1,
      customerName: "ABC Agro Distributor",
      receivableLedger: "ABC Agro Distributor",
      originalAmount: 150000,
      alreadyAdjustedAmount: 0,
      currentCreditAmount: 8260,
      balanceAfterAdjustment: 141740,
      taxCreditAmount: 1260,
      taxableValue: 7000,
      cgstAmount: 630,
      sgstAmount: 630,
      igstAmount: 0,
      lineItems: cn1Lines,
      reason: "Damaged bags on transit",
      remarks: `Auto-generated from Sales Return ${ret1}`,
      status: "approved",
      activity: [
        {
          at: demoTimestamp(d1, "10:00:00"),
          action: "approved",
          by: ACCOUNTS_CURRENT_USER,
          detail: `Credit note from ${ret1}`,
        },
      ],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      approvedBy: ACCOUNTS_CURRENT_USER,
      approvedAt: demoTimestamp(d1, "10:00:00"),
      createdAt: demoTimestamp(d1, "09:00:00"),
      updatedAt: demoTimestamp(d1, "10:00:00"),
    },
    {
      id: 2,
      creditNoteNo: demoDocNo("CN", 2),
      creditNoteDate: d2,
      againstType: "sales_invoice",
      source: "sales_return",
      sourceReturnId: "sret-seed-2",
      sourceReturnNo: ret2,
      sourceInvoiceId: 2,
      sourceInvoiceNo: inv2,
      sourceOrderId: null,
      sourceOrderNo: "SO-2026-0002",
      customerId: 1,
      customerName: "ABC Agro Distributor",
      receivableLedger: "ABC Agro Distributor",
      originalAmount: 98000,
      alreadyAdjustedAmount: 0,
      currentCreditAmount: 6552,
      balanceAfterAdjustment: 91448,
      taxCreditAmount: 1000,
      taxableValue: 5552,
      cgstAmount: 500,
      sgstAmount: 500,
      igstAmount: 0,
      lineItems: cn2Lines,
      reason: "Customer return — excess stock",
      remarks: `Auto-generated from Sales Return ${ret2}`,
      status: "approved",
      activity: [
        {
          at: demoTimestamp(d2, "11:00:00"),
          action: "approved",
          by: ACCOUNTS_CURRENT_USER,
          detail: `Credit note from ${ret2}`,
        },
      ],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      approvedBy: ACCOUNTS_CURRENT_USER,
      approvedAt: demoTimestamp(d2, "11:00:00"),
      createdAt: demoTimestamp(d2, "10:00:00"),
      updatedAt: demoTimestamp(d2, "11:00:00"),
    },
    {
      id: 3,
      creditNoteNo: demoDocNo("CN", 3),
      creditNoteDate: d3,
      againstType: "sales_invoice",
      source: "payment_discount_scheme",
      schemeName: "Early Payment 5% — ABC Distributor",
      schemeCode: "PAY-EARLY-001",
      discountPercent: 5,
      sourceInvoiceId: 4,
      sourceInvoiceNo: inv4,
      sourceOrderId: null,
      sourceOrderNo: "",
      customerId: 4,
      customerName: "Green Harvest Agro",
      receivableLedger: "Green Harvest Agro",
      originalAmount: 120000,
      alreadyAdjustedAmount: 0,
      currentCreditAmount: 3776,
      balanceAfterAdjustment: 116224,
      taxCreditAmount: 576,
      taxableValue: 3200,
      cgstAmount: 288,
      sgstAmount: 288,
      igstAmount: 0,
      lineItems: cn3Lines,
      reason: "Payment discount scheme",
      remarks: "Payment received within 3 days — 5% discount applied",
      status: "approved",
      schemeSettlementAmount: 3776,
      activity: [
        {
          at: demoTimestamp(d3, "14:00:00"),
          action: "approved",
          by: ACCOUNTS_CURRENT_USER,
          detail: "Payment discount credit note",
        },
      ],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      approvedBy: ACCOUNTS_CURRENT_USER,
      approvedAt: demoTimestamp(d3, "14:00:00"),
      createdAt: demoTimestamp(d3, "13:30:00"),
      updatedAt: demoTimestamp(d3, "14:00:00"),
    },
    {
      id: 4,
      creditNoteNo: demoDocNo("CN", 4),
      creditNoteDate: d4,
      againstType: "sales_invoice",
      source: "payment_discount_scheme",
      schemeName: "ABC Distributor Outstanding Settlement",
      schemeCode: "PAY-001",
      discountPercent: 30,
      sourceInvoiceId: 1,
      sourceInvoiceNo: inv1,
      sourceOrderId: null,
      sourceOrderNo: "",
      customerId: 1,
      customerName: "ABC Agro Distributor",
      receivableLedger: "ABC Agro Distributor",
      originalAmount: 150000,
      alreadyAdjustedAmount: 8260,
      currentCreditAmount: 2464,
      balanceAfterAdjustment: 139276,
      taxCreditAmount: 264,
      taxableValue: 2200,
      cgstAmount: 132,
      sgstAmount: 132,
      igstAmount: 0,
      lineItems: cn4Lines,
      reason: "Payment discount scheme",
      remarks: "Partial collection waiver under PAY-001",
      status: "approved",
      schemeSettlementAmount: 2464,
      activity: [
        {
          at: demoTimestamp(d4, "09:30:00"),
          action: "approved",
          by: ACCOUNTS_CURRENT_USER,
          detail: "Scheme settlement CN",
        },
      ],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      approvedBy: ACCOUNTS_CURRENT_USER,
      approvedAt: demoTimestamp(d4, "09:30:00"),
      createdAt: demoTimestamp(d4, "09:00:00"),
      updatedAt: demoTimestamp(d4, "09:30:00"),
    },
    {
      id: 5,
      creditNoteNo: demoDocNo("CN", 5),
      creditNoteDate: d5,
      againstType: "general",
      source: "manual",
      sourceInvoiceId: null,
      sourceInvoiceNo: "",
      sourceOrderId: null,
      sourceOrderNo: "",
      customerId: 6,
      customerName: "Krishna Retail Store",
      receivableLedger: "Krishna Retail Store",
      originalAmount: 5310,
      alreadyAdjustedAmount: 0,
      currentCreditAmount: 5310,
      balanceAfterAdjustment: 0,
      taxCreditAmount: 810,
      taxableValue: 4500,
      cgstAmount: 405,
      sgstAmount: 405,
      igstAmount: 0,
      lineItems: cn5Lines,
      reason: "Commercial Settlement",
      remarks: "One-time commercial settlement agreed with customer",
      status: "approved",
      activity: [
        {
          at: demoTimestamp(d5, "16:00:00"),
          action: "approved",
          by: ACCOUNTS_CURRENT_USER,
          detail: "Manual credit note posted",
        },
      ],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      approvedBy: ACCOUNTS_CURRENT_USER,
      approvedAt: demoTimestamp(d5, "16:00:00"),
      createdAt: demoTimestamp(d5, "15:00:00"),
      updatedAt: demoTimestamp(d5, "16:00:00"),
    },
  ];
}
