import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import { formatMoney, formatMoneyOrDash, formatMoneyWithSide } from "@/lib/accounts/money-format";
import type { CashBookDisplayRow, CashBookSummary } from "./cash-book-data";

const COMPANY_NAME = "Dharitri Sutra Agri Solutions Pvt Ltd";
const REPORT_NAME = "Cash Book";

export interface CashBookExportMeta {
  dateFrom: string;
  dateTo: string;
  financialYear: string;
}

function generatedOnLabel(): string {
  return new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function balanceLabel(row: CashBookDisplayRow): string {
  return formatMoneyWithSide(row.runningBalance, row.runningBalanceType);
}

export async function exportCashBookToExcel(
  rows: CashBookDisplayRow[],
  summary: CashBookSummary,
  meta: CashBookExportMeta,
): Promise<void> {
  const XLSX = await import("xlsx");

  const dataRows = rows.map((r) => ({
    Date: r.date,
    "Voucher No.": r.kind === "opening" ? "—" : r.voucherNo,
    "Voucher Type": r.voucherType,
    Particular: r.particular,
    Narration: r.narration,
    "Receipt (₹)": r.receipt || "",
    "Payment (₹)": r.payment || "",
    "Running Balance": balanceLabel(r),
  }));

  const sheet = XLSX.utils.json_to_sheet(dataRows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, sheet, "Cash Book");

  const info = XLSX.utils.aoa_to_sheet([
    ["Company Name", COMPANY_NAME],
    ["Report Name", REPORT_NAME],
    ["Cash Ledger", summary.ledgerName],
    ["Ledger Code", summary.ledgerCode],
    ["Date Range", `${meta.dateFrom} to ${meta.dateTo}`],
    ["Financial Year", meta.financialYear],
    [
      "Opening Cash Balance",
      formatMoneyWithSide(summary.openingBalance, summary.openingBalanceType),
    ],
    ["Total Cash Receipts", summary.totalReceipts],
    ["Total Cash Payments", summary.totalPayments],
    [
      "Closing Cash Balance",
      formatMoneyWithSide(summary.closingBalance, summary.closingBalanceType),
    ],
    ["Generated By", ACCOUNTS_CURRENT_USER],
    ["Generated On", generatedOnLabel()],
  ]);
  XLSX.utils.book_append_sheet(wb, info, "Report Info");

  const safeName = summary.ledgerCode.replace(/[^\w-]+/g, "_");
  const date = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `Cash_Book_${safeName}_${date}.xlsx`);
}

export function exportCashBookToPdf(
  rows: CashBookDisplayRow[],
  summary: CashBookSummary,
  meta: CashBookExportMeta,
): void {
  const tableRows = rows
    .map(
      (r) => `
    <tr class="${r.kind === "opening" ? "summary-row" : ""}">
      <td>${r.date}</td>
      <td>${r.kind === "opening" ? "—" : r.voucherNo}</td>
      <td>${r.voucherType}</td>
      <td>${r.particular}</td>
      <td>${r.narration}</td>
      <td class="num">${formatMoneyOrDash(r.receipt)}</td>
      <td class="num">${formatMoneyOrDash(r.payment)}</td>
      <td class="num">${balanceLabel(r)}</td>
    </tr>`,
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Cash Book — ${summary.ledgerName}</title>
  <style>
    body { font-family: system-ui, sans-serif; font-size: 11px; padding: 24px; color: #111; }
    h1 { font-size: 16px; margin: 0 0 4px; color: #1A3A96; }
    .meta { color: #555; margin-bottom: 16px; font-size: 10px; line-height: 1.5; }
    table { width: 100%; border-collapse: collapse; }
    th, td { border: 1px solid #ddd; padding: 6px 8px; text-align: left; }
    th { background: #f5f5f5; font-size: 10px; text-transform: uppercase; }
    .num { text-align: right; font-variant-numeric: tabular-nums; }
    .summary-row { background: #fafafa; font-weight: 600; }
    .totals { margin-top: 12px; font-size: 11px; }
    .totals p { margin: 4px 0; }
    @media print { body { padding: 12px; } }
  </style>
</head>
<body>
  <h1>${REPORT_NAME}</h1>
  <div class="meta">
    <div><strong>${COMPANY_NAME}</strong></div>
    <div>Cash Ledger: ${summary.ledgerName} (${summary.ledgerCode})</div>
    <div>Period: ${meta.dateFrom} to ${meta.dateTo} · ${meta.financialYear}</div>
    <div>Opening Cash Balance: ${formatMoneyWithSide(summary.openingBalance, summary.openingBalanceType)}</div>
    <div>Generated by ${ACCOUNTS_CURRENT_USER} on ${generatedOnLabel()}</div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Voucher No.</th>
        <th>Voucher Type</th>
        <th>Particular</th>
        <th>Narration</th>
        <th class="num">Receipt</th>
        <th class="num">Payment</th>
        <th class="num">Running Balance</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
  </table>
  <div class="totals">
    <p><strong>Total Receipts:</strong> ${formatMoney(summary.totalReceipts)}</p>
    <p><strong>Total Payments:</strong> ${formatMoney(summary.totalPayments)}</p>
    <p><strong>Closing Cash Balance:</strong> ${formatMoneyWithSide(summary.closingBalance, summary.closingBalanceType)}</p>
  </div>
  <script>window.onload = function() { window.print(); }</script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
}
