import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import { demoDateAt, demoDocNo, demoTimestamp } from "@/lib/accounts/demo-date-utils";
import type { DebitNoteLine, DebitNoteRecord } from "./debit-notes-data";

function line(
  id: string,
  productName: string,
  qty: number,
  rate: number,
  taxPct: number,
  debitAmount: number,
): DebitNoteLine {
  const taxable = Math.round((debitAmount / (1 + taxPct / 100)) * 100) / 100;
  const gst = Math.round((debitAmount - taxable) * 100) / 100;
  return {
    id,
    sourceLineId: id,
    productName,
    invoiceQty: qty + 5,
    uom: "BAG",
    unitPrice: rate,
    discountPct: 0,
    taxPct,
    gstAmount: gst,
    lineAmount: debitAmount,
    returnQty: qty,
    debitAmount,
    lineRemarks: "",
  };
}

export function buildDebitNotesSeed(): DebitNoteRecord[] {
  const d1 = demoDateAt(5);
  const d2 = demoDateAt(9);
  const d3 = demoDateAt(14);
  const d4 = demoDateAt(19);
  const d5 = demoDateAt(26);

  const pi1 = "PUR-2026-001";
  const pi2 = "PUR-2026-002";
  const pi3 = "PUR-2026-003";
  const pi4 = "PUR-2026-004";

  return [
    {
      id: 1,
      debitNoteNo: demoDocNo("DN", 1),
      debitNoteDate: d1,
      againstType: "purchase_invoice",
      source: "purchase_return",
      sourceReturnId: "1",
      sourceReturnNo: "PRET-2026-001",
      sourceInvoiceId: 1,
      sourceInvoiceNo: pi1,
      sourcePoId: 1,
      sourcePoNo: "PO-2026-0001",
      sourceGrnNo: "GRN-001",
      sourceQcNo: "QC-2024-003",
      vendorId: 1,
      vendorName: "Agro Chem Distributors",
      originalAmount: 94400,
      alreadyAdjustedAmount: 0,
      taxableAmount: 1695,
      gstAmount: 305,
      cgstAmount: 152.5,
      sgstAmount: 152.5,
      igstAmount: 0,
      currentDebitAmount: 2000,
      balanceAfterAdjustment: 92400,
      standaloneDebitAmount: 0,
      lineItems: [line("dnl-1", "Chlorpyrifos 20 EC", 2, 850, 18, 2000)],
      reason: "Leakage — partial return",
      remarks: "Auto-generated from Purchase Return PRET-2026-001",
      attachments: [],
      status: "approved",
      activity: [
        {
          at: demoTimestamp(d1, "10:00:00"),
          action: "approved",
          by: ACCOUNTS_CURRENT_USER,
          detail: "Debit note from PRET-2026-001",
        },
      ],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      approvedBy: ACCOUNTS_CURRENT_USER,
      approvedAt: demoTimestamp(d1, "10:00:00"),
      createdAt: demoTimestamp(d1, "09:00:00"),
      updatedAt: demoTimestamp(d1, "10:00:00"),
    },
    {
      id: 2,
      debitNoteNo: demoDocNo("DN", 2),
      debitNoteDate: d2,
      againstType: "purchase_invoice",
      source: "purchase_return",
      sourceReturnId: "2",
      sourceReturnNo: "PRET-2026-002",
      sourceInvoiceId: 2,
      sourceInvoiceNo: pi2,
      sourcePoId: 2,
      sourcePoNo: "PO-2026-0002",
      sourceGrnNo: "GRN-002",
      sourceQcNo: "QC-2024-005",
      vendorId: 2,
      vendorName: "Green Fertilizers Ltd",
      originalAmount: 112100,
      alreadyAdjustedAmount: 0,
      taxableAmount: 3390,
      gstAmount: 610,
      cgstAmount: 305,
      sgstAmount: 305,
      igstAmount: 0,
      currentDebitAmount: 4000,
      balanceAfterAdjustment: 108100,
      standaloneDebitAmount: 0,
      lineItems: [line("dnl-2", "NPK 10:26:26", 2, 1600, 18, 4000)],
      reason: "Short supply — rejected at QC",
      remarks: "Auto-generated from Purchase Return PRET-2026-002",
      attachments: [],
      status: "approved",
      activity: [
        {
          at: demoTimestamp(d2, "11:00:00"),
          action: "approved",
          by: ACCOUNTS_CURRENT_USER,
          detail: "Debit note from PRET-2026-002",
        },
      ],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      approvedBy: ACCOUNTS_CURRENT_USER,
      approvedAt: demoTimestamp(d2, "11:00:00"),
      createdAt: demoTimestamp(d2, "10:00:00"),
      updatedAt: demoTimestamp(d2, "11:00:00"),
    },
    {
      id: 3,
      debitNoteNo: demoDocNo("DN", 3),
      debitNoteDate: d3,
      againstType: "purchase_invoice",
      source: "purchase_return",
      sourceReturnId: "3",
      sourceReturnNo: "PRET-2026-003",
      sourceInvoiceId: 3,
      sourceInvoiceNo: pi3,
      sourcePoId: 3,
      sourcePoNo: "PO-2026-0003",
      sourceGrnNo: "GRN-003",
      sourceQcNo: "QC-2024-007",
      vendorId: 3,
      vendorName: "Bharat Seeds Corp",
      originalAmount: 78500,
      alreadyAdjustedAmount: 0,
      taxableAmount: 1271,
      gstAmount: 229,
      cgstAmount: 114.5,
      sgstAmount: 114.5,
      igstAmount: 0,
      currentDebitAmount: 1500,
      balanceAfterAdjustment: 77000,
      standaloneDebitAmount: 0,
      lineItems: [line("dnl-3", "Hybrid Maize Seed 1kg", 5, 220, 12, 1500)],
      reason: "Damaged packaging",
      remarks: "Auto-generated from Purchase Return PRET-2026-003",
      attachments: [],
      status: "approved",
      activity: [
        {
          at: demoTimestamp(d3, "12:00:00"),
          action: "approved",
          by: ACCOUNTS_CURRENT_USER,
          detail: "Debit note from PRET-2026-003",
        },
      ],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      approvedBy: ACCOUNTS_CURRENT_USER,
      approvedAt: demoTimestamp(d3, "12:00:00"),
      createdAt: demoTimestamp(d3, "11:00:00"),
      updatedAt: demoTimestamp(d3, "12:00:00"),
    },
    {
      id: 4,
      debitNoteNo: demoDocNo("DN", 4),
      debitNoteDate: d4,
      againstType: "purchase_invoice",
      source: "purchase_return",
      sourceReturnId: "4",
      sourceReturnNo: "PRET-2026-004",
      sourceInvoiceId: 4,
      sourceInvoiceNo: pi4,
      sourcePoId: 4,
      sourcePoNo: "PO-2026-0004",
      sourceGrnNo: "GRN-004",
      sourceQcNo: "QC-2024-009",
      vendorId: 4,
      vendorName: "Krishna Inputs Pvt Ltd",
      originalAmount: 95600,
      alreadyAdjustedAmount: 0,
      taxableAmount: 2542,
      gstAmount: 458,
      cgstAmount: 229,
      sgstAmount: 229,
      igstAmount: 0,
      currentDebitAmount: 3000,
      balanceAfterAdjustment: 92600,
      standaloneDebitAmount: 0,
      lineItems: [line("dnl-4", "Bio Stimulant - Humic Acid", 3, 900, 18, 3000)],
      reason: "Quality rejection at warehouse",
      remarks: "Auto-generated from Purchase Return PRET-2026-004",
      attachments: [],
      status: "approved",
      activity: [
        {
          at: demoTimestamp(d4, "15:00:00"),
          action: "approved",
          by: ACCOUNTS_CURRENT_USER,
          detail: "Debit note from PRET-2026-004",
        },
      ],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      approvedBy: ACCOUNTS_CURRENT_USER,
      approvedAt: demoTimestamp(d4, "15:00:00"),
      createdAt: demoTimestamp(d4, "14:00:00"),
      updatedAt: demoTimestamp(d4, "15:00:00"),
    },
    {
      id: 5,
      debitNoteNo: demoDocNo("DN", 5),
      debitNoteDate: d5,
      againstType: "purchase_invoice",
      source: "manual",
      sourceInvoiceId: 2,
      sourceInvoiceNo: pi2,
      sourcePoId: 2,
      sourcePoNo: "PO-2026-0002",
      sourceGrnNo: "GRN-002",
      sourceQcNo: "",
      vendorId: 2,
      vendorName: "Green Fertilizers Ltd",
      originalAmount: 112100,
      alreadyAdjustedAmount: 4000,
      taxableAmount: 4237,
      gstAmount: 763,
      cgstAmount: 381.5,
      sgstAmount: 381.5,
      igstAmount: 0,
      currentDebitAmount: 5000,
      balanceAfterAdjustment: 103100,
      standaloneDebitAmount: 0,
      lineItems: [line("dnl-5", "Pesticide - Chlorpyrifos 20EC", 4, 850, 18, 5000)],
      reason: "Commercial Settlement",
      remarks: "Manual debit note — rate difference settlement with supplier",
      attachments: [],
      status: "approved",
      activity: [
        {
          at: demoTimestamp(d5, "10:00:00"),
          action: "approved",
          by: ACCOUNTS_CURRENT_USER,
          detail: "Manual debit note posted",
        },
      ],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      approvedBy: ACCOUNTS_CURRENT_USER,
      approvedAt: demoTimestamp(d5, "10:00:00"),
      createdAt: demoTimestamp(d5, "09:00:00"),
      updatedAt: demoTimestamp(d5, "10:00:00"),
      branch: "Maharashtra",
    } as DebitNoteRecord & { branch?: string },
    {
      id: 6,
      debitNoteNo: demoDocNo("DN", 6),
      debitNoteDate: demoDateAt(3),
      againstType: "purchase_invoice",
      source: "purchase_return",
      sourceReturnId: "5",
      sourceReturnNo: "PRET-2026-005",
      sourceInvoiceId: 1,
      sourceInvoiceNo: pi1,
      sourcePoId: 1,
      sourcePoNo: "PO-2026-0005",
      sourceGrnNo: "GRN-005",
      sourceQcNo: "QC-2024-011",
      vendorId: 1,
      vendorName: "Green Seeds Pvt. Ltd.",
      originalAmount: 94400,
      alreadyAdjustedAmount: 0,
      taxableAmount: 847,
      gstAmount: 153,
      cgstAmount: 76.5,
      sgstAmount: 76.5,
      igstAmount: 0,
      currentDebitAmount: 1000,
      balanceAfterAdjustment: 93400,
      standaloneDebitAmount: 0,
      lineItems: [line("dnl-6", "Urea 50kg", 1, 850, 18, 1000)],
      reason: "Draft — pending QC confirmation",
      remarks: "Draft debit note",
      attachments: [],
      status: "draft",
      activity: [{ at: demoTimestamp(demoDateAt(3), "09:00:00"), action: "created", by: ACCOUNTS_CURRENT_USER, detail: "Draft saved" }],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      createdAt: demoTimestamp(demoDateAt(3), "09:00:00"),
      updatedAt: demoTimestamp(demoDateAt(3), "09:00:00"),
      branch: "Gujarat",
    } as DebitNoteRecord & { branch?: string },
    {
      id: 7,
      debitNoteNo: demoDocNo("DN", 7),
      debitNoteDate: demoDateAt(11),
      againstType: "purchase_invoice",
      source: "manual",
      sourceInvoiceId: 3,
      sourceInvoiceNo: pi3,
      sourcePoId: 3,
      sourcePoNo: "PO-2026-0006",
      sourceGrnNo: "GRN-006",
      sourceQcNo: "",
      vendorId: 2,
      vendorName: "Bharat Fertilizers",
      originalAmount: 78500,
      alreadyAdjustedAmount: 1500,
      taxableAmount: 2119,
      gstAmount: 381,
      cgstAmount: 190.5,
      sgstAmount: 190.5,
      igstAmount: 0,
      currentDebitAmount: 2500,
      balanceAfterAdjustment: 74500,
      standaloneDebitAmount: 0,
      lineItems: [line("dnl-7", "Rate difference", 1, 2119, 18, 2500)],
      reason: "Rate Difference",
      remarks: "Pending finance approval",
      attachments: [],
      status: "pending_approval",
      activity: [{ at: demoTimestamp(demoDateAt(11), "15:00:00"), action: "submitted", by: ACCOUNTS_CURRENT_USER, detail: "Submitted for approval" }],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      createdAt: demoTimestamp(demoDateAt(11), "14:30:00"),
      updatedAt: demoTimestamp(demoDateAt(11), "15:00:00"),
      branch: "Maharashtra",
    } as DebitNoteRecord & { branch?: string },
    {
      id: 8,
      debitNoteNo: demoDocNo("DN", 8),
      debitNoteDate: demoDateAt(15),
      againstType: "purchase_invoice",
      source: "purchase_return",
      sourceReturnId: "6",
      sourceReturnNo: "PRET-2026-006",
      sourceInvoiceId: 2,
      sourceInvoiceNo: pi2,
      sourcePoId: 2,
      sourcePoNo: "PO-2026-0007",
      sourceGrnNo: "GRN-007",
      sourceQcNo: "QC-2024-012",
      vendorId: 2,
      vendorName: "Green Fertilizers Ltd",
      originalAmount: 112100,
      alreadyAdjustedAmount: 4000,
      taxableAmount: 847,
      gstAmount: 153,
      cgstAmount: 76.5,
      sgstAmount: 76.5,
      igstAmount: 0,
      currentDebitAmount: 1000,
      balanceAfterAdjustment: 107100,
      standaloneDebitAmount: 0,
      lineItems: [line("dnl-8", "Damaged bags", 1, 847, 18, 1000)],
      reason: "Cancelled return",
      remarks: "Voided — supplier dispute resolved",
      attachments: [],
      status: "cancelled",
      activity: [{ at: demoTimestamp(demoDateAt(15), "12:00:00"), action: "cancelled", by: ACCOUNTS_CURRENT_USER, detail: "Cancelled" }],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      createdAt: demoTimestamp(demoDateAt(15), "11:00:00"),
      updatedAt: demoTimestamp(demoDateAt(15), "12:00:00"),
      branch: "Karnataka",
    } as DebitNoteRecord & { branch?: string },
    {
      id: 9,
      debitNoteNo: demoDocNo("DN", 9),
      debitNoteDate: demoDateAt(21),
      againstType: "purchase_invoice",
      source: "purchase_return",
      sourceReturnId: "7",
      sourceReturnNo: "PRET-2026-007",
      sourceInvoiceId: 4,
      sourceInvoiceNo: pi4,
      sourcePoId: 4,
      sourcePoNo: "PO-2026-0008",
      sourceGrnNo: "GRN-008",
      sourceQcNo: "QC-2024-013",
      vendorId: 4,
      vendorName: "Krishna Inputs Pvt Ltd",
      originalAmount: 95600,
      alreadyAdjustedAmount: 3000,
      taxableAmount: 1695,
      gstAmount: 305,
      cgstAmount: 152.5,
      sgstAmount: 152.5,
      igstAmount: 0,
      currentDebitAmount: 2000,
      balanceAfterAdjustment: 90600,
      standaloneDebitAmount: 0,
      lineItems: [line("dnl-9", "Chlorpyrifos 20 EC", 2, 850, 18, 2000)],
      reason: "Short supply",
      remarks: "Posted debit note",
      attachments: [],
      status: "approved",
      activity: [{ at: demoTimestamp(demoDateAt(21), "10:00:00"), action: "approved", by: ACCOUNTS_CURRENT_USER, detail: "Posted" }],
      createdBy: ACCOUNTS_CURRENT_USER,
      updatedBy: ACCOUNTS_CURRENT_USER,
      approvedBy: ACCOUNTS_CURRENT_USER,
      approvedAt: demoTimestamp(demoDateAt(21), "10:00:00"),
      createdAt: demoTimestamp(demoDateAt(21), "09:30:00"),
      updatedAt: demoTimestamp(demoDateAt(21), "10:00:00"),
      branch: "Maharashtra",
    } as DebitNoteRecord & { branch?: string },
  ];
}
