import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import type { CoaLedgerListingRow, CoaListingRow } from "./coa-listing-data";
import type { CoaLedgerDetailRow } from "./coa-demo-accounting";
import type { ChartOfAccount } from "../../data";
import { formatBalanceAmount, formatMoney, balanceSideLabel } from "@/lib/accounts/money-format";
import { resolveDrCrColumnSide } from "@/lib/accounts/running-balance";
import { isoToDisplayDate } from "@/lib/accounts/date-display";

const COMPANY_NAME = "Dharitri Sutra Agri Solutions Pvt Ltd";
const REPORT_NAME = "Chart of Accounts";

export interface CoaExportMeta {
  dateFrom: string;
  dateTo: string;
}

function generatedOnLabel(): string {
  return new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function formatBalance(amount: number, side: "Debit" | "Credit"): string {
  if (amount <= 0) return "—";
  return `${amount.toLocaleString("en-IN")} ${side === "Debit" ? "Dr" : "Cr"}`;
}

export interface CoaLedgerListingExportMeta {
  groupName: string;
}

export async function exportCoaLedgerListingToExcel(
  rows: CoaLedgerListingRow[],
  meta: CoaLedgerListingExportMeta,
): Promise<void> {
  const XLSX = await import("xlsx");

  const dataRows = rows.map((r) => ({
    "Ledger Name": r.ledger.accountName,
    "Ledger Code": r.ledger.accountCode,
    "Parent Group": r.parentGroupName,
    Source: r.source,
    "Opening Balance": formatBalance(r.openingAmount, r.openingSide),
    "Current Balance": formatBalance(r.currentAmount, r.currentSide),
    Status: r.ledger.status === "active" ? "Active" : "Inactive",
  }));

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(dataRows), "Ledgers");

  const info = XLSX.utils.aoa_to_sheet([
    ["Company Name", COMPANY_NAME],
    ["Report Name", "Chart of Accounts — Ledger Listing"],
    ["Accounting Group", meta.groupName],
    ["Generated By", ACCOUNTS_CURRENT_USER],
    ["Generated On", generatedOnLabel()],
  ]);
  XLSX.utils.book_append_sheet(wb, info, "Report Info");

  const safeGroup = meta.groupName.replace(/[^\w]+/g, "_").slice(0, 40);
  const date = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `COA_Ledgers_${safeGroup}_${date}.xlsx`);
}

export function exportCoaLedgerListingToPdf(
  rows: CoaLedgerListingRow[],
  meta: CoaLedgerListingExportMeta,
): void {
  const tableRows = rows
    .map(
      (r) => `
    <tr>
      <td>${r.ledger.accountName}</td>
      <td class="mono">${r.ledger.accountCode}</td>
      <td>${r.parentGroupName || "—"}</td>
      <td>${r.source}</td>
      <td class="num">${formatBalance(r.openingAmount, r.openingSide)}</td>
      <td class="num">${formatBalance(r.currentAmount, r.currentSide)}</td>
      <td>${r.ledger.status === "active" ? "Active" : "Inactive"}</td>
    </tr>`,
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Ledger Listing — ${meta.groupName}</title>
  <style>
    @media print { @page { margin: 16mm; } }
    body { font-family: system-ui, sans-serif; font-size: 11px; padding: 24px; color: #111; }
    .header { display: flex; align-items: flex-start; gap: 12px; margin-bottom: 16px; }
    .logo { width: 40px; height: 40px; border-radius: 10px; background: linear-gradient(135deg, #F47920, #D96A10); color: #fff; font-weight: 800; font-size: 14px; display: flex; align-items: center; justify-content: center; }
    h1 { font-size: 16px; margin: 0 0 2px; color: #1A3A96; }
    .company { font-size: 12px; font-weight: 600; margin: 0 0 4px; }
    .meta { color: #555; font-size: 10px; line-height: 1.5; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th, td { border: 1px solid #ddd; padding: 5px 7px; text-align: left; }
    th { background: #f5f5f5; font-size: 9px; text-transform: uppercase; }
    .num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
    .mono { font-family: monospace; font-size: 10px; color: #B85508; }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">DS</div>
    <div>
      <p class="company">${COMPANY_NAME}</p>
      <h1>Ledger Listing — ${meta.groupName}</h1>
      <p class="meta">
        Generated By: ${ACCOUNTS_CURRENT_USER} · Generated On: ${generatedOnLabel()}
      </p>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Ledger Name</th>
        <th>Ledger Code</th>
        <th>Parent Group</th>
        <th>Source</th>
        <th>Opening Balance</th>
        <th>Current Balance</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
  </table>
  <script>window.onload = function() { window.print(); }</script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
}

export async function exportCoaListingToExcel(
  rows: CoaListingRow[],
  meta: CoaExportMeta,
): Promise<void> {
  const XLSX = await import("xlsx");

  const dataRows = rows.map((r) => ({
    "Ledger Code": r.node.accountCode,
    "Ledger Name": r.node.accountName,
    "Opening Balance": formatBalance(r.openingAmount, r.openingSide),
    "Debit (₹)": r.periodDebit || "",
    "Credit (₹)": r.periodCredit || "",
    "Closing Balance": formatBalance(r.closingAmount, r.closingSide),
  }));

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(dataRows), "Chart of Accounts");

  const info = XLSX.utils.aoa_to_sheet([
    ["Company Name", COMPANY_NAME],
    ["Report Name", REPORT_NAME],
    ["Date Range", `${meta.dateFrom} to ${meta.dateTo}`],
    ["Generated By", ACCOUNTS_CURRENT_USER],
    ["Generated On", generatedOnLabel()],
  ]);
  XLSX.utils.book_append_sheet(wb, info, "Report Info");

  const date = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `Chart_of_Accounts_${date}.xlsx`);
}

export function exportCoaListingToPdf(rows: CoaListingRow[], meta: CoaExportMeta): void {
  const tableRows = rows
    .map(
      (r) => `
    <tr>
      <td class="mono">${r.node.accountCode}</td>
      <td>${r.node.accountName}</td>
      <td class="num">${formatBalance(r.openingAmount, r.openingSide)}</td>
      <td class="num">${r.periodDebit > 0 ? r.periodDebit.toLocaleString("en-IN") : "—"}</td>
      <td class="num">${r.periodCredit > 0 ? r.periodCredit.toLocaleString("en-IN") : "—"}</td>
      <td class="num">${formatBalance(r.closingAmount, r.closingSide)}</td>
    </tr>`,
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${REPORT_NAME}</title>
  <style>
    @media print { @page { margin: 16mm; } }
    body { font-family: system-ui, sans-serif; font-size: 11px; padding: 24px; color: #111; }
    .header { display: flex; align-items: flex-start; gap: 12px; margin-bottom: 16px; }
    .logo { width: 40px; height: 40px; border-radius: 10px; background: linear-gradient(135deg, #F47920, #D96A10); color: #fff; font-weight: 800; font-size: 14px; display: flex; align-items: center; justify-content: center; }
    h1 { font-size: 16px; margin: 0 0 2px; color: #1A3A96; }
    .company { font-size: 12px; font-weight: 600; margin: 0 0 4px; }
    .meta { color: #555; font-size: 10px; line-height: 1.5; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th, td { border: 1px solid #ddd; padding: 5px 7px; text-align: left; }
    th { background: #f5f5f5; font-size: 9px; text-transform: uppercase; }
    .num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
    .mono { font-family: monospace; font-size: 10px; color: #B85508; }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">DS</div>
    <div>
      <p class="company">${COMPANY_NAME}</p>
      <h1>${REPORT_NAME}</h1>
      <p class="meta">
        Date Range: ${meta.dateFrom} to ${meta.dateTo}<br />
        Generated By: ${ACCOUNTS_CURRENT_USER} · Generated On: ${generatedOnLabel()}
      </p>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Ledger Code</th>
        <th>Ledger Name</th>
        <th>Opening Balance</th>
        <th>Debit (₹)</th>
        <th>Credit (₹)</th>
        <th>Closing Balance</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
  </table>
  <script>window.onload = function() { window.print(); }</script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
}

export interface CoaLedgerExportMeta {
  ledger: ChartOfAccount;
  parentGroup: string;
  dateFrom: string;
  dateTo: string;
  openingAmount: number;
  openingSide: "Debit" | "Credit";
  closingAmount: number;
  closingSide: "Debit" | "Credit";
}

function formatLedgerRowDate(iso: string): string {
  return iso ? isoToDisplayDate(iso) : "—";
}

export async function exportCoaLedgerStatementToExcel(
  rows: CoaLedgerDetailRow[],
  meta: CoaLedgerExportMeta,
): Promise<void> {
  const XLSX = await import("xlsx");

  const dataRows = rows.map((r) => ({
    Date: formatLedgerRowDate(r.date),
    "Voucher Type": r.voucherType,
    "Voucher No.": r.voucherNo,
    Particulars: r.isOpeningRow ? "Opening Balance" : r.partyName || r.narration || "—",
    "Debit (₹)": r.debit || "",
    "Credit (₹)": r.credit || "",
    Balance: r.runningBalance > 0 ? formatMoney(r.runningBalance) : "—",
    "Dr/Cr":
      r.runningBalance > 0
        ? balanceSideLabel(
            resolveDrCrColumnSide({
              debit: r.debit,
              credit: r.credit,
              runningBalanceType: r.runningBalanceType,
              isBalanceRow: Boolean(r.isOpeningRow),
            }),
          )
        : "—",
    Narration: r.narration || "—",
  }));

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(dataRows), "Ledger Statement");

  const info = XLSX.utils.aoa_to_sheet([
    ["Company Name", COMPANY_NAME],
    ["Report Name", "Ledger Statement"],
    ["Ledger Name", meta.ledger.accountName],
    ["Ledger Code", meta.ledger.accountCode],
    ["Parent Group", meta.parentGroup],
    ["Date Range", `${meta.dateFrom} to ${meta.dateTo}`],
    ["Opening Balance", formatBalanceAmount(meta.openingAmount, meta.openingSide)],
    ["Closing Balance", formatBalanceAmount(meta.closingAmount, meta.closingSide)],
    ["Generated By", ACCOUNTS_CURRENT_USER],
    ["Generated On", generatedOnLabel()],
  ]);
  XLSX.utils.book_append_sheet(wb, info, "Report Info");

  const safeName = meta.ledger.accountName.replace(/[^\w]+/g, "_").slice(0, 40);
  const date = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `Ledger_${safeName}_${date}.xlsx`);
}

export function exportCoaLedgerStatementToPdf(
  rows: CoaLedgerDetailRow[],
  meta: CoaLedgerExportMeta,
): void {
  const tableRows = rows
    .map(
      (r) => `
    <tr>
      <td>${formatLedgerRowDate(r.date)}</td>
      <td>${r.voucherType}</td>
      <td class="mono">${r.voucherNo}</td>
      <td>${r.isOpeningRow ? "Opening Balance" : r.partyName || r.narration || "—"}</td>
      <td class="num">${r.debit > 0 ? formatMoney(r.debit) : "—"}</td>
      <td class="num">${r.credit > 0 ? formatMoney(r.credit) : "—"}</td>
      <td class="num">${r.runningBalance > 0 ? formatMoney(r.runningBalance) : "—"}</td>
      <td class="num">${
        r.runningBalance > 0
          ? balanceSideLabel(
              resolveDrCrColumnSide({
                debit: r.debit,
                credit: r.credit,
                runningBalanceType: r.runningBalanceType,
                isBalanceRow: Boolean(r.isOpeningRow),
              }),
            )
          : "—"
      }</td>
      <td>${r.narration || "—"}</td>
    </tr>`,
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Ledger Statement — ${meta.ledger.accountName}</title>
  <style>
    @media print { @page { margin: 16mm; } }
    body { font-family: system-ui, sans-serif; font-size: 11px; padding: 24px; color: #111; }
    .header { margin-bottom: 16px; }
    h1 { font-size: 16px; margin: 0 0 8px; color: #1A3A96; }
    .meta { color: #555; font-size: 10px; line-height: 1.6; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th, td { border: 1px solid #ddd; padding: 5px 7px; text-align: left; }
    th { background: #f5f5f5; font-size: 9px; text-transform: uppercase; }
    .num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
    .mono { font-family: monospace; font-size: 10px; color: #B85508; }
  </style>
</head>
<body>
  <div class="header">
    <p class="company">${COMPANY_NAME}</p>
    <h1>Ledger Statement — ${meta.ledger.accountName}</h1>
    <p class="meta">
      Ledger Code: ${meta.ledger.accountCode}<br />
      Parent Group: ${meta.parentGroup}<br />
      Date Range: ${meta.dateFrom} to ${meta.dateTo}<br />
      Opening Balance: ${formatBalanceAmount(meta.openingAmount, meta.openingSide)}<br />
      Closing Balance: ${formatBalanceAmount(meta.closingAmount, meta.closingSide)}<br />
      Generated By: ${ACCOUNTS_CURRENT_USER} · ${generatedOnLabel()}
    </p>
  </div>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Voucher Type</th>
        <th>Voucher No.</th>
        <th>Particulars</th>
        <th>Debit</th>
        <th>Credit</th>
        <th>Balance</th>
        <th>Dr/Cr</th>
        <th>Narration</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
  </table>
  <script>window.onload = function() { window.print(); }</script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
}
