import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import { formatMoney, formatMoneyNumber } from "@/lib/accounts/money-format";
import type { PandLExportRow, PandLStatement } from "./pl-data";

const COMPANY_NAME = "Dharitri Sutra Agri Solutions Pvt Ltd";
const REPORT_NAME = "Profit & Loss";

export interface PandLExportMeta {
  dateFrom: string;
  dateTo: string;
  financialYear: string;
}

function generatedOnLabel(): string {
  return new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function formatExportAmount(amount: number | null): string {
  if (amount == null) return "";
  if (amount < 0) return `(${formatMoney(Math.abs(amount))})`;
  return formatMoney(amount);
}

function indentParticular(label: string, indent: number): string {
  return `${"  ".repeat(indent)}${label}`;
}

function metaRows(meta: PandLExportMeta) {
  return [
    ["Company Name", COMPANY_NAME],
    ["Report Name", REPORT_NAME],
    ["Date Range", `${meta.dateFrom} to ${meta.dateTo}`],
    ["Financial Year", meta.financialYear],
    ["Generated By", ACCOUNTS_CURRENT_USER],
    ["Generated On", generatedOnLabel()],
  ];
}

export async function exportPandLToExcel(
  rows: PandLExportRow[],
  meta: PandLExportMeta,
  statement: PandLStatement,
): Promise<void> {
  const XLSX = await import("xlsx");

  const dataRows = rows.map((r) => ({
    Particular: indentParticular(r.particular, r.indent),
    "Amount (₹)": r.amount == null ? "" : r.amount,
  }));

  const sheet = XLSX.utils.json_to_sheet(dataRows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, sheet, "Profit and Loss");

  const info = XLSX.utils.aoa_to_sheet(metaRows(meta));
  XLSX.utils.book_append_sheet(wb, info, "Report Info");

  const summary = XLSX.utils.aoa_to_sheet([
    ["Total Income", statement.totalIncome],
    ["Total Expenses", statement.totalExpenses],
    [
      statement.netProfit >= 0 ? "Net Profit" : "Net Loss",
      Math.abs(statement.netProfit),
    ],
  ]);
  XLSX.utils.book_append_sheet(wb, summary, "Summary");

  const date = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `Profit_and_Loss_${date}.xlsx`);
}

export function exportPandLToPdf(
  rows: PandLExportRow[],
  meta: PandLExportMeta,
  statement: PandLStatement,
): void {
  const tableRows = rows
    .map((r) => {
      const rowClass =
        r.rowType === "section"
          ? "section"
          : r.rowType === "total"
            ? "total"
            : r.rowType === "net"
              ? "net"
              : r.rowType === "line"
                ? "line"
                : "";
      const label = indentParticular(r.particular, r.indent);
      const amount = formatExportAmount(r.amount);
      return `<tr class="${rowClass}"><td>${label}</td><td class="num">${amount}</td></tr>`;
    })
    .join("");

  const netLabel = statement.netProfit >= 0 ? "Net Profit" : "Net Loss";

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${REPORT_NAME}</title>
  <style>
    @media print { @page { margin: 16mm; } }
    body { font-family: system-ui, sans-serif; font-size: 11px; padding: 24px; color: #111; }
    .header { display: flex; align-items: flex-start; gap: 12px; margin-bottom: 16px; }
    .logo { width: 40px; height: 40px; border-radius: 10px; background: linear-gradient(135deg, #F47920, #D96A10); color: #fff; font-weight: 800; font-size: 14px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
    h1 { font-size: 16px; margin: 0 0 2px; color: #1A3A96; }
    .company { font-size: 12px; font-weight: 600; margin: 0 0 4px; }
    .meta { color: #555; font-size: 10px; line-height: 1.5; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th, td { border: 1px solid #ddd; padding: 6px 8px; text-align: left; }
    th { background: #f5f5f5; font-size: 10px; text-transform: uppercase; }
    .num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
    tr.section td { font-weight: 700; background: #f8fafc; text-transform: uppercase; font-size: 10px; letter-spacing: 0.04em; color: #1A3A96; }
    tr.total td { font-weight: 600; border-top: 2px solid #ccc; }
    tr.net td { font-weight: 700; background: #FFF3E8; border-top: 2px solid #D96A10; color: #B85508; }
    .footer-meta { margin-top: 16px; font-size: 9px; color: #666; }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">DS</div>
    <div>
      <p class="company">${COMPANY_NAME}</p>
      <h1>${REPORT_NAME}</h1>
      <p class="meta">
        Date Range: ${meta.dateFrom} to ${meta.dateTo}<br />
        Financial Year: ${meta.financialYear}<br />
        Generated By: ${ACCOUNTS_CURRENT_USER} · Generated On: ${generatedOnLabel()}
      </p>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Particular</th>
        <th class="num">Amount</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
  </table>
  <p class="footer-meta">${netLabel}: ₹ ${formatMoneyNumber(Math.abs(statement.netProfit))}</p>
  <script>window.onload = () => window.print();</script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
}
