import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import { formatMoney, formatMoneyNumber } from "@/lib/accounts/money-format";
import type { TdsSummaryExportRow, TdsSummaryTotals } from "./tds-summary-data";

const COMPANY_NAME = "Dharitri Sutra Agri Solutions Pvt Ltd";
const REPORT_NAME = "TDS Summary";

export interface TdsSummaryExportMeta {
  dateFrom: string;
  dateTo: string;
  financialYear: string;
  partyType: string;
  tdsSection: string;
  search: string;
}

function generatedOnLabel(): string {
  return new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function formatExportAmount(amount: number | null): string {
  if (amount == null) return "";
  return formatMoney(amount);
}

function metaRows(meta: TdsSummaryExportMeta) {
  return [
    ["Company Name", COMPANY_NAME],
    ["Report Name", REPORT_NAME],
    ["Date Range", `${meta.dateFrom} to ${meta.dateTo}`],
    ["Financial Year", meta.financialYear],
    ["Party Type", meta.partyType],
    ["TDS Section", meta.tdsSection],
    ["Search", meta.search || "—"],
    ["Generated By", ACCOUNTS_CURRENT_USER],
    ["Generated On", generatedOnLabel()],
  ];
}

export async function exportTdsSummaryToExcel(
  rows: TdsSummaryExportRow[],
  meta: TdsSummaryExportMeta,
  totals: TdsSummaryTotals,
): Promise<void> {
  const XLSX = await import("xlsx");

  const dataRows = rows
    .filter((r) => r.rowType !== "total")
    .map((r) => ({
      "Party Name": r.partyName,
      "Party Type": r.partyType,
      PAN: r.pan,
      "TDS Section": r.tdsSection,
      "Gross Amount (₹)": r.grossAmount ?? "",
      "TDS Rate": r.tdsRate,
      "TDS Amount (₹)": r.tdsAmount ?? "",
      "Net Payable (₹)": r.netPayable ?? "",
    }));

  const sheet = XLSX.utils.json_to_sheet(dataRows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, sheet, "TDS Summary");

  const info = XLSX.utils.aoa_to_sheet(metaRows(meta));
  XLSX.utils.book_append_sheet(wb, info, "Report Info");

  const summary = XLSX.utils.aoa_to_sheet([
    ["Total Gross Amount", totals.totalGross],
    ["Total TDS Amount", totals.totalTds],
    ["Total Net Payable", totals.totalNet],
  ]);
  XLSX.utils.book_append_sheet(wb, summary, "Totals");

  const date = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `TDS_Summary_${date}.xlsx`);
}

export function exportTdsSummaryToPdf(
  rows: TdsSummaryExportRow[],
  meta: TdsSummaryExportMeta,
  totals: TdsSummaryTotals,
): void {
  const dataRows = rows.filter((r) => r.rowType !== "total");
  const tableRows = dataRows
    .map((r) => {
      const rowClass = r.rowType === "section" ? "section" : "line";
      return `<tr class="${rowClass}">
        <td>${r.partyName}</td>
        <td>${r.partyType}</td>
        <td class="mono">${r.pan}</td>
        <td class="mono">${r.tdsSection}</td>
        <td class="num">${formatExportAmount(r.grossAmount)}</td>
        <td class="num">${r.tdsRate}</td>
        <td class="num">${formatExportAmount(r.tdsAmount)}</td>
        <td class="num">${formatExportAmount(r.netPayable)}</td>
      </tr>`;
    })
    .join("");

  const totalRow = `<tr class="total">
    <td colspan="4"><strong>Totals</strong></td>
    <td class="num"><strong>${formatExportAmount(totals.totalGross)}</strong></td>
    <td></td>
    <td class="num"><strong>${formatExportAmount(totals.totalTds)}</strong></td>
    <td class="num"><strong>${formatExportAmount(totals.totalNet)}</strong></td>
  </tr>`;

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${REPORT_NAME}</title>
  <style>
    @media print { @page { margin: 12mm; } }
    body { font-family: system-ui, sans-serif; font-size: 10px; padding: 20px; color: #111; }
    .header { display: flex; align-items: flex-start; gap: 12px; margin-bottom: 14px; }
    .logo { width: 36px; height: 36px; border-radius: 8px; background: linear-gradient(135deg, #F47920, #D96A10); color: #fff; font-weight: 800; font-size: 13px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
    h1 { font-size: 15px; margin: 0 0 2px; color: #1A3A96; }
    .company { font-size: 11px; font-weight: 600; margin: 0 0 4px; }
    .meta { color: #555; font-size: 9px; line-height: 1.5; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    th, td { border: 1px solid #ddd; padding: 5px 6px; text-align: left; }
    th { background: #fff; font-size: 9px; text-transform: uppercase; font-weight: 700; }
    .num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
    .mono { font-family: ui-monospace, monospace; font-size: 9px; }
    tr.section td { font-weight: 700; background: #f8fafc; text-transform: uppercase; font-size: 9px; letter-spacing: 0.04em; color: #1A3A96; }
    tr.total td { font-weight: 700; background: #f0f0f0; border-top: 2px solid #ccc; }
    .footer-meta { margin-top: 14px; font-size: 9px; color: #666; }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">DS</div>
    <div>
      <p class="company">${COMPANY_NAME}</p>
      <h1>${REPORT_NAME}</h1>
      <p class="meta">
        Date Range: ${meta.dateFrom} to ${meta.dateTo}<br />
        Financial Year: ${meta.financialYear}<br />
        Party Type: ${meta.partyType} · TDS Section: ${meta.tdsSection}<br />
        Generated By: ${ACCOUNTS_CURRENT_USER} · Generated On: ${generatedOnLabel()}
      </p>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Party Name</th>
        <th>Party Type</th>
        <th>PAN</th>
        <th>TDS Section</th>
        <th class="num">Gross Amount</th>
        <th class="num">TDS Rate</th>
        <th class="num">TDS Amount</th>
        <th class="num">Net Payable</th>
      </tr>
    </thead>
    <tbody>${tableRows}${totalRow}</tbody>
  </table>
  <p class="footer-meta">
    Total Gross: ₹ ${formatMoneyNumber(totals.totalGross)} ·
    Total TDS: ₹ ${formatMoneyNumber(totals.totalTds)} ·
    Total Net Payable: ₹ ${formatMoneyNumber(totals.totalNet)}
  </p>
  <script>window.onload = () => window.print();</script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
}
