import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import { formatMoney, formatMoneyNumber } from "@/lib/accounts/money-format";
import type { RegisterReportTotals } from "./register-types";

const COMPANY_NAME = "Dharitri Sutra Agri Solutions Pvt Ltd";

export interface RegisterExportMeta {
  reportName: string;
  dateFrom: string;
  dateTo: string;
  financialYear: string;
  partyLabel: string;
  partyFilter: string;
  invoiceStatus: string;
  gstRate: string;
  search: string;
}

export interface RegisterExportRow {
  "Invoice Date": string;
  "Invoice No.": string;
  [key: string]: string | number;
  GSTIN: string;
  State: string;
  "Taxable Value": number;
  "GST Amount": number;
  "Invoice Total": number;
  "Payment Status": string;
}

function generatedOnLabel(): string {
  return new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function metaRows(meta: RegisterExportMeta) {
  return [
    ["Company Name", COMPANY_NAME],
    ["Report Name", meta.reportName],
    ["Date Range", `${meta.dateFrom} to ${meta.dateTo}`],
    ["Financial Year", meta.financialYear],
    [meta.partyLabel, meta.partyFilter],
    ["Invoice Status", meta.invoiceStatus],
    ["GST Rate", meta.gstRate],
    ["Search", meta.search || "—"],
    ["Generated By", ACCOUNTS_CURRENT_USER],
    ["Generated On", generatedOnLabel()],
  ];
}

export async function exportRegisterToExcel(
  rows: RegisterExportRow[],
  meta: RegisterExportMeta,
  totals: RegisterReportTotals,
  filePrefix: string,
): Promise<void> {
  const XLSX = await import("xlsx");

  const dataRows = rows.map((r) => ({
    "Invoice Date": r["Invoice Date"],
    "Invoice No.": r["Invoice No."],
    [meta.partyLabel]: r[meta.partyLabel],
    GSTIN: r.GSTIN,
    State: r.State,
    "Taxable Value (₹)": r["Taxable Value"],
    "GST Amount (₹)": r["GST Amount"],
    "Invoice Total (₹)": r["Invoice Total"],
    "Payment Status": r["Payment Status"],
  }));

  const sheet = XLSX.utils.json_to_sheet(dataRows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, sheet, meta.reportName.slice(0, 31));

  const info = XLSX.utils.aoa_to_sheet(metaRows(meta));
  XLSX.utils.book_append_sheet(wb, info, "Report Info");

  const summary = XLSX.utils.aoa_to_sheet([
    ["Total Taxable Value", totals.taxableValue],
    ["Total GST", totals.gstAmount],
    ["Grand Total", totals.grandTotal],
  ]);
  XLSX.utils.book_append_sheet(wb, summary, "Totals");

  const date = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `${filePrefix}_${date}.xlsx`);
}

export function exportRegisterToPdf(
  rows: RegisterExportRow[],
  meta: RegisterExportMeta,
  totals: RegisterReportTotals,
): void {
  const partyHeader = meta.partyLabel;
  const tableRows = rows
    .map(
      (r) => `<tr>
        <td>${r["Invoice Date"]}</td>
        <td class="mono">${r["Invoice No."]}</td>
        <td>${r[partyHeader]}</td>
        <td class="mono">${r.GSTIN}</td>
        <td>${r.State}</td>
        <td class="num">${formatMoney(r["Taxable Value"])}</td>
        <td class="num">${formatMoney(r["GST Amount"])}</td>
        <td class="num">${formatMoney(r["Invoice Total"])}</td>
        <td>${r["Payment Status"]}</td>
      </tr>`,
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${meta.reportName}</title>
  <style>
    @media print { @page { margin: 12mm; } }
    body { font-family: system-ui, sans-serif; font-size: 10px; padding: 20px; color: #111; }
    .header { display: flex; align-items: flex-start; gap: 12px; margin-bottom: 14px; }
    .logo { width: 36px; height: 36px; border-radius: 8px; background: linear-gradient(135deg, #F47920, #D96A10); color: #fff; font-weight: 800; font-size: 13px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
    h1 { font-size: 15px; margin: 0 0 2px; color: #1A3A96; }
    .company { font-size: 11px; font-weight: 600; margin: 0 0 4px; }
    .meta { color: #555; font-size: 9px; line-height: 1.5; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    th, td { border: 1px solid #ddd; padding: 5px 6px; text-align: left; }
    th { background: #fff; font-size: 9px; text-transform: uppercase; font-weight: 700; }
    .num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
    .mono { font-family: ui-monospace, monospace; font-size: 9px; }
    tfoot td { font-weight: 700; background: #f8fafc; border-top: 2px solid #ccc; }
    .footer-meta { margin-top: 14px; font-size: 9px; color: #666; }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">DS</div>
    <div>
      <p class="company">${COMPANY_NAME}</p>
      <h1>${meta.reportName}</h1>
      <p class="meta">
        Date Range: ${meta.dateFrom} to ${meta.dateTo}<br />
        Financial Year: ${meta.financialYear}<br />
        ${meta.partyLabel}: ${meta.partyFilter} · Invoice Status: ${meta.invoiceStatus} · GST Rate: ${meta.gstRate}<br />
        Generated By: ${ACCOUNTS_CURRENT_USER} · Generated On: ${generatedOnLabel()}
      </p>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Invoice Date</th>
        <th>Invoice No.</th>
        <th>${partyHeader}</th>
        <th>GSTIN</th>
        <th>State</th>
        <th class="num">Taxable Value</th>
        <th class="num">GST Amount</th>
        <th class="num">Invoice Total</th>
        <th>Payment Status</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
    <tfoot>
      <tr>
        <td colspan="5">Totals</td>
        <td class="num">${formatMoney(totals.taxableValue)}</td>
        <td class="num">${formatMoney(totals.gstAmount)}</td>
        <td class="num">${formatMoney(totals.grandTotal)}</td>
        <td></td>
      </tr>
    </tfoot>
  </table>
  <p class="footer-meta">
    Total Taxable Value: ₹ ${formatMoneyNumber(totals.taxableValue)} ·
    Total GST: ₹ ${formatMoneyNumber(totals.gstAmount)} ·
    Grand Total: ₹ ${formatMoneyNumber(totals.grandTotal)} ·
    ${totals.count} invoice(s)
  </p>
  <script>window.onload = () => window.print();</script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
}
