import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import {
  formatMoney,
  formatMoneyOrDash,
  formatMoneyWithSide,
} from "@/lib/accounts/money-format";
import type { BankBookDisplayRow, BankBookSummary } from "./bank-book-data";
import { formatBankBookDate } from "./bank-book-data";

const COMPANY_NAME = "Dharitri Sutra Agri Solutions Pvt Ltd";
const REPORT_NAME = "Bank Book";

export interface BankBookExportMeta {
  dateFrom: string;
  dateTo: string;
  financialYear: string;
}

function generatedOnLabel(): string {
  return new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function balanceLabel(row: BankBookDisplayRow): string {
  return formatMoneyWithSide(row.runningBalance, row.runningBalanceType);
}

export async function exportBankBookToExcel(
  openingRow: BankBookDisplayRow,
  transactionRows: BankBookDisplayRow[],
  summary: BankBookSummary,
  meta: BankBookExportMeta,
): Promise<void> {
  const XLSX = await import("xlsx");
  const rows = [openingRow, ...transactionRows];

  const dataRows = rows.map((r) => ({
    Date: r.kind === "opening" ? formatBankBookDate(r.date) : formatBankBookDate(r.date),
    "Voucher No.": r.voucherNo,
    "Voucher Type": r.voucherType,
    Particular: r.particular,
    Narration: r.narration,
    "Receipt (₹)": r.receipt || "",
    "Payment (₹)": r.payment || "",
    "Running Balance": balanceLabel(r),
  }));

  const sheet = XLSX.utils.json_to_sheet(dataRows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, sheet, "Bank Book");

  const info = XLSX.utils.aoa_to_sheet([
    ["Company Name", COMPANY_NAME],
    ["Report Name", REPORT_NAME],
    ["Bank Name", summary.bankName],
    ["Account", `${summary.accountNickname} (${summary.maskedAccountNumber})`],
    ["Date Range", `${meta.dateFrom} to ${meta.dateTo}`],
    ["Financial Year", meta.financialYear],
    [
      "Opening Balance",
      formatMoneyWithSide(summary.openingBalance, summary.openingBalanceType),
    ],
    ["Total Receipts", summary.totalReceipts],
    ["Total Payments", summary.totalPayments],
    [
      "Closing Balance",
      formatMoneyWithSide(summary.closingBalance, summary.closingBalanceType),
    ],
    ["Generated By", ACCOUNTS_CURRENT_USER],
    ["Generated On", generatedOnLabel()],
  ]);
  XLSX.utils.book_append_sheet(wb, info, "Report Info");

  const safeName = summary.accountNickname.replace(/[^\w-]+/g, "_");
  const date = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `Bank_Book_${safeName}_${date}.xlsx`);
}

export function exportBankBookToPdf(
  openingRow: BankBookDisplayRow,
  transactionRows: BankBookDisplayRow[],
  summary: BankBookSummary,
  meta: BankBookExportMeta,
): void {
  const rows = [openingRow, ...transactionRows];
  const tableRows = rows
    .map(
      (r) => `
    <tr class="${r.kind === "opening" ? "summary-row" : ""}">
      <td>${formatBankBookDate(r.date)}</td>
      <td>${r.voucherNo}</td>
      <td>${r.voucherType}</td>
      <td>${r.particular}</td>
      <td>${r.narration}</td>
      <td class="num">${formatMoneyOrDash(r.receipt)}</td>
      <td class="num">${formatMoneyOrDash(r.payment)}</td>
      <td class="num">${balanceLabel(r)}</td>
    </tr>`,
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Bank Book — ${summary.accountNickname}</title>
  <style>
    body { font-family: system-ui, sans-serif; font-size: 11px; padding: 24px; color: #111; }
    h1 { font-size: 16px; margin: 0 0 4px; color: #1A3A96; }
    .meta { color: #555; margin-bottom: 16px; font-size: 10px; line-height: 1.5; }
    table { width: 100%; border-collapse: collapse; }
    th, td { border: 1px solid #ddd; padding: 6px 8px; text-align: left; }
    th { background: #fff; font-size: 10px; text-transform: uppercase; }
    .num { text-align: right; font-variant-numeric: tabular-nums; }
    .summary-row td { font-weight: 600; background: #fafafa; }
    tfoot td { font-weight: 600; background: #f5f5f5; }
  </style>
</head>
<body>
  <h1>${summary.bankName} — ${summary.accountNickname}</h1>
  <p class="meta">
    Account: ${summary.maskedAccountNumber}<br />
    Period: ${meta.dateFrom} to ${meta.dateTo} · Financial Year: ${meta.financialYear}<br />
    Opening: ${formatMoneyWithSide(summary.openingBalance, summary.openingBalanceType)} ·
    Total Receipts: ${formatMoney(summary.totalReceipts)} ·
    Total Payments: ${formatMoney(summary.totalPayments)} ·
    Closing: ${formatMoneyWithSide(summary.closingBalance, summary.closingBalanceType)}
  </p>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Voucher No.</th>
        <th>Voucher Type</th>
        <th>Particular</th>
        <th>Narration</th>
        <th>Receipt (₹)</th>
        <th>Payment (₹)</th>
        <th>Running Balance</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
    <tfoot>
      <tr>
        <td colspan="5">Total</td>
        <td class="num">${formatMoney(summary.totalReceipts)}</td>
        <td class="num">${formatMoney(summary.totalPayments)}</td>
        <td class="num">${formatMoneyWithSide(summary.closingBalance, summary.closingBalanceType)}</td>
      </tr>
    </tfoot>
  </table>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 400);
}
