export type FarmerStatus = "Active" | "Inactive";
export type FarmingPracticeType = "Chemical" | "Biological" | "Both";
export type OwnershipType = "Owned" | "Leased" | "Owned + Leased";

export interface Farmer {
  id: number;
  name: string;
  fatherName: string;
  age: number;
  gender: "Male" | "Female" | "Other";
  phoneNumber: string;
  village: string;
  town: string;
  city: string;
  district: string;
  state: string;
  pincode: string;
  farmlandSize: string;
  ownershipType: OwnershipType;
  currentCrop: string;
  cropRotation: string;
  cropEntries: Array<{
    type: string;
    category: string;
    produceCropName: string;
    landSize: string;
    ownershipType: "Owned" | "Leased";
    cropRotation: string;
  }>;
  chemicalBiologicalPercentage: string;
  brandProductUses: string;
  brandsRecall: string;
  currentProblem: string;
  majorDiseases: string;
  majorPests: string;
  productsUsed: string;
  currentBrandUsed: string;
  farmingPractice: FarmingPracticeType;
  chemicalPercent?: number;
  biologicalPercent?: number;
  latLong: string;
  status: FarmerStatus;
  lastUpdated: string;
}

type FarmerSeedRecord = Omit<
  Farmer,
  | "status"
  | "lastUpdated"
  | "majorPests"
  | "productsUsed"
  | "currentBrandUsed"
  | "farmingPractice"
  | "chemicalPercent"
  | "biologicalPercent"
> & {
  /** Optional override — comma-separated brands currently in use */
  currentBrandUsed?: string;
};

const MAJOR_PESTS_BY_ID: Record<number, string> = {
  1: "Whitefly, bollworm",
  2: "Aphids, thrips",
  3: "Stem borer, leaf folder",
  4: "Fall armyworm, cutworm",
  5: "Termites, mealybug",
  6: "Girdle beetle, pod borer",
  7: "Leaf folder, hispa",
  8: "Semilooper, jute hairy caterpillar",
  9: "Leaf miner, thrips",
  10: "Pod borer, stem fly",
  11: "Aphids, brown planthopper",
  12: "Stem borer, top borer",
  13: "Aphids, thrips",
  14: "Leaf folder, gall midge",
  15: "Thrips, onion maggot",
  16: "Cutworm, aphid",
  17: "Bollworm, jassids",
  18: "Pod borer, stem borer",
  19: "Stem weevil, rhinoceros beetle",
  20: "Fall armyworm, shoot borer",
};

function enrichFarmerRecord(raw: FarmerSeedRecord, index: number): Farmer {
  const chemicalMatch = raw.chemicalBiologicalPercentage.match(/Chemical\s*(\d+)/i);
  const biologicalMatch = raw.chemicalBiologicalPercentage.match(/Biological\s*(\d+)/i);
  const chemicalPercent = chemicalMatch ? Number(chemicalMatch[1]) : undefined;
  const biologicalPercent = biologicalMatch ? Number(biologicalMatch[1]) : undefined;

  let farmingPractice: FarmingPracticeType = "Both";
  if (chemicalPercent !== undefined && biologicalPercent !== undefined) {
    if (chemicalPercent >= 95) farmingPractice = "Chemical";
    else if (biologicalPercent >= 95) farmingPractice = "Biological";
  }

  const products = raw.brandProductUses
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);

  return {
    ...raw,
    majorPests: MAJOR_PESTS_BY_ID[raw.id] ?? "—",
    productsUsed: raw.brandProductUses,
    currentBrandUsed: raw.currentBrandUsed ?? products[0] ?? raw.brandProductUses,
    farmingPractice,
    chemicalPercent,
    biologicalPercent,
    status: raw.id === 20 ? "Inactive" : "Active",
    lastUpdated: `2026-06-${String((index % 26) + 1).padStart(2, "0")}`,
  };
}

const RAW_SEED: FarmerSeedRecord[] = [
  {
    id: 1,
    name: "Ramesh Patel",
    fatherName: "Mahendra Patel",
    age: 42,
    gender: "Male",
    phoneNumber: "9876501001",
    village: "Navapura",
    town: "Anand",
    city: "Anand",
    district: "Anand",
    state: "Gujarat",
    pincode: "388001",
    farmlandSize: "4.5 Acres",
    ownershipType: "Owned + Leased",
    currentCrop: "Cotton, Wheat",
    cropRotation: "Parcel based",
    cropEntries: [
      { type: "Cash Crop", category: "Fibre", produceCropName: "Cotton (Kapas)", landSize: "3.0 Acres", ownershipType: "Owned", cropRotation: "Cotton -> Wheat" },
      { type: "Cereal", category: "Rabi Cereal", produceCropName: "Wheat", landSize: "1.5 Acres", ownershipType: "Leased", cropRotation: "Wheat -> Fallow" },
    ],
    chemicalBiologicalPercentage: "Chemical 60% / Biological 40%",
    brandProductUses: "Dharitri Shield Insecticide",
    brandsRecall: "Shield, Crop Booster, Root Guard",
    currentProblem: "Whitefly infestation and uneven flowering",
    majorDiseases: "Whitefly, bollworm",
    latLong: "22.5645, 72.9289",
  },
  {
    id: 2,
    name: "Suresh Kumar",
    fatherName: "Ratan Kumar",
    age: 38,
    gender: "Male",
    phoneNumber: "9876501002",
    village: "Kheralu",
    town: "Kheralu",
    city: "Mehsana",
    district: "Mehsana",
    state: "Gujarat",
    pincode: "384325",
    farmlandSize: "2.0 Acres",
    ownershipType: "Leased",
    currentCrop: "Wheat, Cumin",
    cropRotation: "Parcel based",
    cropEntries: [
      { type: "Cereal", category: "Rabi Cereal", produceCropName: "Wheat", landSize: "1.25 Acres", ownershipType: "Leased", cropRotation: "Wheat -> Cumin" },
      { type: "Spice", category: "Seed Spice", produceCropName: "Cumin (Jeera)", landSize: "0.75 Acres", ownershipType: "Leased", cropRotation: "Cumin -> Fallow" },
    ],
    chemicalBiologicalPercentage: "Chemical 70% / Biological 30%",
    brandProductUses: "YieldMax Fungicide",
    brandsRecall: "YieldMax, Soil Plus",
    currentProblem: "Leaf yellowing and low grain weight",
    majorDiseases: "Rust, aphids",
    latLong: "23.8851, 72.6187",
  },
  {
    id: 3,
    name: "Mahesh Singh",
    fatherName: "Shivlal Singh",
    age: 46,
    gender: "Male",
    phoneNumber: "9876501003",
    village: "Bhanpur",
    town: "Raipur Rural",
    city: "Raipur",
    district: "Raipur",
    state: "Chhattisgarh",
    pincode: "492001",
    farmlandSize: "6.0 Acres",
    ownershipType: "Owned + Leased",
    currentCrop: "Paddy, Maize",
    cropRotation: "Parcel based",
    cropEntries: [
      { type: "Cereal", category: "Kharif Cereal", produceCropName: "Rice (Paddy)", landSize: "4.0 Acres", ownershipType: "Owned", cropRotation: "Paddy -> Maize" },
      { type: "Cereal", category: "Kharif Cereal", produceCropName: "Maize (Corn)", landSize: "2.0 Acres", ownershipType: "Leased", cropRotation: "Maize -> Fallow" },
    ],
    chemicalBiologicalPercentage: "Chemical 50% / Biological 50%",
    brandProductUses: "Paddy Care Herbicide",
    brandsRecall: "Paddy Care, BioRoot",
    currentProblem: "Weed pressure and poor water retention",
    majorDiseases: "Stem borer, blast",
    latLong: "21.2514, 81.6296",
  },
  {
    id: 4,
    name: "Prakash Rao",
    fatherName: "Narayana Rao",
    age: 35,
    gender: "Male",
    phoneNumber: "9876501004",
    village: "Tandur",
    town: "Tandur",
    city: "Vikarabad",
    district: "Vikarabad",
    state: "Telangana",
    pincode: "501141",
    farmlandSize: "3.5 Acres",
    ownershipType: "Leased",
    currentCrop: "Maize, Cotton",
    cropRotation: "Parcel based",
    cropEntries: [
      { type: "Cereal", category: "Kharif Cereal", produceCropName: "Maize (Corn)", landSize: "2.0 Acres", ownershipType: "Leased", cropRotation: "Maize -> Cotton" },
      { type: "Cash Crop", category: "Fibre", produceCropName: "Cotton (Kapas)", landSize: "1.5 Acres", ownershipType: "Leased", cropRotation: "Cotton -> Fallow" },
    ],
    chemicalBiologicalPercentage: "Chemical 65% / Biological 35%",
    brandProductUses: "Maize Guard Nutrient Mix",
    brandsRecall: "Maize Guard, Power Spray",
    currentProblem: "Stem weakness and patchy germination",
    majorDiseases: "Fall armyworm",
    latLong: "17.2473, 77.5767",
  },
  {
    id: 5,
    name: "Rajan Verma",
    fatherName: "Bhola Verma",
    age: 41,
    gender: "Male",
    phoneNumber: "9876501005",
    village: "Barwa",
    town: "Fatehpur",
    city: "Fatehpur",
    district: "Fatehpur",
    state: "Uttar Pradesh",
    pincode: "212601",
    farmlandSize: "1.5 Acres",
    ownershipType: "Owned",
    currentCrop: "Sugarcane, Wheat",
    cropRotation: "Parcel based",
    cropEntries: [
      { type: "Cash Crop", category: "Sugar", produceCropName: "Sugarcane", landSize: "1.0 Acre", ownershipType: "Owned", cropRotation: "Sugarcane -> Wheat" },
      { type: "Cereal", category: "Rabi Cereal", produceCropName: "Wheat", landSize: "0.5 Acre", ownershipType: "Owned", cropRotation: "Wheat -> Fallow" },
    ],
    chemicalBiologicalPercentage: "Chemical 75% / Biological 25%",
    brandProductUses: "Cane Boost Micronutrient",
    brandsRecall: "Cane Boost, GrowFast",
    currentProblem: "Low cane thickness and water stress",
    majorDiseases: "Red rot, termites",
    latLong: "25.9270, 80.8120",
  },
  {
    id: 6,
    name: "Haridas Patil",
    fatherName: "Ganesh Patil",
    age: 49,
    gender: "Male",
    phoneNumber: "9876501006",
    village: "Mohol",
    town: "Mohol",
    city: "Solapur",
    district: "Solapur",
    state: "Maharashtra",
    pincode: "413213",
    farmlandSize: "8.0 Acres",
    ownershipType: "Owned + Leased",
    currentCrop: "Soybean, Sorghum (Jowar)",
    cropRotation: "Parcel based",
    cropEntries: [
      { type: "Oil Seed", category: "Oil Seed", produceCropName: "Soybean", landSize: "5.5 Acres", ownershipType: "Owned", cropRotation: "Soybean -> Jowar" },
      { type: "Cereal", category: "Kharif Cereal", produceCropName: "Sorghum (Jowar)", landSize: "2.5 Acres", ownershipType: "Leased", cropRotation: "Jowar -> Fallow" },
    ],
    chemicalBiologicalPercentage: "Chemical 55% / Biological 45%",
    brandProductUses: "Soy Root Stimulator",
    brandsRecall: "Soy Root, LeafCare",
    currentProblem: "Pod drop during late growth stage",
    majorDiseases: "Yellow mosaic, girdle beetle",
    latLong: "17.8112, 75.6411",
  },
  {
    id: 7,
    name: "Gopal Nair",
    fatherName: "Krishnan Nair",
    age: 44,
    gender: "Male",
    phoneNumber: "9876501007",
    village: "Kuttanad",
    town: "Kuttanad",
    city: "Alappuzha",
    district: "Alappuzha",
    state: "Kerala",
    pincode: "688001",
    farmlandSize: "1.0 Acres",
    ownershipType: "Leased",
    currentCrop: "Paddy",
    cropRotation: "Paddy -> Fallow",
    cropEntries: [
      { type: "Cereal", category: "Kharif Cereal", produceCropName: "Rice (Paddy)", landSize: "1.0 Acre", ownershipType: "Leased", cropRotation: "Paddy -> Fallow" },
    ],
    chemicalBiologicalPercentage: "Chemical 40% / Biological 60%",
    brandProductUses: "Bio Paddy Shield",
    brandsRecall: "Bio Paddy Shield, Aqua Protect",
    currentProblem: "Waterlogging and nutrient loss",
    majorDiseases: "Leaf folder, sheath blight",
    latLong: "9.4981, 76.3388",
  },
  {
    id: 8,
    name: "Bharat Das",
    fatherName: "Raghunath Das",
    age: 39,
    gender: "Male",
    phoneNumber: "9876501008",
    village: "Srirampur",
    town: "Srirampur",
    city: "Murshidabad",
    district: "Murshidabad",
    state: "West Bengal",
    pincode: "742149",
    farmlandSize: "2.5 Acres",
    ownershipType: "Owned",
    currentCrop:
      "Jute, Rice (Paddy), Wheat, Maize, Mustard, Potato, Sugarcane, Sesame, Lentil, Chickpea, Groundnut, Soybean, Vegetables, Mango, Banana, Coconut, Turmeric, Ginger, Onion, Garlic",
    cropRotation:
      "Jute, Paddy, Wheat, Mustard, Fallow, Potato, Sugarcane, Sesame, Groundnut, Soybean, Tur, Moong, Maize, Vegetables, Onion",
    cropEntries: [],
    chemicalBiologicalPercentage: "Chemical 58% / Biological 42%",
    currentBrandUsed:
      "Jute Pro Growth Mix, GreenField Bio, Paddy Shield, AgriMax Plus, BioRise Kharif, CropCare Elite, Kisan Shakti, NaturaGrow, Assam Bio Pack, Harvest Gold, SeedMaster Pro, FieldForce Mix",
    brandProductUses:
      "Jute Pro Growth Mix, Jute Stem Booster, Paddy NutriMix, Bio Fungicide Spray, Nematode Control, Micronutrient Blend, Organic Compost Tea, Drip Fertigation A, Soil pH Balancer, Rhizobium Culture",
    brandsRecall:
      "Jute Pro, GreenField Bio, Paddy Bio, Mustard Plus, CropShield, AgriGold, BioFarm, Kisan Kit, Harvest Plus, NaturaRoot, FieldMax, GreenLeaf, ProGrow, SeedCare, TerraMix",
    currentProblem: "Slow stem growth and pest spots",
    majorDiseases: "Semilooper, stem rot",
    latLong: "24.1750, 88.2750",
  },
  {
    id: 9,
    name: "Lakshmi Reddy",
    fatherName: "Srinivas Reddy",
    age: 37,
    gender: "Female",
    phoneNumber: "9876501009",
    village: "Vempalli",
    town: "Vempalli",
    city: "Kadapa",
    district: "Kadapa",
    state: "Andhra Pradesh",
    pincode: "516329",
    farmlandSize: "3.0 Acres",
    ownershipType: "Owned + Leased",
    currentCrop: "Groundnut, Red Gram",
    cropRotation: "Parcel based",
    cropEntries: [
      { type: "Oil Seed", category: "Kharif Oil Seed", produceCropName: "Groundnut", landSize: "2.0 Acres", ownershipType: "Owned", cropRotation: "Groundnut -> Fallow" },
      { type: "Pulse", category: "Kharif Pulse", produceCropName: "Red Gram (Tur)", landSize: "1.0 Acre", ownershipType: "Leased", cropRotation: "Red Gram -> Sesame" },
    ],
    chemicalBiologicalPercentage: "Chemical 52% / Biological 48%",
    brandProductUses: "Groundnut Shield Spray",
    brandsRecall: "Groundnut Shield, BioRise",
    currentProblem: "Pod formation is weak in one parcel",
    majorDiseases: "Leaf miner, tikka disease",
    latLong: "14.3664, 78.6067",
  },
  {
    id: 10,
    name: "Sunita Chauhan",
    fatherName: "Mahipal Chauhan",
    age: 40,
    gender: "Female",
    phoneNumber: "9876501010",
    village: "Ashta",
    town: "Ashta",
    city: "Sehore",
    district: "Sehore",
    state: "Madhya Pradesh",
    pincode: "466116",
    farmlandSize: "5.0 Acres",
    ownershipType: "Owned",
    currentCrop: "Soybean, Chickpea",
    cropRotation: "Parcel based",
    cropEntries: [
      { type: "Oil Seed", category: "Kharif Oil Seed", produceCropName: "Soybean", landSize: "3.0 Acres", ownershipType: "Owned", cropRotation: "Soybean -> Chickpea" },
      { type: "Pulse", category: "Rabi Pulse", produceCropName: "Chickpea (Gram)", landSize: "2.0 Acres", ownershipType: "Owned", cropRotation: "Chickpea -> Fallow" },
    ],
    chemicalBiologicalPercentage: "Chemical 57% / Biological 43%",
    brandProductUses: "Pulse Root Activator",
    brandsRecall: "Pulse Root, SoyCare",
    currentProblem: "Yellowing observed after recent rain",
    majorDiseases: "Pod borer, collar rot",
    latLong: "23.0173, 76.7247",
  },
  {
    id: 11,
    name: "Devendra Yadav",
    fatherName: "Ramvilas Yadav",
    age: 45,
    gender: "Male",
    phoneNumber: "9876501011",
    village: "Hilsa",
    town: "Hilsa",
    city: "Nalanda",
    district: "Nalanda",
    state: "Bihar",
    pincode: "801302",
    farmlandSize: "4.0 Acres",
    ownershipType: "Leased",
    currentCrop: "Rice (Paddy), Mustard",
    cropRotation: "Parcel based",
    cropEntries: [
      { type: "Cereal", category: "Kharif Cereal", produceCropName: "Rice (Paddy)", landSize: "2.5 Acres", ownershipType: "Leased", cropRotation: "Paddy -> Mustard" },
      { type: "Oil Seed", category: "Rabi Oil Seed", produceCropName: "Mustard", landSize: "1.5 Acres", ownershipType: "Leased", cropRotation: "Mustard -> Fallow" },
    ],
    chemicalBiologicalPercentage: "Chemical 68% / Biological 32%",
    brandProductUses: "Mustard Yield Tonic",
    brandsRecall: "Yield Tonic, Paddy Gold",
    currentProblem: "Low tillering in the paddy parcel",
    majorDiseases: "Blast, aphids",
    latLong: "25.3167, 85.2833",
  },
  {
    id: 12,
    name: "Manjunath Gowda",
    fatherName: "Ranga Gowda",
    age: 43,
    gender: "Male",
    phoneNumber: "9876501012",
    village: "Srirangapatna",
    town: "Srirangapatna",
    city: "Mandya",
    district: "Mandya",
    state: "Karnataka",
    pincode: "571438",
    farmlandSize: "6.5 Acres",
    ownershipType: "Owned + Leased",
    currentCrop: "Sugarcane, Rice (Paddy)",
    cropRotation: "Parcel based",
    cropEntries: [
      { type: "Cash Crop", category: "Sugar", produceCropName: "Sugarcane", landSize: "4.0 Acres", ownershipType: "Owned", cropRotation: "Sugarcane -> Ratoon" },
      { type: "Cereal", category: "Kharif Cereal", produceCropName: "Rice (Paddy)", landSize: "2.5 Acres", ownershipType: "Leased", cropRotation: "Paddy -> Fallow" },
    ],
    chemicalBiologicalPercentage: "Chemical 61% / Biological 39%",
    brandProductUses: "Cane Energy Mix",
    brandsRecall: "Cane Energy, Paddy Prime",
    currentProblem: "Stalk thickness is uneven across plots",
    majorDiseases: "Red rot, stem borer",
    latLong: "12.4226, 76.6930",
  },
  {
    id: 13,
    name: "Pooja Jat",
    fatherName: "Bherulal Jat",
    age: 33,
    gender: "Female",
    phoneNumber: "9876501013",
    village: "Sultanpur",
    town: "Digod",
    city: "Kota",
    district: "Kota",
    state: "Rajasthan",
    pincode: "325204",
    farmlandSize: "2.8 Acres",
    ownershipType: "Leased",
    currentCrop: "Coriander, Wheat",
    cropRotation: "Parcel based",
    cropEntries: [
      { type: "Spice", category: "Seed Spice", produceCropName: "Coriander", landSize: "1.2 Acres", ownershipType: "Leased", cropRotation: "Coriander -> Fallow" },
      { type: "Cereal", category: "Rabi Cereal", produceCropName: "Wheat", landSize: "1.6 Acres", ownershipType: "Leased", cropRotation: "Wheat -> Coriander" },
    ],
    chemicalBiologicalPercentage: "Chemical 49% / Biological 51%",
    brandProductUses: "Spice Guard Fungicide",
    brandsRecall: "Spice Guard, Wheat Care",
    currentProblem: "Patchy growth in coriander rows",
    majorDiseases: "Powdery mildew, aphids",
    latLong: "25.1032, 76.1647",
  },
  {
    id: 14,
    name: "Ajay Boro",
    fatherName: "Dharam Boro",
    age: 39,
    gender: "Male",
    phoneNumber: "9876501014",
    village: "Kampur",
    town: "Kampur",
    city: "Nagaon",
    district: "Nagaon",
    state: "Assam",
    pincode: "782426",
    farmlandSize: "3.8 Acres",
    ownershipType: "Owned",
    currentCrop: "Rice (Paddy), Mustard",
    cropRotation: "Parcel based",
    cropEntries: [
      { type: "Cereal", category: "Kharif Cereal", produceCropName: "Rice (Paddy)", landSize: "2.5 Acres", ownershipType: "Owned", cropRotation: "Paddy -> Mustard" },
      { type: "Oil Seed", category: "Rabi Oil Seed", produceCropName: "Mustard", landSize: "1.3 Acres", ownershipType: "Owned", cropRotation: "Mustard -> Fallow" },
    ],
    chemicalBiologicalPercentage: "Chemical 46% / Biological 54%",
    brandProductUses: "Assam Paddy Bio Pack",
    brandsRecall: "Paddy Bio, Mustard Plus",
    currentProblem: "Flood impact on low-lying parcel",
    majorDiseases: "Blast, leaf folder",
    latLong: "26.3582, 92.6925",
  },
  {
    id: 15,
    name: "Rekha Pawar",
    fatherName: "Madhukar Pawar",
    age: 36,
    gender: "Female",
    phoneNumber: "9876501015",
    village: "Niphad",
    town: "Niphad",
    city: "Nashik",
    district: "Nashik",
    state: "Maharashtra",
    pincode: "422303",
    farmlandSize: "2.2 Acres",
    ownershipType: "Owned + Leased",
    currentCrop: "Onion, Millet (Bajra)",
    cropRotation: "Parcel based",
    cropEntries: [
      { type: "Vegetable", category: "Bulb Crop", produceCropName: "Onion", landSize: "1.2 Acres", ownershipType: "Owned", cropRotation: "Onion -> Bajra" },
      { type: "Cereal", category: "Kharif Cereal", produceCropName: "Millet (Bajra)", landSize: "1.0 Acre", ownershipType: "Leased", cropRotation: "Bajra -> Onion" },
    ],
    chemicalBiologicalPercentage: "Chemical 54% / Biological 46%",
    brandProductUses: "Bulb Strength Mix",
    brandsRecall: "Bulb Strength, RainSafe",
    currentProblem: "Neck rot symptoms in stored onions",
    majorDiseases: "Thrips, purple blotch",
    latLong: "20.0837, 74.1078",
  },
  {
    id: 16,
    name: "Tsering Namgyal",
    fatherName: "Dorje Namgyal",
    age: 41,
    gender: "Male",
    phoneNumber: "9876501016",
    village: "Diskit",
    town: "Diskit",
    city: "Leh",
    district: "Leh",
    state: "Ladakh",
    pincode: "194401",
    farmlandSize: "1.8 Acres",
    ownershipType: "Owned",
    currentCrop: "Barley, Pea",
    cropRotation: "Parcel based",
    cropEntries: [
      { type: "Cereal", category: "High Altitude Cereal", produceCropName: "Barley", landSize: "1.0 Acre", ownershipType: "Owned", cropRotation: "Barley -> Pea" },
      { type: "Pulse", category: "Vegetable Pulse", produceCropName: "Pea", landSize: "0.8 Acre", ownershipType: "Owned", cropRotation: "Pea -> Fallow" },
    ],
    chemicalBiologicalPercentage: "Chemical 28% / Biological 72%",
    brandProductUses: "Cold Climate Bio Mix",
    brandsRecall: "Cold Climate Bio, Root Warm",
    currentProblem: "Short growing window limits recovery",
    majorDiseases: "Rust, cutworm",
    latLong: "34.5594, 77.5472",
  },
  {
    id: 17,
    name: "Imran Sheikh",
    fatherName: "Yakub Sheikh",
    age: 34,
    gender: "Male",
    phoneNumber: "9876501017",
    village: "Parbhani Rural",
    town: "Parbhani",
    city: "Parbhani",
    district: "Parbhani",
    state: "Maharashtra",
    pincode: "431401",
    farmlandSize: "4.7 Acres",
    ownershipType: "Leased",
    currentCrop: "Cotton, Soybean",
    cropRotation: "Parcel based",
    cropEntries: [
      { type: "Cash Crop", category: "Fibre", produceCropName: "Cotton (Kapas)", landSize: "2.2 Acres", ownershipType: "Leased", cropRotation: "Cotton -> Soybean" },
      { type: "Oil Seed", category: "Kharif Oil Seed", produceCropName: "Soybean", landSize: "2.5 Acres", ownershipType: "Leased", cropRotation: "Soybean -> Fallow" },
    ],
    chemicalBiologicalPercentage: "Chemical 66% / Biological 34%",
    brandProductUses: "Boll Safe Protector",
    brandsRecall: "Boll Safe, Soy Boost",
    currentProblem: "Flower drop in the cotton section",
    majorDiseases: "Bollworm, yellow mosaic",
    latLong: "19.2699, 76.7708",
  },
  {
    id: 18,
    name: "Nirmala Sahu",
    fatherName: "Raghu Sahu",
    age: 47,
    gender: "Female",
    phoneNumber: "9876501018",
    village: "Bhatapara",
    town: "Bhatapara",
    city: "Baloda Bazar",
    district: "Baloda Bazar",
    state: "Chhattisgarh",
    pincode: "493118",
    farmlandSize: "5.5 Acres",
    ownershipType: "Owned + Leased",
    currentCrop: "Rice (Paddy), Black Gram",
    cropRotation: "Parcel based",
    cropEntries: [
      { type: "Cereal", category: "Kharif Cereal", produceCropName: "Rice (Paddy)", landSize: "3.5 Acres", ownershipType: "Owned", cropRotation: "Paddy -> Black Gram" },
      { type: "Pulse", category: "Rabi Pulse", produceCropName: "Black Gram (Urad)", landSize: "2.0 Acres", ownershipType: "Leased", cropRotation: "Urad -> Fallow" },
    ],
    chemicalBiologicalPercentage: "Chemical 51% / Biological 49%",
    brandProductUses: "Paddy Balance Pack",
    brandsRecall: "Paddy Balance, Pulse Guard",
    currentProblem: "Uneven water distribution across fields",
    majorDiseases: "Bacterial leaf blight, pod borer",
    latLong: "21.7357, 81.9474",
  },
  {
    id: 19,
    name: "Joseph Mathew",
    fatherName: "Mathew Joseph",
    age: 52,
    gender: "Male",
    phoneNumber: "9876501019",
    village: "Pala",
    town: "Pala",
    city: "Kottayam",
    district: "Kottayam",
    state: "Kerala",
    pincode: "686575",
    farmlandSize: "2.9 Acres",
    ownershipType: "Owned",
    currentCrop: "Rubber, Banana",
    cropRotation: "Parcel based",
    cropEntries: [
      { type: "Plantation", category: "Commercial Plantation", produceCropName: "Rubber", landSize: "2.0 Acres", ownershipType: "Owned", cropRotation: "Rubber -> Rubber" },
      { type: "Fruit", category: "Tropical Fruit", produceCropName: "Banana", landSize: "0.9 Acre", ownershipType: "Owned", cropRotation: "Banana -> Fallow" },
    ],
    chemicalBiologicalPercentage: "Chemical 38% / Biological 62%",
    brandProductUses: "Plantation Care Kit",
    brandsRecall: "Plantation Care, Banana Lift",
    currentProblem: "Moisture stress in the banana patch",
    majorDiseases: "Sigatoka, stem weevil",
    latLong: "9.7116, 76.6863",
  },
  {
    id: 20,
    name: "Kavita Solanki",
    fatherName: "Bhupendra Solanki",
    age: 31,
    gender: "Female",
    phoneNumber: "9876501020",
    village: "Santrampur",
    town: "Santrampur",
    city: "Mahisagar",
    district: "Mahisagar",
    state: "Gujarat",
    pincode: "389260",
    farmlandSize: "3.4 Acres",
    ownershipType: "Owned + Leased",
    currentCrop: "Maize (Corn), Castor",
    cropRotation: "Parcel based",
    cropEntries: [
      { type: "Cereal", category: "Kharif Cereal", produceCropName: "Maize (Corn)", landSize: "2.0 Acres", ownershipType: "Owned", cropRotation: "Maize -> Castor" },
      { type: "Oil Seed", category: "Industrial Oil Seed", produceCropName: "Castor", landSize: "1.4 Acres", ownershipType: "Leased", cropRotation: "Castor -> Fallow" },
    ],
    chemicalBiologicalPercentage: "Chemical 59% / Biological 41%",
    brandProductUses: "Corn Vital Spray",
    brandsRecall: "Corn Vital, Castor Shield",
    currentProblem: "Low cob fill in the upland parcel",
    majorDiseases: "Fall armyworm, wilt",
    latLong: "23.1911, 73.8916",
  },
];

export const SEED: Farmer[] = RAW_SEED.map(enrichFarmerRecord);

export const VIEW_FARMER_STORAGE_KEY = "farmer:view-id";
