import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import { formatMoney, formatMoneyNumber } from "@/lib/accounts/money-format";
import type { StockValuationRow, StockValuationTotals } from "./stock-valuation-data";
import { formatStockValuationDate } from "./stock-valuation-data";

const COMPANY_NAME = "Dharitri Sutra Agri Solutions Pvt Ltd";
const REPORT_NAME = "Stock Valuation";

export interface StockValuationExportMeta {
  asOnDate: string;
  financialYear: string;
  warehouse: string;
  category: string;
  product: string;
  stockStatus: string;
  search: string;
}

function generatedOnLabel(): string {
  return new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function metaRows(meta: StockValuationExportMeta, totals: StockValuationTotals) {
  return [
    ["Company Name", COMPANY_NAME],
    ["Report Name", REPORT_NAME],
    ["As On Date", meta.asOnDate],
    ["Financial Year", meta.financialYear],
    ["Warehouse", meta.warehouse],
    ["Category", meta.category],
    ["Product", meta.product],
    ["Stock Status", meta.stockStatus],
    ["Search", meta.search || "—"],
    ["Generated By", ACCOUNTS_CURRENT_USER],
    ["Generated On", generatedOnLabel()],
    [],
    ["Total Available Quantity", totals.totalAvailableQty],
    ["Total Stock Value", totals.totalStockValue],
  ];
}

function toExportRow(row: StockValuationRow) {
  return {
    Product: row.product,
    SKU: row.sku,
    UOM: row.uom,
    "Pack Size": row.packSize,
    "Units Per Pack": row.unitsPerPack,
    "Batch No": row.batchNo,
    Warehouse: row.warehouse,
    "Available Qty": row.availableQty,
    "Cost Price (CP)": row.costPrice,
    "Stock Value": row.stockValue,
    "Manufacturing Date": formatStockValuationDate(row.mfgDate),
    "Expiry Date": formatStockValuationDate(row.expiryDate),
    "Stock Status": row.stockStatus,
  };
}

export async function exportStockValuationToExcel(
  rows: StockValuationRow[],
  meta: StockValuationExportMeta,
  totals: StockValuationTotals,
): Promise<void> {
  const XLSX = await import("xlsx");

  const dataRows = rows.map((r) => {
    const e = toExportRow(r);
    return {
      Product: e.Product,
      SKU: e.SKU,
      UOM: e.UOM,
      "Pack Size": e["Pack Size"],
      "Units Per Pack": e["Units Per Pack"],
      "Batch No": e["Batch No"],
      Warehouse: e.Warehouse,
      "Available Qty": e["Available Qty"],
      "Cost Price (₹)": e["Cost Price (CP)"],
      "Stock Value (₹)": e["Stock Value"],
      "Manufacturing Date": e["Manufacturing Date"],
      "Expiry Date": e["Expiry Date"],
      "Stock Status": e["Stock Status"],
    };
  });

  const sheet = XLSX.utils.json_to_sheet(dataRows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, sheet, "Stock Valuation");

  const info = XLSX.utils.aoa_to_sheet(metaRows(meta, totals).filter((row) => row.length > 0));
  XLSX.utils.book_append_sheet(wb, info, "Report Info");

  const summary = XLSX.utils.aoa_to_sheet([
    ["Total Available Quantity", totals.totalAvailableQty],
    ["Total Stock Value", totals.totalStockValue],
    ["Batch Lines", totals.count],
  ]);
  XLSX.utils.book_append_sheet(wb, summary, "Totals");

  const date = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `Stock_Valuation_${date}.xlsx`);
}

export function exportStockValuationToPdf(
  rows: StockValuationRow[],
  meta: StockValuationExportMeta,
  totals: StockValuationTotals,
): void {
  const tableRows = rows
    .map((row) => {
      const e = toExportRow(row);
      return `<tr>
        <td>${e.Product}</td>
        <td class="mono">${e.SKU}</td>
        <td>${e.UOM}</td>
        <td>${e["Pack Size"]}</td>
        <td class="num">${e["Units Per Pack"]}</td>
        <td class="mono">${e["Batch No"]}</td>
        <td>${e.Warehouse}</td>
        <td class="num">${e["Available Qty"].toLocaleString("en-IN")}</td>
        <td class="num">${formatMoney(e["Cost Price (CP)"])}</td>
        <td class="num">${formatMoney(e["Stock Value"])}</td>
        <td>${e["Manufacturing Date"]}</td>
        <td>${e["Expiry Date"]}</td>
        <td>${e["Stock Status"]}</td>
      </tr>`;
    })
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${REPORT_NAME}</title>
  <style>
    @media print { @page { margin: 10mm; size: landscape; } }
    body { font-family: system-ui, sans-serif; font-size: 9px; padding: 16px; color: #111; }
    .header { display: flex; align-items: flex-start; gap: 12px; margin-bottom: 12px; }
    .logo { width: 36px; height: 36px; border-radius: 8px; background: linear-gradient(135deg, #F47920, #D96A10); color: #fff; font-weight: 800; font-size: 13px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
    h1 { font-size: 15px; margin: 0 0 2px; color: #1A3A96; }
    .company { font-size: 11px; font-weight: 600; margin: 0 0 4px; }
    .meta { color: #555; font-size: 9px; line-height: 1.5; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    th, td { border: 1px solid #ddd; padding: 4px 5px; text-align: left; }
    th { background: #fff; font-size: 8px; text-transform: uppercase; font-weight: 700; }
    .num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
    .mono { font-family: ui-monospace, monospace; font-size: 8px; }
    tfoot td { font-weight: 700; background: #f8fafc; border-top: 2px solid #ccc; }
    .footer-meta { margin-top: 12px; font-size: 9px; color: #666; }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">DS</div>
    <div>
      <p class="company">${COMPANY_NAME}</p>
      <h1>${REPORT_NAME}</h1>
      <p class="meta">
        As On Date: ${meta.asOnDate}<br />
        Financial Year: ${meta.financialYear}<br />
        Warehouse: ${meta.warehouse} · Category: ${meta.category} · Product: ${meta.product}<br />
        Stock Status: ${meta.stockStatus} · Search: ${meta.search || "—"}<br />
        Generated By: ${ACCOUNTS_CURRENT_USER} · Generated On: ${generatedOnLabel()}
      </p>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Product</th>
        <th>SKU</th>
        <th>UOM</th>
        <th>Pack Size</th>
        <th class="num">Units/Pack</th>
        <th>Batch No</th>
        <th>Warehouse</th>
        <th class="num">Available Qty</th>
        <th class="num">Cost Price (CP)</th>
        <th class="num">Stock Value</th>
        <th>Mfg Date</th>
        <th>Expiry Date</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
    <tfoot>
      <tr>
        <td colspan="7">Totals</td>
        <td class="num">${totals.totalAvailableQty.toLocaleString("en-IN")}</td>
        <td></td>
        <td class="num">${formatMoney(totals.totalStockValue)}</td>
        <td colspan="2"></td>
      </tr>
    </tfoot>
  </table>
  <p class="footer-meta">
    Total Available Quantity: ${totals.totalAvailableQty.toLocaleString("en-IN")} ·
    Total Stock Value: ₹ ${formatMoneyNumber(totals.totalStockValue)} ·
    ${totals.count} batch line(s)
  </p>
  <script>window.onload = () => window.print();</script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
}
