import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import { formatMoney, formatMoneyNumber } from "@/lib/accounts/money-format";
import { getReceivableStatusLabel, type ReceivableStatus } from "@/lib/accounts/receivables-data";

const COMPANY_NAME = "Dharitri Sutra Agri Solutions Pvt Ltd";

export interface ReceivablesExportMeta {
  reportName: string;
  financialYear?: string;
  dateFrom?: string;
  dateTo?: string;
  asOnDate?: string;
  customer?: string;
  status?: string;
  search?: string;
}

function generatedOnLabel(): string {
  return new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function metaRows(meta: ReceivablesExportMeta): string[][] {
  const rows: string[][] = [
    ["Company Name", COMPANY_NAME],
    ["Report Name", meta.reportName],
    ["Generated By", ACCOUNTS_CURRENT_USER],
    ["Generated On", generatedOnLabel()],
  ];
  if (meta.financialYear) rows.push(["Financial Year", meta.financialYear]);
  if (meta.asOnDate) rows.push(["As On Date", meta.asOnDate]);
  if (meta.dateFrom && meta.dateTo) rows.push(["Date Range", `${meta.dateFrom} to ${meta.dateTo}`]);
  if (meta.customer) rows.push(["Customer", meta.customer]);
  if (meta.status) rows.push(["Status", meta.status]);
  if (meta.search) rows.push(["Search", meta.search || "—"]);
  return rows;
}

export async function exportReceivablesToExcel(
  rows: Record<string, string | number>[],
  meta: ReceivablesExportMeta,
  filePrefix: string,
): Promise<void> {
  const XLSX = await import("xlsx");
  const sheet = XLSX.utils.json_to_sheet(rows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, sheet, meta.reportName.slice(0, 31));
  const info = XLSX.utils.aoa_to_sheet(metaRows(meta));
  XLSX.utils.book_append_sheet(wb, info, "Report Info");
  const date = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `${filePrefix}_${date}.xlsx`);
}

export function exportReceivablesToPdf(
  headers: string[],
  rows: string[][],
  meta: ReceivablesExportMeta,
): void {
  const tableRows = rows
    .map(
      (cells) =>
        `<tr>${cells.map((c, i) => `<td class="${i > 4 ? "num" : ""}">${c}</td>`).join("")}</tr>`,
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${meta.reportName}</title>
  <style>
    @media print { @page { margin: 12mm; } }
    body { font-family: system-ui, sans-serif; font-size: 10px; padding: 20px; color: #111; }
    h1 { font-size: 15px; margin: 0 0 8px; color: #1A3A96; }
    .meta { color: #555; font-size: 9px; line-height: 1.5; margin-bottom: 12px; }
    table { width: 100%; border-collapse: collapse; }
    th, td { border: 1px solid #ddd; padding: 5px 6px; text-align: left; }
    th { background: #fff; font-size: 9px; text-transform: uppercase; font-weight: 700; }
    .num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
  </style>
</head>
<body>
  <h1>${meta.reportName}</h1>
  <div class="meta">${metaRows(meta).map(([k, v]) => `${k}: ${v}`).join(" · ")}</div>
  <table>
    <thead><tr>${headers.map((h) => `<th>${h}</th>`).join("")}</tr></thead>
    <tbody>${tableRows}</tbody>
  </table>
</body>
</html>`;

  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(html);
  w.document.close();
  w.focus();
  w.print();
}

export function formatExportStatus(status: ReceivableStatus): string {
  return getReceivableStatusLabel(status);
}

export function formatExportAmount(amount: number): string {
  return formatMoneyNumber(amount);
}

export function formatExportMoney(amount: number): string {
  return formatMoney(amount);
}
