import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import { formatMoney, formatMoneyNumber } from "@/lib/accounts/money-format";
import type { GstSummaryExportRow, GstSummaryTotals } from "./gst-summary-data";

const COMPANY_NAME = "Dharitri Sutra Agri Solutions Pvt Ltd";
const REPORT_NAME = "GST Summary";

export interface GstSummaryExportMeta {
  dateFrom: string;
  dateTo: string;
  financialYear: string;
  gstType: string;
  gstRate: string;
  search: string;
}

function generatedOnLabel(): string {
  return new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function formatExportAmount(amount: number | null): string {
  if (amount == null) return "";
  if (amount < 0) return `(${formatMoney(Math.abs(amount))})`;
  return formatMoney(amount);
}

function metaRows(meta: GstSummaryExportMeta) {
  return [
    ["Company Name", COMPANY_NAME],
    ["Report Name", REPORT_NAME],
    ["Date Range", `${meta.dateFrom} to ${meta.dateTo}`],
    ["Financial Year", meta.financialYear],
    ["GST Type", meta.gstType],
    ["GST Rate", meta.gstRate],
    ["Search", meta.search || "—"],
    ["Generated By", ACCOUNTS_CURRENT_USER],
    ["Generated On", generatedOnLabel()],
  ];
}

export async function exportGstSummaryToExcel(
  rows: GstSummaryExportRow[],
  meta: GstSummaryExportMeta,
  totals: GstSummaryTotals,
): Promise<void> {
  const XLSX = await import("xlsx");

  const dataRows = rows.map((r) => ({
    "GST Type": r.gstType,
    "Taxable Value (₹)": r.taxableValue ?? "",
    "CGST (₹)": r.cgst ?? "",
    "SGST (₹)": r.sgst ?? "",
    "IGST (₹)": r.igst ?? "",
    "Total GST (₹)": r.totalGst ?? "",
    "Total Invoice Value (₹)": r.totalInvoiceValue ?? "",
  }));

  const sheet = XLSX.utils.json_to_sheet(dataRows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, sheet, "GST Summary");

  const info = XLSX.utils.aoa_to_sheet(metaRows(meta));
  XLSX.utils.book_append_sheet(wb, info, "Report Info");

  const summary = XLSX.utils.aoa_to_sheet([
    ["Total Output GST", totals.totalOutputGst],
    ["Total Input GST", totals.totalInputGst],
    ["Net GST Payable / Receivable", totals.netGstPayable],
  ]);
  XLSX.utils.book_append_sheet(wb, summary, "Totals");

  const date = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `GST_Summary_${date}.xlsx`);
}

export function exportGstSummaryToPdf(
  rows: GstSummaryExportRow[],
  meta: GstSummaryExportMeta,
  totals: GstSummaryTotals,
): void {
  const tableRows = rows
    .map((r) => {
      const rowClass =
        r.rowType === "section"
          ? "section"
          : r.rowType === "total" || r.rowType === "net"
            ? "total"
            : "line";
      return `<tr class="${rowClass}">
        <td>${r.gstType}</td>
        <td class="num">${formatExportAmount(r.taxableValue)}</td>
        <td class="num">${formatExportAmount(r.cgst)}</td>
        <td class="num">${formatExportAmount(r.sgst)}</td>
        <td class="num">${formatExportAmount(r.igst)}</td>
        <td class="num">${formatExportAmount(r.totalGst)}</td>
        <td class="num">${formatExportAmount(r.totalInvoiceValue)}</td>
      </tr>`;
    })
    .join("");

  const netLabel =
    totals.netGstPayable >= 0 ? "Net GST Payable" : "Net GST Receivable";
  const netClass = totals.netGstPayable >= 0 ? "payable" : "receivable";

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${REPORT_NAME}</title>
  <style>
    @media print { @page { margin: 12mm; } }
    body { font-family: system-ui, sans-serif; font-size: 10px; padding: 20px; color: #111; }
    .header { display: flex; align-items: flex-start; gap: 12px; margin-bottom: 14px; }
    .logo { width: 36px; height: 36px; border-radius: 8px; background: linear-gradient(135deg, #F47920, #D96A10); color: #fff; font-weight: 800; font-size: 13px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
    h1 { font-size: 15px; margin: 0 0 2px; color: #1A3A96; }
    .company { font-size: 11px; font-weight: 600; margin: 0 0 4px; }
    .meta { color: #555; font-size: 9px; line-height: 1.5; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    th, td { border: 1px solid #ddd; padding: 5px 6px; text-align: left; }
    th { background: #fff; font-size: 9px; text-transform: uppercase; font-weight: 700; }
    .num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
    tr.section td { font-weight: 700; background: #f8fafc; text-transform: uppercase; font-size: 9px; letter-spacing: 0.04em; color: #1A3A96; }
    tr.total td { font-weight: 700; background: #f0f0f0; border-top: 2px solid #ccc; }
    .footer-meta { margin-top: 14px; font-size: 9px; color: #666; }
    .net-msg { margin-top: 10px; font-size: 11px; font-weight: 700; }
    .net-msg.payable { color: #B85508; }
    .net-msg.receivable { color: #267A2E; }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">DS</div>
    <div>
      <p class="company">${COMPANY_NAME}</p>
      <h1>${REPORT_NAME}</h1>
      <p class="meta">
        Date Range: ${meta.dateFrom} to ${meta.dateTo}<br />
        Financial Year: ${meta.financialYear}<br />
        GST Type: ${meta.gstType} · GST Rate: ${meta.gstRate}<br />
        Generated By: ${ACCOUNTS_CURRENT_USER} · Generated On: ${generatedOnLabel()}
      </p>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th>GST Type</th>
        <th class="num">Taxable Value</th>
        <th class="num">CGST</th>
        <th class="num">SGST</th>
        <th class="num">IGST</th>
        <th class="num">Total GST</th>
        <th class="num">Total Invoice Value</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
  </table>
  <p class="net-msg ${netClass}">
    ${netLabel}: ₹ ${formatMoneyNumber(Math.abs(totals.netGstPayable))}
  </p>
  <p class="footer-meta">
    Total Output GST: ₹ ${formatMoneyNumber(totals.totalOutputGst)} ·
    Total Input GST: ₹ ${formatMoneyNumber(totals.totalInputGst)}
  </p>
  <script>window.onload = () => window.print();</script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
}
