export { RecordDetailLayout } from "./RecordDetailLayout";
export { RecordDetailPage } from "./RecordDetailPage";
export { RecordSectionCard } from "./RecordSectionCard";
export { RecordKvRow } from "./RecordKvRow";
export { RecordDetailSidebar } from "./RecordDetailSidebar";
export { RecordMiniTable } from "./RecordMiniTable";
export { StatusBadge } from "./StatusBadge";
export { RecordStatusPill } from "./RecordStatusPill";
export { RecordStatusToggle } from "./RecordStatusToggle";
export { RecordEntityAvatar, getInitials } from "./RecordEntityAvatar";
export { RecordKpiBar } from "./RecordKpiBar";
export { RecordDetailTabs } from "./RecordDetailTabs";
export type * from "./types";
export { OVERVIEW_TAB } from "./types";
