import { ACCOUNTS_CURRENT_USER } from "@/lib/accounts/config";
import {
  balanceSideLabel,
  formatBalanceAmount,
  formatMoney,
  formatMoneyWithSide,
} from "@/lib/accounts/money-format";
import { resolveDrCrColumnSide } from "@/lib/accounts/running-balance";
import type {
  GeneralLedgerDisplayRow,
  GeneralLedgerListingRow,
  GeneralLedgerSummary,
} from "./general-ledger-data";

const COMPANY_NAME = "Dharitri Sutra Agri Solutions Pvt Ltd";
const REPORT_NAME = "General Ledger";

export interface GeneralLedgerExportMeta {
  dateFrom: string;
  dateTo: string;
  financialYear: string;
}

function generatedOnLabel(): string {
  return new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function exportRowFields(r: GeneralLedgerDisplayRow) {
  const isOpening = r.kind === "opening";
  const isBalanceRow = r.kind === "opening" || r.kind === "closing";
  const drCrSide = resolveDrCrColumnSide({
    debit: r.debit,
    credit: r.credit,
    runningBalanceType: r.runningBalanceType,
    isBalanceRow,
  });
  return {
    Date: r.date,
    "Voucher Type": isOpening ? "Opening" : r.voucherType,
    "Voucher No.": isOpening || !r.voucherNo ? "—" : r.voucherNo,
    "Reference No.": isOpening || !r.referenceNo ? "—" : r.referenceNo,
    Particulars: r.particularsNarration,
    "Debit (₹)": r.debit || "",
    "Credit (₹)": r.credit || "",
    "Running Balance (₹)": r.runningBalance ? formatMoney(r.runningBalance) : "",
    "Dr/Cr": balanceSideLabel(drCrSide),
  };
}

function statementExportRows(rows: GeneralLedgerDisplayRow[]): GeneralLedgerDisplayRow[] {
  return rows.filter((r) => r.kind !== "closing");
}

export async function exportGeneralLedgerToExcel(
  rows: GeneralLedgerDisplayRow[],
  summary: GeneralLedgerSummary,
  meta: GeneralLedgerExportMeta,
): Promise<void> {
  const XLSX = await import("xlsx");

  const exportRows = statementExportRows(rows);
  const dataRows = exportRows.map((r) => exportRowFields(r));

  const sheet = XLSX.utils.json_to_sheet(dataRows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, sheet, "General Ledger");

  const info = XLSX.utils.aoa_to_sheet([
    ["Company Name", COMPANY_NAME],
    ["Report Name", REPORT_NAME],
    ["Ledger Name", summary.ledgerName],
    ["Ledger Code", summary.ledgerCode],
    ["Ledger Type", summary.ledgerType],
    ["Parent Group", summary.parentGroup],
    ["Date Range", `${meta.dateFrom} to ${meta.dateTo}`],
    ["Financial Year", meta.financialYear],
    ["Opening Balance", formatBalanceAmount(summary.openingBalance, summary.openingBalanceType)],
    ["Total Debit", summary.totalDebit],
    ["Total Credit", summary.totalCredit],
    ["Closing Balance", formatBalanceAmount(summary.closingBalance, summary.closingBalanceType)],
    ["Current Balance", formatBalanceAmount(summary.currentBalance, summary.currentBalanceType)],
    ["Generated By", ACCOUNTS_CURRENT_USER],
    ["Generated On", generatedOnLabel()],
  ]);
  XLSX.utils.book_append_sheet(wb, info, "Report Info");

  const safeName = summary.ledgerCode.replace(/[^\w-]+/g, "_");
  const date = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `General_Ledger_${safeName}_${date}.xlsx`);
}

export function exportGeneralLedgerToPdf(
  rows: GeneralLedgerDisplayRow[],
  summary: GeneralLedgerSummary,
  meta: GeneralLedgerExportMeta,
): void {
  const exportRows = statementExportRows(rows);
  const tableRows = exportRows
    .map((r) => {
      const f = exportRowFields(r);
      return `
    <tr class="${r.kind === "opening" ? "summary-row" : ""}">
      <td>${f.Date}</td>
      <td>${f["Voucher Type"]}</td>
      <td class="mono">${f["Voucher No."]}</td>
      <td class="mono">${f["Reference No."]}</td>
      <td>${f.Particulars}</td>
      <td class="num">${f["Debit (₹)"] || "—"}</td>
      <td class="num">${f["Credit (₹)"] || "—"}</td>
      <td class="num">${f["Running Balance (₹)"] || "—"}</td>
      <td class="center">${f["Dr/Cr"]}</td>
    </tr>`;
    })
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>General Ledger — ${summary.ledgerName}</title>
  <style>
    body { font-family: system-ui, sans-serif; font-size: 10px; padding: 16px; color: #111; }
    h1 { font-size: 16px; margin: 0 0 4px; color: #1A3A96; }
    .meta { color: #555; margin-bottom: 16px; font-size: 10px; line-height: 1.5; }
    table { width: 100%; border-collapse: collapse; }
    th, td { border: 1px solid #ddd; padding: 4px 6px; text-align: left; }
    th { background: #f5f5f5; font-size: 8px; text-transform: uppercase; position: sticky; top: 0; }
    .num { text-align: right; font-variant-numeric: tabular-nums; }
    .center { text-align: center; font-weight: 600; }
    .mono { font-family: ui-monospace, monospace; font-size: 9px; }
    .summary-row td { font-weight: 600; background: #fafafa; }
    .footer { margin-top: 12px; display: grid; grid-template-columns: repeat(5, 1fr); gap: 8px; font-size: 9px; }
    .footer-item { border: 1px solid #ddd; padding: 6px 8px; border-radius: 4px; }
    .footer-item label { display: block; color: #666; font-size: 8px; text-transform: uppercase; margin-bottom: 2px; }
    .footer-item strong { font-variant-numeric: tabular-nums; }
  </style>
</head>
<body>
  <h1>${summary.ledgerName}</h1>
  <p class="meta">
    ${summary.ledgerCode} · ${summary.ledgerType} · ${summary.parentGroup}<br />
    Period: ${meta.dateFrom} to ${meta.dateTo} · Financial Year: ${meta.financialYear}
  </p>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Voucher Type</th>
        <th>Voucher No.</th>
        <th>Reference No.</th>
        <th>Particulars</th>
        <th>Debit (₹)</th>
        <th>Credit (₹)</th>
        <th>Running Balance</th>
        <th>Dr/Cr</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
  </table>
  <div class="footer">
    <div class="footer-item"><label>Opening Balance</label><strong>${formatBalanceAmount(summary.openingBalance, summary.openingBalanceType)}</strong></div>
    <div class="footer-item"><label>Total Debit</label><strong>${formatMoney(summary.totalDebit)}</strong></div>
    <div class="footer-item"><label>Total Credit</label><strong>${formatMoney(summary.totalCredit)}</strong></div>
    <div class="footer-item"><label>Closing Balance</label><strong>${formatBalanceAmount(summary.closingBalance, summary.closingBalanceType)}</strong></div>
    <div class="footer-item"><label>Current Balance</label><strong>${formatBalanceAmount(summary.currentBalance, summary.currentBalanceType)}</strong></div>
  </div>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 400);
}

function listingRowFields(row: GeneralLedgerListingRow) {
  return {
    "Ledger Code": row.ledgerCode,
    "Ledger Name": row.ledgerName,
    "Ledger Type": row.ledgerType,
    "Parent Group": row.parentGroup,
    GSTIN: row.gstin,
    PAN: row.pan,
    "Opening Balance": formatMoneyWithSide(row.openingBalance, row.openingBalanceType),
    "Total Debit (₹)": row.totalDebit || "",
    "Total Credit (₹)": row.totalCredit || "",
    "Closing Balance": formatMoneyWithSide(row.closingBalance, row.closingBalanceType),
    "Last Transaction Date": row.lastTransactionDate ?? "—",
  };
}

export async function exportGeneralLedgerListingToExcel(
  rows: GeneralLedgerListingRow[],
  meta: GeneralLedgerExportMeta,
): Promise<void> {
  const XLSX = await import("xlsx");

  const dataRows = rows.map((r) => listingRowFields(r));
  const sheet = XLSX.utils.json_to_sheet(dataRows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, sheet, "General Ledger Listing");

  const info = XLSX.utils.aoa_to_sheet([
    ["Company Name", COMPANY_NAME],
    ["Report Name", `${REPORT_NAME} — Listing`],
    ["Date Range", `${meta.dateFrom} to ${meta.dateTo}`],
    ["Financial Year", meta.financialYear],
    ["Total Ledgers", rows.length],
    ["Generated By", ACCOUNTS_CURRENT_USER],
    ["Generated On", generatedOnLabel()],
  ]);
  XLSX.utils.book_append_sheet(wb, info, "Report Info");

  const date = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `General_Ledger_Listing_${date}.xlsx`);
}

export function exportGeneralLedgerListingToPdf(
  rows: GeneralLedgerListingRow[],
  meta: GeneralLedgerExportMeta,
): void {
  const tableRows = rows
    .map((row) => {
      const f = listingRowFields(row);
      return `
    <tr>
      <td class="mono">${f["Ledger Code"]}</td>
      <td>${f["Ledger Name"]}</td>
      <td>${f["Ledger Type"]}</td>
      <td>${f["Parent Group"]}</td>
      <td class="num">${f["Opening Balance"]}</td>
      <td class="num">${f["Total Debit (₹)"] || "—"}</td>
      <td class="num">${f["Total Credit (₹)"] || "—"}</td>
      <td class="num">${f["Closing Balance"]}</td>
      <td>${f["Last Transaction Date"]}</td>
    </tr>`;
    })
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>General Ledger Listing</title>
  <style>
    body { font-family: system-ui, sans-serif; font-size: 10px; padding: 16px; color: #111; }
    h1 { font-size: 16px; margin: 0 0 4px; color: #1A3A96; }
    .meta { color: #555; margin-bottom: 16px; font-size: 10px; line-height: 1.5; }
    table { width: 100%; border-collapse: collapse; }
    th, td { border: 1px solid #ddd; padding: 4px 6px; text-align: left; }
    th { background: #f5f5f5; font-size: 8px; text-transform: uppercase; }
    .num { text-align: right; font-variant-numeric: tabular-nums; }
    .mono { font-family: ui-monospace, monospace; font-size: 9px; }
  </style>
</head>
<body>
  <h1>General Ledger — All Ledgers</h1>
  <p class="meta">
    Period: ${meta.dateFrom} to ${meta.dateTo} · Financial Year: ${meta.financialYear}<br />
    Showing ${rows.length} ledger(s)
  </p>
  <table>
    <thead>
      <tr>
        <th>Ledger Code</th>
        <th>Ledger Name</th>
        <th>Ledger Type</th>
        <th>Parent Group</th>
        <th>Opening Balance</th>
        <th>Total Debit</th>
        <th>Total Credit</th>
        <th>Closing Balance</th>
        <th>Last Transaction</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
  </table>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 400);
}
