export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    LOGOUT: "/auth/logout",
    REFRESH_TOKEN: "/auth/refresh-token",
    VALIDATE_TOKEN: "/auth/validate_token",
    FORGOT_PASSWORD: "/auth/forgot-password",
    VERIFY_OTP: "/auth/verify-otp",
    RESET_PASSWORD: "/auth/reset-password",
  },
  MASTER: {
    CATEGORY: {
      LIST: "/master/category/list",
      CREATE: "/master/category/create",
      UPDATE: (id: string) => `/master/category/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/category/update-status/${id}`,
      EXPORT: "/master/category/export",
      VIEW: (id: string) => `/master/category/${id}`,
      DROPDOWN: "/master/category/dropdown",
      FILTER_DROPDOWN: "/master/category/filter-dropdown",
    },
    DOCUMENT_TYPE: {
      LIST: "/master/document-type/list",
      CREATE: "/master/document-type/create",
      UPDATE: (id: string) => `/master/document-type/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/document-type/update-status/${id}`,
      VIEW: (id: string) => `/master/document-type/${id}`,
      DROPDOWN: "/master/document-type/dropdown",
      EXPORT_CSV: "/master/document-type/export-csv",
      FILTER_DROPDOWN: "/master/document-type/filter-dropdown",
    },
    CUSTOMER_TYPE: {
      LIST: "/master/customer-type/list",
      CREATE: "/master/customer-type/create",
      UPDATE: (id: string) => `/master/customer-type/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/customer-type/update-status/${id}`,
      VIEW: (id: string) => `/master/customer-type/${id}`,
      EXPORT: "/master/customer-type/export",
      DROPDOWN: "/master/customer-type/dropdown",
      FILTER_DROPDOWN: "/master/customer-type/filter-dropdown",
    },
    GST: {
      LIST: "/master/gst/list",
      CREATE: "/master/gst/create",
      UPDATE: (id: string) => `/master/gst/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/gst/update-status/${id}`,
      VIEW: (id: string) => `/master/gst/${id}`,
      EXPORT: "/master/gst/export",
      DROPDOWN: "/master/gst/dropdown",
      FILTER_DROPDOWN: "/master/gst/filter-dropdown",
    },
    HSN: {
      LIST: "/master/hsn/list",
      CREATE: "/master/hsn/create",
      UPDATE: (id: string) => `/master/hsn/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/hsn/update-status/${id}`,
      VIEW: (id: string) => `/master/hsn/${id}`,
      EXPORT: "/master/hsn/export",
      DROPDOWN: "/master/hsn/dropdown",
      FILTER_DROPDOWN: "/master/hsn/filter-dropdown",
    },
    CROP: {
      LIST: "/master/crop/list",
      CREATE: "/master/crop/create",
      UPDATE: (id: string) => `/master/crop/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/crop/toggle-status/${id}`,
      VIEW: (id: string) => `/master/crop/details/${id}`,
      EXPORT: "/master/crop/export",
      FILTER_DROPDOWN: "/master/crop/filter-dropdown",
      DROPDOWN: "/master/crop/dropdown",
    },
    EVENT_TYPE: {
      LIST: "/master/event-type/list",
      CREATE: "/master/event-type/create",
      UPDATE: (id: string) => `/master/event-type/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/event-type/update-status/${id}`,
      VIEW: (id: string) => `/master/event-type/${id}`,
      EXPORT: "/master/event-type/export",
      FILTER_DROPDOWN: "/master/event-type/filter-dropdown",
      DROPDOWN: "/master/event-type/dropdown",
      SUMMARY: "/master/event-type/summary",
    },
    BRAND: {
      LIST: "/master/brand/list",
      CREATE: "/master/brand/create",
      UPDATE: (id: string) => `/master/brand/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/brand/update-status/${id}`,
      VIEW: (id: string) => `/master/brand/${id}`,
      EXPORT: "/master/brand/export",
      FILTER_DROPDOWN: "/master/brand/filter-dropdown",
      DROPDOWN: "/master/brand/dropdown",
    },
    CFU: {
      LIST: "/master/cfu-master/list",
      CREATE: "/master/cfu-master/create",
      UPDATE: (id: string) => `/master/cfu-master/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/cfu-master/update-status/${id}`,
      VIEW: (id: string) => `/master/cfu-master/${id}`,
      EXPORT: "/master/cfu-master/export",
      FILTER_DROPDOWN: "/master/cfu-master/filter-dropdown",
      DROPDOWN: "/master/cfu-master/dropdown",
      SUMMARY: "/master/cfu-master/summary",
    },
    SEGMENT: {
      LIST: "/master/segment/list",
      CREATE: "/master/segment/create",
      UPDATE: (id: string) => `/master/segment/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/segment/toggle-status/${id}`,
      VIEW: (id: string) => `/master/segment/details/${id}`,
      EXPORT: "/master/segment/export",
      PREVIEW_NUMBER: "/master/segment/preview-number",
      FILTER_DROPDOWN: "/master/segment/filter-dropdown",
      DROPDOWN: "/master/segment/dropdown",
    },
    TDS: {
      LIST: "/master/tds/list",
      CREATE: "/master/tds/create",
      UPDATE: (id: string) => `/master/tds/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/tds/toggle-status/${id}`,
      VIEW: (id: string) => `/master/tds/details/${id}`,
      EXPORT: "/master/tds/export",
      FILTER_DROPDOWN: "/master/tds/filter-dropdown",
      DROPDOWN: "/master/tds/dropdown",
    },
    UNIT: {
      LIST: "/master/unit/list",
      CREATE: "/master/unit/create",
      UPDATE: (id: string) => `/master/unit/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/unit/toggle-status/${id}`,
      VIEW: (id: string) => `/master/unit/details/${id}`,
      EXPORT: "/master/unit/export",
      FILTER_DROPDOWN: "/master/unit/filter-dropdown",
      DROPDOWN: "/master/unit/dropdown",
    },
    FORMULATION: {
      LIST: "/master/formulation/list",
      CREATE: "/master/formulation/create",
      UPDATE: (id: string) => `/master/formulation/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/formulation/toggle-status/${id}`,
      VIEW: (id: string) => `/master/formulation/details/${id}`,
      EXPORT: "/master/formulation/export",
      FILTER_DROPDOWN: "/master/formulation/filter-dropdown",
      DROPDOWN: "/master/formulation/dropdown",
    },
    PRODUCT: {
      LIST: "/master/product/list",
      CREATE: "/master/product/create",
      UPDATE: (id: string) => `/master/product/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/product/update-status/${id}`,
      VIEW: (id: string) => `/master/product/${id}`,
      EXPORT: "/master/product/export",
      PREVIEW_NUMBER: "/master/product/preview-number",
      DROPDOWN: "/master/product/dropdown",
      PRICING: "/master/product/pricing",
    },
    PRICING: {
      DROPDOWN: "/master/product-pricing/dropdown",
    },
    WAREHOUSE: {
      DROPDOWN: "/master/warehouse/dropdown",
      LIST: "/master/warehouse/list",
      CREATE: "/master/warehouse/create",
      UPDATE: (id: string) => `/master/warehouse/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/warehouse/toggle-status/${id}`,
      VIEW: (id: string) => `/master/warehouse/details/${id}`,
      EXPORT: "/master/warehouse/export",
      PREVIEW_NUMBER: "/master/warehouse/preview-number",
    },
    SUPPLIER: {
      LIST: "/master/supplier/list",
      CREATE: "/master/supplier/create",
      UPDATE: (id: string) => `/master/supplier/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/supplier/toggle-status/${id}`,
      VIEW: (id: string) => `/master/supplier/details/${id}`,
      EXPORT: "/master/supplier/export",
      PREVIEW_NUMBER: "/master/supplier/preview-number",
      DROPDOWN: "/master/supplier/dropdown",
      DETAILS: (id: string) => `/master/supplier/details/${id}`,
    },
    CUSTOMER: {
      LIST: "/master/customer/list",
      CREATE: "/master/customer/create",
      UPDATE: (id: string) => `/master/customer/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/customer/update-status/${id}`,
      VIEW: (id: string) => `/master/customer/${id}`,
      EXPORT: "/master/customer/export",
      PREVIEW_NUMBER: "/master/customer/preview-number",
      DROPDOWN: "/master/customer/dropdown",
    },
    SUPPLIER_TYPE: {
      LIST: "/master/supplier-type/list",
      CREATE: "/master/supplier-type/create",
      UPDATE: (id: string) => `/master/supplier-type/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/supplier-type/toggle-status/${id}`,
      VIEW: (id: string) => `/master/supplier-type/details/${id}`,
      EXPORT: "/master/supplier-type/export",
      DROPDOWN: "/master/supplier-type/dropdown",
    },
  },
  PROCUREMENT: {
    PURCHASE_ORDER: {
      LIST: "/procurement/purchase-order/list",
      SUMMARY: "/procurement/purchase-order/summary",
      FILTER_DROPDOWN: "/procurement/purchase-order/filter-dropdown",
      EXPORT: "/procurement/purchase-order/export",
      PREVIEW_NUMBER: "/procurement/purchase-order/preview-number",
      CREATE: "/procurement/purchase-order/create",
      UPDATE: (id: string) => `/procurement/purchase-order/update/${id}`,
      DETAILS: (id: string) => `/procurement/purchase-order/details/${id}`,
      FOLLOWUP_CREATE: "/procurement/purchase-order/followup/create",
      INVOICE_UPLOAD: "/procurement/purchase-order/invoice/upload",
      SHORT_CLOSE: "/procurement/purchase-order/short-close",
      ACTION: "/procurement/purchase-order/action",
      CLOSE: "/procurement/purchase-order/close",
      CANCEL: "/procurement/purchase-order/cancel",
      APPROVE: "/procurement/purchase-order/approve",
      REJECT: "/procurement/purchase-order/reject",
    },
    PURCHASE_RETURN: {
      LIST: "/procurement/purchase-order-return/list",
      EXPORT: "/procurement/purchase-order-return/export",
      PREVIEW_NUMBER: "/procurement/purchase-order-return/preview-number",
      ELIGIBLE_ITEMS: "/procurement/purchase-order-return/eligible-items",
      FILTER_DROPDOWN: "/procurement/purchase-order-return/filter-dropdown",
      CREATE: "/procurement/purchase-order-return/create",
      UPDATE: (id: string) => `/procurement/purchase-order-return/update/${id}`,
      DETAILS: (id: string) => `/procurement/purchase-order-return/details/${id}`,
    },
  },
  SALES: {
    SALES_ORDER: {
      NEXT_SO_NUMBER: "/sales/sales-order/next-so-number",
      FILTER: "/sales/sales-order/filter",
      LIST: "/sales/sales-order/list",
      EXPORT: "/sales/sales-order/export",
      CREATE: "/sales/sales-order/create",
      DETAILS: (id: string) => `/sales/sales-order/${id}`,
      UPDATE: (id: string) => `/sales/sales-order/update/${id}`,
      APPROVE_REJECT: (id: string) => `/sales/sales-order/${id}/approve-reject`,
      CANCEL: (id: string) => `/sales/sales-order/${id}/cancel`,
      SPLIT: (id: string) => `/sales/sales-order/${id}/split`,
      DOWNLOAD_PI: (id: string) => `/sales/sales-order/${id}/download-pi`,
    },
    STOCK_TRANSFER: {
      SUMMARY: "/sales/stock-transfer/summary",
      NEXT_NUMBER: "/sales/stock-transfer/next-number",
      DROPDOWN: "/sales/stock-transfer/dropdown",
      FILTER: "/sales/stock-transfer/filter",
      BATCHES: "/sales/stock-transfer/batches",
      LIST: "/sales/stock-transfer/list",
      EXPORT: "/sales/stock-transfer/export",
      CREATE: "/sales/stock-transfer/create",
      DETAILS: (id: string) => `/sales/stock-transfer/${id}`,
      UPDATE: (id: string) => `/sales/stock-transfer/update/${id}`,
      UPDATE_STATUS: (id: string) => `/sales/stock-transfer/${id}/status`,
      DOWNLOAD_NOTE: (id: string) => `/sales/stock-transfer/${id}/download-note`,
    },
    SAMPLE_ORDER: {
      NEXT_NUMBER: "/sales/sample-order/next-number",
      DROPDOWN: "/sales/sample-order/dropdown",
      FILTER: "/sales/sample-order/filter",
      LIST: "/sales/sample-order/list",
      CREATE: "/sales/sample-order/create",
      EXPORT: "/sales/sample-order/export",
      DETAILS: (id: string) => `/sales/sample-order/${id}`,
      UPDATE: (id: string) => `/sales/sample-order/update/${id}`,
      UPDATE_STATUS: (id: string) => `/sales/sample-order/${id}/status`,
      DOWNLOAD_NOTE: (id: string) => `/sales/sample-order/${id}/download-note`,
    },
  },
  USER_MANAGEMENT: {
    USER: {
      LIST: "/user-management/user/list",
      CREATE: "/user-management/user/create",
      UPDATE: (id: string) => `/user-management/user/update/${id}`,
      STATUS_UPDATE: (id: string) => `/user-management/user/update-status/${id}`,
      VIEW: (id: string) => `/user-management/user/${id}`,
      EXPORT: "/user-management/user/export-excel",
      FILTER: "/user-management/user/filter",
      DROPDOWN: "/user-management/user/dropdown",
      NEXT_EMPLOYEE_ID: "/user-management/user/next-employee-id",
      PERMISSIONS: (id: string) => `/user-management/user/permissions/${id}`,
      APPROVAL_USERS: "/user-management/user/approval-users",
    },
    DEPARTMENT: {
      LIST: "/user-management/department/list",
      CREATE: "/user-management/department/create",
      UPDATE: (id: string) => `/user-management/department/update/${id}`,
      STATUS_UPDATE: (id: string) => `/user-management/department/update-status/${id}`,
      VIEW: (id: string) => `/user-management/department/${id}`,
      EXPORT: "/user-management/department/export-csv",
      FILTER: "/user-management/department/filter",
      DROPDOWN: "/user-management/department/dropdown",
    },
    ROLE: {
      LIST: "/user-management/role/list",
      CREATE: "/user-management/role/create",
      UPDATE: (id: string) => `/user-management/role/update/${id}`,
      STATUS_UPDATE: (id: string) => `/user-management/role/update-status/${id}`,
      VIEW: (id: string) => `/user-management/role/${id}`,
      EXPORT: "/user-management/role/export-csv",
      FILTER: "/user-management/role/filter",
      DROPDOWN: "/user-management/role/dropdown",
    },
    GEOGRAPHY: {
      DROPDOWN: "/user-management/geography/dropdown",
    },
    TEMPLATE: {
      LIST: "/user-management/template/list",
      CREATE: "/user-management/template/create",
      UPDATE: (id: string) => `/user-management/template/update/${id}`,
      STATUS_UPDATE: (id: string) => `/user-management/template/update-status/${id}`,
      VIEW: (id: string) => `/user-management/template/${id}`,
      DROPDOWN: "/user-management/template/dropdown",
    },
  },
  MASTER_DROPDOWNS: {
    CUSTOMER: "/master/customer/dropdown",
    CUSTOMER_DETAILS: (id: string) => `/master/customer/${id}`,
    WAREHOUSE: "/master/warehouse/dropdown",
    PRODUCT: "/master/product/dropdown",
    PRICING: "/master/product-pricing/dropdown",
  },
  WAREHOUSE: {
    PACKING_LIST: {
      BATCHES: "/warehouse/packing-list/batches",
      FILTER_DROPDOWN: "/warehouse/packing-list/filter-dropdown",
      LIST: "/warehouse/packing-list/list",
      CREATE: "/warehouse/packing-list/create",
      DETAILS: (id: string) => `/warehouse/packing-list/details/${id}`,
      REVERT: (id: string) => `/warehouse/packing-list/revert/${id}`,
    },
    PACKING_DONE: {
      PREVIEW_NUMBER: "/warehouse/packing-done/preview-number",
      SUMMARY: "/warehouse/packing-done/summary",
      FILTER_DROPDOWN: "/warehouse/packing-done/filter-dropdown",
      LIST: "/warehouse/packing-done/list",
      CREATE: "/warehouse/packing-done/create",
      DETAILS: (id: string) => `/warehouse/packing-done/details/${id}`,
      UPDATE: (id: string) => `/warehouse/packing-done/update/${id}`,
      REVERT: (id: string) => `/warehouse/packing-done/revert/${id}`,
    },
  },
};
