export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    LOGOUT: "/auth/logout",
    REFRESH_TOKEN: "/auth/refresh-token",
    VALIDATE_TOKEN: "/auth/validate_token",
    FORGOT_PASSWORD: "/auth/forgot-password",
    VERIFY_OTP: "/auth/verify-otp",
    RESET_PASSWORD: "/auth/reset-password",
  },
  MASTER: {
    CATEGORY: {
      LIST: "/master/category/list",
      CREATE: "/master/category/create",
      UPDATE: (id: string) => `/master/category/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/category/update-status/${id}`,
      EXPORT: "/master/category/export",
      VIEW: (id: string) => `/master/category/${id}`,
    },
    DOCUMENT_TYPE: {
      LIST: "/master/document-type/list",
      CREATE: "/master/document-type/create",
      UPDATE: (id: string) => `/master/document-type/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/document-type/update-status/${id}`,
      VIEW: (id: string) => `/master/document-type/${id}`,
      DROPDOWN: "/master/document-type/dropdown",
      EXPORT_CSV: "/master/document-type/export-csv",
    },
    CUSTOMER_TYPE: {
      LIST: "/master/customer-type/list",
      CREATE: "/master/customer-type/create",
      UPDATE: (id: string) => `/master/customer-type/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/customer-type/update-status/${id}`,
      VIEW: (id: string) => `/master/customer-type/${id}`,
      EXPORT: "/master/customer-type/export",
    },
    GST: {
      LIST: "/master/gst/list",
      CREATE: "/master/gst/create",
      UPDATE: (id: string) => `/master/gst/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/gst/update-status/${id}`,
      VIEW: (id: string) => `/master/gst/${id}`,
      EXPORT: "/master/gst/export",
      DROPDOWN: "/master/gst/dropdown",
    },
    HSN: {
      LIST: "/master/hsn/list",
      CREATE: "/master/hsn/create",
      UPDATE: (id: string) => `/master/hsn/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/hsn/update-status/${id}`,
      VIEW: (id: string) => `/master/hsn/${id}`,
      EXPORT: "/master/hsn/export",
    },
    SEGMENT: {
      LIST: "/master/segment/list",
      CREATE: "/master/segment/create",
      UPDATE: (id: string) => `/master/segment/update/${id}`,
      STATUS_UPDATE: (id: string) => `/master/segment/toggle-status/${id}`,
      VIEW: (id: string) => `/master/segment/details/${id}`,
      EXPORT: "/master/segment/export",
      PREVIEW_NUMBER: "/master/segment/preview-number",
    },
  },
};
