name: Frontend Deploy - pvb.dev.metaphi.in
on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: self-hosted
    env:
      PATH: /root/.nvm/versions/node/v20.19.6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PM2_HOME: /root/.pm2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Verify node, npm and pm2
        run: |
          node -v
          npm -v
          pm2 -v
      - name: Copy files to deployment directory
        run: |
          rsync -av --delete \
                    --exclude='.git' \
                    --exclude='node_modules' \
                    --exclude='.env' \
                    ./ /var/www/pvb.dev.metaphi.in/ /var/www/pvb.dev1.metaphi.in/  
      - name: Install dependencies
        working-directory: /var/www/pvb.dev.metaphi.in
        run: npm i && npm run build

      - name: pm2 restart
        run: pm2 restart pvb.dev.metaphi.in
